### ISSUE TITLE
Security, user and pass directly on js?

### ISSUE THREAD

**Issue by rogeliogamez92** [neo4j-contrib/neovis.js#101]
Hello!

I am trying to use this library to visualize a neo4j graph, but my issue is security. I see that I need to have the user and pass directly on javascript, is there a way to avoid this?

**Comment by thebestnom** [comment]
Not really, as the password need to get somehow to client side, my suggestion is to have a read only account and have that in the client...

**Comment by babyrusa** [comment]
@rogeliogamez92 I'm wondering the same

**Comment by babyrusa** [comment]
@thebestnom readonly account neo4j right?

**Comment by thebestnom** [comment]
Yes. Another way now that I think about that is letting the user enter his user/pass

**Comment by babyrusa** [comment]
@thebestnom  can u clarify the method u just said ?

**Comment by thebestnom** [comment]
If you know that all your users have an account in the main neo4j db, you can add a user password form and use that as the neovis.js user password

**Comment by babyrusa** [comment]
Thank you

**Comment by Amal-David** [comment]
@thebestnom Would it be possible to serve data from server and only render it in frontend? Any data format that is available? perhaps nodejs or django?

**Comment by thebestnom** [comment]
@Amal-David currently neovis.js does not accept any data that doesn't come directly from the driver, meaning that it will only render things if you do your query on client, my only suggestion if you want to do the query on server site currently is to use vis.js instead

**Comment by kjoshi** [comment]
As another option (since creating a read-only user is only available in the Enterprise Edition of Neo4j, as far as I understand), you could set `dbms.read_only=true` in `conf/neo4j.conf` to prevent anything from being created or deleted if somebody did manage to find the password and connect to the database.

Not ideal but may be Ok for a temporary solution?

**Comment by alete89** [comment]
isn't there a way to fetch nodes and edges (or any data structure needed) from a custom API instead of connecting frontend directly to Neo4j? I was thinking on using neo4j nodejs driver on backend and getting it data from an endpoint.

**Comment by Amal-David** [comment]
That's the approach I have taken and routing data through Neo4j HTTP API in the backend. However using Visjs Network in the frontend to show graphs as it offered a bit of flexibility and easy to integrate as well.

**Comment by alete89** [comment]
@Amal-David Would you mind to briefly describe what you did in order to achieve that? 
- How did you passed the data into NeoVis in order to render it?
- Did you have to transform the data structure in any way?

Thanks for your collaboration.

**Comment by Amal-David** [comment]
@alete89 As mentioned before, I didn't use neovis, rather a forked version of this [example](https://github.com/aamanlamba/graphvisjs) which uses visjs. I simply wrote a wrapper in the backend for [Neo4j HTTP API](https://neo4j.com/docs/http-api/current/actions/return-results-in-graph-format/) which returns data in graph format and then fed it to the frontend.

**Comment by alete89** [comment]
@Amal-David  Got it now. Thank you!!

**Comment by thebestnom** [comment]
Im pretty sure that's about everything we can discuss about this issue
Closing

**Comment by Rezu** [comment]
Why is this closed with the lingering security issue, if Amal-David was able to provide a fix, why not neovis?
https://github.com/aamanlamba/graphvisjs

**Comment by Milzi** [comment]
Yes, please add a way to execute it on the server-side or at least to allow to render an already fetched graph object.

**Comment by thebestnom** [comment]
> Yes, please add a way to execute it on the server-side or at least to allow to render an already fetched graph object. 

This is a client side library, I don't understand by what you mean server side? To render on server and display the image?
But to fetch data in other ways should be fairly easy and I can easily do that... Open a new issue with this idea and Ill try to do that today or at least next week (on 2.x)

**Comment by Milzi** [comment]
No, like many others, we were hoping that we could fetch the graph on the server side (to not expose the db to the internet) and then use neovis to render the graph in the frontend, but apparently that is not something it was build for, but nevertheless would be awesome to have.

**Comment by gg4u** [comment]
Any follow up on this?
