### ISSUE TITLE
index.d.ts : Change type of caption from boolean to string|boolean.

### ISSUE THREAD

**Issue by pschhikara88** [neo4j-contrib/neovis.js#102]
In Index.d.ts, please change the type of caption from boolean to string|boolean. 

Current type
export interface IRelationshipConfig {
    thickness?: string;
    caption?: boolean;
}

Expected type:
export interface IRelationshipConfig {
    thickness?: string;
    caption?: string|boolean;
}

Purpose for this:
currently it is accepting the string also and show the label on edge or relationship. But when we write a component using typescript in angular, it generated warning during the ng serve because of string to boolean mismatch. 

    ERROR in src/app/neovis.service.ts:34:17 - error TS2322: Type 'string' is not assignable to type 'boolean'.

    34                 caption: "level",
                       ~~~~~~~

      node_modules/neovis.js/index.d.ts:12:5
        12     caption?: boolean;
               ~~~~~~~
        The expected type comes from property 'caption' which is declared here on type 'IRelationshipConfig'

First is to avoid warning

2) string| boolean - give flexibility for both hide/show or change the caption of edge by different property of relationship.

**Comment by thebestnom** [comment]
I think you are right, but you can just open a PR, it should take you a few moments
