### ISSUE TITLE
font size can not be changed in css #viz

### ISSUE THREAD

**Issue by svod5306** [neo4j-contrib/neovis.js#108]
my language is chinese,but the size of label is too big,and how to substring the caption?
thanks a lot

**Comment by svod5306** [comment]
![image](https://user-images.githubusercontent.com/16983126/85866953-c8652400-b7fa-11ea-96be-7706caf3215e.png)

**Comment by thebestnom** [comment]
it looks that currently there is no way to change the font size, PR is welcomed!

**Comment by thebestnom** [comment]
Trivial in 2.x
