### ISSUE TITLE
how to hide server connect info？

### ISSUE THREAD

**Issue by svod5306** [neo4j-contrib/neovis.js#109]
because the neovis js run at client browser.so the user can see connection info including password and url.it is not safe.

**Comment by thebestnom** [comment]
https://github.com/neo4j-contrib/neovis.js/issues/101

**Comment by Rezu** [comment]
Why is this lingering security issue persisting, if Amal-David was able to provide a fix, why not neovis?
https://github.com/aamanlamba/graphvisjs

**Comment by thebestnom** [comment]
Never saw this repo in my life, what did he do to fix this?

**Comment by thebestnom** [comment]
He literaly sends neo4j:password as user and password, how is this a fix?

**Comment by Rezu** [comment]
@thebestnom in the following link, please see 2 threads above your closing thread: https://github.com/neo4j-contrib/neovis.js/issues/101
...
I think I see what you're saying, but:
- **graphvisjs:** the client-side file (TestVis.html) does not explicitly show the neo4j password in any of its AUTH variables, though yes, the app.js file does request the password be explicitly added to the var AUTHORIZATION, and someone could read this app.js file in the client browser, (though I'm guessing this app.js function content is meant to be placed and run from an actual 'server' file, so a user wouldn't be able to see the password from a browser).

- **neovis:** the client-side file (examples/index.html) explicitly requests url, user, and password:
`
var viz;
        function draw() {
            var config = {
                container_id: "viz",
                server_url: "bolt://localhost:7687",
                server_user: "neo4j",
                server_password: "neo4j",
`
...
It doesn't change the fact that this neovis package is using client-side authorization where that's typically frowned upon. It would be nice if neovis used best practices for server-side Authorization.

**Comment by Rezu** [comment]
Ah it appears I have an older version of neovis, In the latest repo, I see a file (examples/form-example.html) which appears to pass the user's neo4j server auth to the 'server side'. 
Which file carries this neo4j server-side auth code?
Can you or someone else please confirm that's what is happening here? If this is true, it would appear this is a solution to this issue.

**Comment by thebestnom** [comment]
Yes, thats correct, you need to pass to neovis.js the user and password, the problem in this thread is that the client side needs password for db, but it's a security problem in neo4j and not in neovis...

**Comment by thebestnom** [comment]
Btw, Im pretty sure that neo4j driver have a way to connect to a non db server somehow, and neovis 2.0.0 can get driver instead of configs so it might help (im not 100% on that)

**Comment by Rezu** [comment]
@thebestnom Thanks, tho I'm not quite sure what you're referring to. Any chance you can point me to a site or example?

**Comment by thebestnom** [comment]
https://neo4j.com/developer/kb/neo4j-security-benchmark/ this is a quick security guide and I don't see any mention about making it unavoidable from outside network if yoir user password is strong enough and letting the user entering it... Though not what you meant Im searching for the other thing I found last time
