### ISSUE TITLE
Can't Connect to Graphenedb instance of Neo4j

### ISSUE THREAD

**Issue by kave3** [neo4j-contrib/neovis.js#11]
Can't connect to Neo4j Graphene connection using:

var viz;
        function draw() {
            var config = {
                container_id: "viz",
                server_url: "bolt://....dbs.graphenedb.com:12345",
                server_user: "neo4j",
                server_password: "12345",

Here's the dev console report:

WebSocket connection to 'ws://....dbs.graphenedb.com:12345/' failed: Connection closed before receiving a handshake response

NeoVis_config: {container_id: "viz", server_url: "bolt://.....dbs.graphenedb.com:12345", server_user: "user", server_password: "12345", labels: {…}, …}_container: div#viz_data: {nodes: n, edges: n}_driver: Driver {_url: "....dbs.graphenedb.com:12345", _userAgent: "neo4j-javascript/0.0.0-dev", _openSessions: {…}, _sessionIdGenerator: 1, _token: {…}, …}_edges: n {_options: {…}, _data: {…}, length: 0, _fieldId: "id", _type: {…}, …}_network: null_nodes: n {_options: {…}, _data: {…}, length: 0, _fieldId: "id", _type: {…}, …}_query: "MATCH (n)-[r:BREWS]->(m) RETURN n,r,m Limit 5"proto: Object
neovis.js:12345 WebSocket connection to 'ws://....dbs.graphenedb.com:12345/' failed: Connection closed before receiving a handshake response

WebSocketChannel @ neovis.js:12345
neovis.js:12345 Error: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket readyState is: 3
at new Neo4jError (neovis.js:12345)
at newError (neovis.js:12345)
at WebSocketChannel._handleConnectionError (neovis.js:12345)

**Comment by johnymontana** [comment]
Does GrapheneDB require an encrypted connection for connecting to their instances? Try adding

```
encrypted: "ENCRYPTION_ON"
```

to your config object. This will trigger neo4j-driver to use an encrypted wss connection instead of the standard ws websocket connection.

**Comment by kaveUW** [comment]
Many Thanks for your follow up!!!

I added as suggested, but it's still not working and getting the same error.

var viz;
    function draw() {
        var config = {
            **encrypted: "ENCRYPTION_ON",**
            container_id: "viz",
            server_url: "bolt://hobby-ihj....dbs.graphenedb.com:24786",
            server_user: "abc",
            server_password: "123",

I don't think GrapheneDB is requiring an encrypted connection for connecting. For other data acquisitions within my Node.js app, I am able to connect to my GrapheneDB data set from my server.js file in this way:
const neo4j = require('neo4j-driver').v1;

const driver = neo4j.driver('bolt://hobby-ihj.....dbs.graphenedb.com:24786', neo4j.auth.basic('abc','123'));
const session = driver.session();


I am able to see the neovis visualization in my app by connecting to a second, local neo4j database:
                server_url: "bolt://localhost:7687",
                server_user: "neo4j",
                server_password: "neo4j",

Should the webpack.config.js file be integrated with my server.js file?

**Comment by Brachamul** [comment]
I'm also encountering this issue.

**Comment by kaveUW** [comment]
Hi @alexandrupetrescu94 & @Brachamul 
No, unfortunately I am still at a loss hoping for a solution that incorporates neovis.js and graphenedb.
I would ignore what victoriastuart posted as her example points to a local neo4j db not to graphenedb.

@johnymontana Any updates on being able to make this handshake work between these actors?
Graphenedb gives us the following connection options, neither work:
BOLT: bolt://abc123.dbs.graphenedb.com:24786
REST: https://abc123l.dbs.graphenedb.com:24780/db/data/

**Comment by Brachamul** [comment]
After speaking with the GrapheneDB people, they told me that they didn't want to support browser connections because of the inherent security issues of having your api keys in the front-end code.
