### ISSUE TITLE
Config : Server URL take off params

### ISSUE THREAD

**Issue by FloozeIT** [neo4j-contrib/neovis.js#111]
Hi,
I'm currently implementing NeovisJS in an angular project and i have a problem of configuration in production.
When i want to pass to my config an url with params like : "bolt://mydomain.com/socket", the websocket who is open is : ws://mydomain.com:7687/ and not : "bolt://mydomain.com/socket".
If anyone has a solution, i will be happy to hear it  💯 

Thanks

**Comment by thebestnom** [comment]
Browsers doesn't support bolt so it uses websocket to implement it, this is normal

**Comment by FloozeIT** [comment]
Sorry I made a little mistake, I meant that the settings were deleted and the port it's replace by 7687. Instead of : ws://mydomain.com/socket it's : ws://mydomain.com:7687. And in my case i want ws://mydomain.com/socket when i pass bolt://mydomain.com/socket in my config.

Thanks

**Comment by thebestnom** [comment]
How do you send the port?

**Comment by FloozeIT** [comment]
The port is not the main problem ! The problem it's the escape of params!

**Comment by FloozeIT** [comment]
When in my config i pass : server_url : "bolt://mydomain.com:443/socket"...the websocket who is open is : "wss://mydomain.com:443/" and not : "wss://mydomain.com:443/socket"

Many thanks

**Comment by thebestnom** [comment]
Hmm... Thats sounds like neo4j driver problem, can you try to test using it directly?

**Comment by FloozeIT** [comment]
In effect the problem come from de "neo4j-driver" who take off the params after the base path. I'm gonna open an issue in their repository.

Many thanks @thebestnom
