### ISSUE TITLE
neovis can not show node relationships and node directions

### ISSUE THREAD

**Issue by minicloudsky** [neo4j-contrib/neovis.js#112]
my cypher likes below
```
CREATE p =(vic:Worker:Person{ name:'vic',title:"Developer" })-[:WORKS_AT]->(neo)<-[:WORKS_AT]-(michael:Worker:Person { name: 'Michael',title:"Manager" })
RETURN p,neo
```
in neo4j browser ,I can get the correct image,however in neovis, with the same cypher ,i can not get get the direction of the image
in neo4j browser
![image](https://user-images.githubusercontent.com/32286819/86221931-23f72f00-bbb8-11ea-92fc-37e3b54bdd9a.png)
in neovis 
![image](https://user-images.githubusercontent.com/32286819/86222167-746e8c80-bbb8-11ea-9761-31ba1def3b37.png)

**Comment by thebestnom** [comment]
You need to set in the config `arrows` to be `true`, check the readme or the d.ts for correct api

**Comment by minicloudsky** [comment]
finish problems
