### ISSUE TITLE
Please implement option to set image on nodes...

### ISSUE THREAD

**Issue by pvillads** [neo4j-contrib/neovis.js#115]
This is the single feature that is tempting me to scrap my current implementation and go to vis.js directly. The underlying vis.js implementation provides this out of the box when defining the node:

var DIR = 'img/soft-scraps-icons/';
nodes = [
        {id: 1,  shape: 'circularImage', image: DIR + '1.png'},
        {id: 2,  shape: 'circularImage', image: DIR + '2.png'},
...
]

In my opinion it would be natural to implement this in the configuration:

var config = {
...
                labels: {
                    'Class': {
                        caption: 'Name', // Name of property on Class node
                        image: 'myImage', // If the name is a simple string it is the name of a property
...
                        image: '../images/myimage.png' // In this case it is a bitmap in file system or web
                   }
                }
}

But there are plenty of other options that are just as good.

**Comment by thebestnom** [comment]
https://github.com/neo4j-contrib/neovis.js/pull/113 waiting for @johnymontana

**Comment by thebestnom** [comment]
Trivial in 2.x

**Comment by PeterPilley** [comment]
> 

Hi does this mean it has been enabled? if so where can I figure out how to implement. Does it have to be an image or could we render a fontawesome icon (font awesome chosen as example)?
