### ISSUE TITLE
Implement configuration option to set color for particular nodes.

### ISSUE THREAD

**Issue by pvillads** [neo4j-contrib/neovis.js#117]
I would like to be able to set the color for a individual nodes (and edges perhaps) in the configuration file. This would be by adding a literal that looks different from a name, which would designate a property on the node.

                    'MyNode': {
                        ... 
                       Color: 'MyField' // Get the color from the node
                    },
                    'AnotherNode: {
                        Color: '#ff444444', // a literal color 
                    },

or something to that effect.

**Comment by dukesun99** [comment]
I think community property does a similar thing here, although you cannot explicitly specify which color you want.

**Comment by liuyiqi1999** [comment]
Wondering if this can be done in 2.0

**Comment by Deepam-Rai** [comment]
How to do in 2.x?
```
labels: {
   Person: {
        color: 'red',
        shape: 'square'
   }
}
```
Above changes neither color nor shape for the nodes of type Person. Am I missing something?
