### ISSUE TITLE
Feature Request: Specify Node Color by its Property

### ISSUE THREAD

**Issue by mahesh557** [neo4j-contrib/neovis.js#12]
Hi,

While currently it is auto coloring based on community attribute,
it would be good if we can specify the color by a node property
i.e., all the nodes with property status='Active' should color green and others red.

uma

**Comment by DinisCruz** [comment]
yes I was just looking for that feature now (the ability to control the color of a node)

**Comment by pfoser** [comment]
Would be fantastic... hacking the community attribute to get different colors is not very elegant...

**Comment by suchetaswabhav** [comment]
looking for the same

**Comment by cooprose** [comment]
Is this project dead? So fundamental.

**Comment by DurkoMatko** [comment]
@cooprose looks like it's dead indeed. All the issues don't get any responses and this is really a fundamental feature missing.
