### ISSUE TITLE
dependency was not found

### ISSUE THREAD

**Issue by fightlikeagirl** [neo4j-contrib/neovis.js#121]
Hello,
When I try build my vue.js app , it gives me this dependency was not found: `vis-network/dit/vis-netork.min.css` in `./node_modules/neov.s.js/dist/neovis-without-dependencies.js` .To install it I run
`npm install --save vis/*network/dist/vis-network.min.css` and it gives me this error :
`ENOLOCAL, could not install from it as it does not contain a package.json file`
I need a solution, I really will be apprepiciated if you give me some solutions thanks a lot.

**Comment by thebestnom** [comment]
This not the right install, you should do 
`npm install vis-network`

**Comment by fightlikeagirl** [comment]
I uninstalled neovis.js and vis-network with `npm uninstall neovis.js ` then from the beginning  I run `npm install --save neovis.js`  then it gives me : 
>  This dependency was not found: * vis-network/dist/vis-network.min.css in ./node_modules/neovis.js/dist/neovis-without-dependencies.js

When I look at the vis-network.min.css file ,its directory is vis-network/dist/dist/vis-network.min.css. I think there is something wrong. What should I do ?

**Comment by fightlikeagirl** [comment]
I changed every line on ./node_modules/neovis.js/dist/neovis-without-dependencies.js, this ` vis-network/dist/vis-network.min.css` to this ` vis-network/dist/dist/vis-network.min.css`. And now it works. I think you should update your library based on this. Thanks.

**Comment by thebestnom** [comment]
Fixed in https://github.com/neo4j-contrib/neovis.js/pull/133
