### ISSUE TITLE
Adjusting Simulation Properties

### ISSUE THREAD

**Issue by RussDavid** [neo4j-contrib/neovis.js#122]
Hello

Is there anyway to edit the simulation forces of the graph? I would like to increase the repulsion force between the nodes so the graph is more spread out.

Currently the graph looks like this, it's rather difficult to read. 
![Graph Image](https://i.ibb.co/YbbNccG/neovis.png)
The pull force between nodes is too great/repulsion force too little so dragging nodes does little to change the display of the graph as the nodes pull back together to their original positions. 

Any suggestions about how I can improve graph readability would be greatly appreciated. Apologies if this is not the right place to ask these questions.

**Comment by dukesun99** [comment]
I think currently NeoVis does not support this level of graph customization. You can explore [vis.js-network](https://visjs.github.io/vis-network/docs/network/) more to find out the options to achieve this and PR is welcomed!

**Comment by RussDavid** [comment]
> 
> 
> I think currently NeoVis does not support this level of graph customization. You can explore [vis.js-network](https://visjs.github.io/vis-network/docs/network/) more to find out the options to achieve this and PR is welcomed!

Thank you for your response. It's unfortunate it's not possible to adjust these properties. 
I have however improved graph readability by reducing font sizes, node sizes, and line thickness which has improved the graph readability. 

Hopefully in futures releases this library will support more customization.

**Comment by thebestnom** [comment]
Can do on 2.x
