### ISSUE TITLE
Customize node color and relationship

### ISSUE THREAD

**Issue by LeThiTuyet** [neo4j-contrib/neovis.js#126]
I used <script src="https://rawgit.com/neo4j-contrib/neovis.js/master/dist/neovis.js"></script> in html file. 
I built and succeed project. I want to:
1.  Customize node color cuz of my nodes are not have "community" property.
2. Add event click to node and click to relationship
How I can do it? Thank all

**Comment by thebestnom** [comment]
for 1. currently there is no way to customize the color, or a lot of vis options (PR are welcome, see https://github.com/neo4j-contrib/neovis.js/issues/117)
for 2. https://github.com/neo4j-contrib/neovis.js/issues/16

**Comment by laughingchen123** [comment]
![58b7251a83a13dd14b6b04150820510](https://user-images.githubusercontent.com/44112298/104666171-32e59f00-570e-11eb-89f5-c450c2fa4577.png)
![a672d13f1e028bacea4b8dd1e0e57f8](https://user-images.githubusercontent.com/44112298/104666280-717b5980-570e-11eb-86ce-d739c8e831ba.png)
希望你能

> 我在html文件中使用了<script src =“ https://rawgit.com/neo4j-contrib/neovis.js/master/dist/neovis.js”> </ script>。
> 我建立并成功完成了项目。我想要：
> 
> 1. 自定义节点颜色cuz我的节点不具有“社区”属性。
> 2. 将事件单击添加到节点并单击关系，该
>    怎么办？谢谢大家

![58b7251a83a13dd14b6b04150820510](https://user-images.githubusercontent.com/44112298/104666297-81933900-570e-11eb-885a-084eea21153a.png)
![a672d13f1e028bacea4b8dd1e0e57f8](https://user-images.githubusercontent.com/44112298/104666302-85bf5680-570e-11eb-95ed-f0798c41434e.png)
我是在neovis.js文件，buildNodeVisObject方法里面加上了 const color = labelConfig && labelConfig['color']，然后再config里面配置你需要改变那个节点的颜色，比如我这里是修改“RiversNode”节点的颜色，就加上 "color": "#0094ff"这样，希望能帮到你

**Comment by thebestnom** [comment]
1. Please write in English here
2. Currently we are in progress of writing 2.0.0 which will allow to customize your node in any way vis.js allows

**Comment by laughingchen123** [comment]
All right. Thank you.

**Comment by xiaofan007** [comment]
> ![58b7251a83a13dd14b6b04150820510](https://user-images.githubusercontent.com/44112298/104666297-81933900-570e-11eb-885a-084eea21153a.png)
> ![a672d13f1e028bacea4b8dd1e0e57f8](https://user-images.githubusercontent.com/44112298/104666302-85bf5680-570e-11eb-95ed-f0798c41434e.png)
> In the buildNodevisObject method of the neovis.js file, I added const color = labelConfig && labelConfig['color'], and then in the config config I added the color of the node. For example, I changed the color of the node "riversNode", I added "color": "#0094ff", which I hope will help you

just 
`node.color = labelConfig && labelConfig['color']; `
try and enjoy it~

**Comment by thebestnom** [comment]
If you use 2.0.0 you're not going to need to patch the the library ☺️

**Comment by xiaofan007** [comment]
> If you use 2.0.0 you're not going to need to patch the the library ☺️

Wow, thank you~ ☺️

**Comment by HowieHwong** [comment]
> If you use 2.0.0 you're not going to need to patch the the library ☺️

sorry, I still can not customize the color of nodes, can you give an example? Thanks in advance!
