### ISSUE TITLE
Possible to use this in React Application?

### ISSUE THREAD

**Issue by erwin-d-austria** [neo4j-contrib/neovis.js#128]
I want to implement this neovis.js to react application. Is this possible?

**Comment by thebestnom** [comment]
Yes, of course, but it's not as aleasy to use there as a native react component

Just initialize it in `componentDidMount` and update in render/gotprops/any other update lifecycle

**Comment by erwin-d-austria** [comment]
Is there a tutorial to configure create-react-app on this project?

**Comment by thebestnom** [comment]
No that I know of, but following it should'nt be different from configuring vis but doing neovis init instead

**Comment by erwin-d-austria** [comment]
oks i got it thanks.
