### ISSUE TITLE
Is there an option to Zoom In and Zoom Out the relationship node?

### ISSUE THREAD

**Issue by erwin-d-austria** [neo4j-contrib/neovis.js#129]
I would like to know if there is a configuration to enable Zoom In and Zoon Out just like in the Neo4j Application.

**Comment by erwin-d-austria** [comment]
![image](https://user-images.githubusercontent.com/6743963/94811568-1efc8280-0428-11eb-9db1-cc0336f55f0e.png)
Possible to zoom in or zoom out this kind of output?

**Comment by thebestnom** [comment]
Im not sure what you mean, im pretty sure scrolling zooms in and out, programicly im not sure

**Comment by erwin-d-austria** [comment]
![image](https://user-images.githubusercontent.com/6743963/94813355-726fd000-042a-11eb-9832-a9675a196040.png)
there is an option in the neo4 desktop for the zoom in and zoom out.

**Comment by thebestnom** [comment]
There is no way currently with buttons, you can with scroll wheel (if im not wrong)

Vis network does support that if Im not wrong and PR are welcomed

**Comment by erwin-d-austria** [comment]
thanks i got it.

**Comment by mvolkmann** [comment]
I found a way to do this! Just hook these functions up to click handlers on buttons that you add.

```js
  function zoomIn() {
    const canvas = document.querySelector('.vis-network > canvas');
    if (!canvas) return; // It should always find the canvas.
    const box = canvas.getBoundingClientRect();
    canvas.dispatchEvent(
      new WheelEvent('wheel', {
        deltaY: -1,
        clientX: box.left + box.width / 2,
        clientY: box.top + box.height / 2
      })
    );
  }

  function zoomOut() {
    const canvas = document.querySelector('.vis-network > canvas');
    if (!canvas) return; // It should always find the canvas.
    const box = canvas.getBoundingClientRect();
    canvas.dispatchEvent(
      new WheelEvent('wheel', {
        deltaY: 1,
        clientX: box.left + box.width / 2,
        clientY: box.top + box.height / 2
      })
    );
  }
```

**Comment by shobhitexe** [comment]
Another way :

`viz['_network'].setOptions({interaction:{navigationButtons:true}})`
