### ISSUE TITLE
help in creating query for configs

### ISSUE THREAD

**Issue by mzmero** [neo4j-contrib/neovis.js#131]
iam trying to change the size of every node based on its releations count while using this query to change the size of node
 **" match (n:Tag) where id(n) = {id} match (n)-[p:Parent]->(t:Tag) return count(p) as c"** 
but the size of nodes wont change , i tried to run the query on neo4j by swapping the {id} with any id in the db and the query works fine  , any one can help? thx in advance.

**Comment by dukesun99** [comment]
Not sure about the problem, but did you try $id?

**Comment by mzmero** [comment]
> 
> 
> Not sure about the problem, but did you try $id?

yeah sorry it definitely worked , but it must be used at sizeCypher field not size field.
