### ISSUE TITLE
duplicated relationship are displayed when using apoc virtual relationship 

### ISSUE THREAD

**Issue by wedoso** [neo4j-contrib/neovis.js#132]
Apoc supports [creating virtual nodes and relationships](https://neo4j.com/labs/apoc/4.1/virtual/virtual-nodes-rels/) and visualization only. I create a similar graph followed by this [article](https://dzone.com/articles/neo4j-and-virtual-nodesrelationships). The visualization works well when I used `apoc.vRelationship` in the neo4j browser. The table view also includes only one entry. 

<img width="642" alt="image" src="https://user-images.githubusercontent.com/19911392/97337685-d45f0200-183d-11eb-8950-f3c6cffbb143.png">
<img width="998" alt="image" src="https://user-images.githubusercontent.com/19911392/97337752-e8a2ff00-183d-11eb-8a60-b466d2722b0f.png">

However, when I am using neovis to display, 
![image](https://user-images.githubusercontent.com/19911392/97337900-112af900-183e-11eb-99f2-28d35c810078.png)

Similarly, for other cypher queries with virtual relationship creation.

**Comment by wedoso** [comment]
I don't know if anyone here uses virtual nodes and relationships, but the ids of those virtual nodes and relationships are negative. Is that the reason cause this issue?

**Comment by thebestnom** [comment]
Ill test that later this week

**Comment by wedoso** [comment]
For more details, I am using neo4j 4.1.0. You may replicate the issue by following neo4j apoc official instruction [here](https://neo4j.com/labs/apoc/4.1/virtual/virtual-nodes-rels/). 
![image](https://user-images.githubusercontent.com/19911392/97641179-8560ca80-19ff-11eb-8626-c585582e1f6b.png)

First, create a simple dataset by 
`CREATE(a:Person)-[r:ACTED_IN]->(b:Movie)`
Second, create virtual nodes and relationships by 
`MATCH (a)-[r]->(b)
WITH head(labels(a)) AS l, head(labels(b)) AS l2, type(r) AS rel_type, count(*) as count
CALL apoc.create.vNode([l],{name:l}) yield node as a
CALL apoc.create.vNode([l2],{name:l2}) yield node as b
CALL apoc.create.vRelationship(a,rel_type,{count:count},b) yield rel
RETURN *;`

You are supposed to see two nodes and one relationship like the one shown in neo4j browser. 
 
![image](https://user-images.githubusercontent.com/19911392/97641325-dec8f980-19ff-11eb-80ba-ba50971a07c3.png)

But the latest version of neovis shows two sets of virtual nodes and relationships. 
![image](https://user-images.githubusercontent.com/19911392/97641353-ec7e7f00-19ff-11eb-8603-61fcbdfb7449.png)

**Comment by thebestnom** [comment]
Sorry, I didn't had time this week, Ill try to test that tomorrow

**Comment by thebestnom** [comment]
OK, thats wierd, Im testing this with 4.1.0 browser, and I seem to get 2 like the neovis.js 
![image](https://user-images.githubusercontent.com/21955247/97814208-2e265880-1c92-11eb-93cf-c76010f03a4a.png)

**Comment by thebestnom** [comment]
Ok, tested by copy your code, I saw that I didn't specify direction, now Im ggetting the same result

**Comment by thebestnom** [comment]
Ok, after testing seems that making sure that you have direction in the query is what matters, I get the correct thing with neovis after adding direction and got the same thing as you when removing that

**Comment by thebestnom** [comment]
(got duplicate when ran 
```cypher
MATCH (a)-[r]-(b)
WITH head(labels(a)) AS l, head(labels(b)) AS l2, type(r) AS rel_type, count(*) AS count
CALL apoc.create.vNode([l], {name: l}) YIELD node AS a
CALL apoc.create.vNode([l2], {name: l2}) YIELD node AS b
CALL apoc.create.vRelationship(b, rel_type, {count: count}, a) YIELD rel
RETURN *;
```
instead of
```cypher
MATCH (a)-[r]->(b)
WITH head(labels(a)) AS l, head(labels(b)) AS l2, type(r) AS rel_type, count(*) AS count
CALL apoc.create.vNode([l], {name: l}) YIELD node AS a
CALL apoc.create.vNode([l2], {name: l2}) YIELD node AS b
CALL apoc.create.vRelationship(b, rel_type, {count: count}, a) YIELD rel
RETURN *;
```

**Comment by thebestnom** [comment]
tested to see why, if you match without direction it is matched twice (one for each direction and getting called twice
also just to make sure, you only return what's in the last `WITH`, so the original `a` `b` and `r` aren't getting back (Im gessing that this is your intention but checking anyway)

**Comment by wedoso** [comment]
Sorry I didn't get what you mean. But from my end, if i tried to not specify the direction when doing match. In neo4j browser, I will have two pairs, while I will get four pairs with neovis. See the screenshot below. 

With neo4j browser:
![image](https://user-images.githubusercontent.com/19911392/97815835-ca763e00-1c45-11eb-8f25-a078f6ff6468.png)

With neovis:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/19911392/97815838-cea25b80-1c45-11eb-8427-dc67c37f0af8.png">

When I add "LIMIT 1" in the end. Now neo4j browser gives me 1 pair:
![image](https://user-images.githubusercontent.com/19911392/97815887-2345d680-1c46-11eb-95a4-2c1b42627a0e.png)

And the neovis gives me two pairs:
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/19911392/97815892-2fca2f00-1c46-11eb-8915-bf740a3692c3.png">

If like what you said add direction with match, and I add LIMIT 1 to the end, please find the result below:
![image](https://user-images.githubusercontent.com/19911392/97815906-56886580-1c46-11eb-8dc3-061576d0340b.png)

With neovis:
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/19911392/97815912-63a55480-1c46-11eb-9093-e0de5e3faf14.png">

**Comment by wedoso** [comment]
My point is not about the direction, it is about the rendering I guess. Even you specify the number of results to return by `LIMIT`, the virtual nodes or virtual relationships will be duplicated still.

**Comment by thebestnom** [comment]
I understand your point, it's just wierd because I can't reproduce (using 4.1.0)

**Comment by wedoso** [comment]
It is wierd. BTW, I am using neovis 1.5.0 and neo4j 4.1.0. 

I am not getting duplicated relationships or nodes with the actually existed ones. And once I use apoc's virtual nodes and relationships, I get this issue. So I don't think I have anything set up incorrectly. :(

**Comment by thebestnom** [comment]
this is my initial query
![image](https://user-images.githubusercontent.com/21955247/97816384-87e05000-1c9d-11eb-8217-b15c6fa3ad33.png)
and this is my output
![image](https://user-images.githubusercontent.com/21955247/97816393-93337b80-1c9d-11eb-9374-68b799aba2ab.png)
Im working on master branch, but I don't think that matters...

**Comment by wedoso** [comment]
Thanks for posting this. I tried to set the cypher as inital_cypher, and it works well. But when i click submit, I call 

      this.viz.renderWithCypher(this.cypher);
      this.viz.reload();

even i didn't change anything, now it gives me two pairs.

**Comment by wedoso** [comment]
For reference, here is how I implement it

    import {Component, OnInit} from '@angular/core';
    import NeoVis from 'neovis.js/dist/neovis.js';
    import {HttpService} from '../service/http.service';
    import {xxxService} from '../service/xxx.service';

    @Component({
      selector: 'app-data-visualization',
      templateUrl: './data-visualization.component.html',
      styleUrls: ['./data-visualization.component.scss']
    })
    export class DataVisualizationComponent implements OnInit {

      cypher = `MATCH (a)-[r]->(b)
      WITH head(labels(a)) AS l, head(labels(b)) AS l2, type(r) AS rel_type, count(*) AS count
      CALL apoc.create.vNode([l], {name: l}) YIELD node AS a
      CALL apoc.create.vNode([l2], {name: l2}) YIELD node AS b
      CALL apoc.create.vRelationship(b, rel_type, {count: count}, a) YIELD rel
      RETURN * ;`;
      url: string;
      error;

      constructor(
        private http: HttpService,
        private xxxService: xxxService
      ) { }

      config = {
        container_id: 'viz',
        server_url: '',
        server_database: '',
        server_user: '',
        server_password: '',
        initial_cypher: this.cypher,
        arrows: true,
      };
    
      viz: NeoVis;
    
      ngOnInit() {
        this.xxxService.getByName(localStorage.getItem('workspace'))
          .subscribe(
            data => {
              this.url = data[0].url.split('db')[0];
    
              this.http.getBolt(this.url).subscribe(
                bolt => {
                  // @ts-ignore
                  this.config.server_url = bolt.bolt_routing;
                  this.config.server_user = 'neo4j';
                  this.config.server_password = 'test';
                  this.config.server_database = data[0].url.split('db')[1].split('/')[1];
                  this.viz = new NeoVis(this.config);
                  this.viz.render();
                },
                error => this.error = error
              );
            },
            error => this.error = error
          );
      }
    
      submitQuery() {
        if (true) {
          this.viz.renderWithCypher(this.cypher);
          this.viz.reload();
        } else {
          alert('Please use \"LIMIT\" keyword to query the graph.');
        }
    
      }
    
      stabilize() {
        this.viz.stabilize();
      }
    
    }

**Comment by thebestnom** [comment]
I don't think `reload` is neccesry here as it does exactly what renderWithCypher does, I can easily think of a way that you are making a race condition 😅

**Comment by thebestnom** [comment]
```js

	/**
	 * Execute an arbitrary Cypher query and re-render the visualization
	 * @param query
	 */
	renderWithCypher(query) {
		// this._config.initial_cypher = query;
		this.clearNetwork();
		this._query = query;
		this.render();
	}

	/**
	 * Execute an arbitrary Cypher query and update the current visualization, retaning current nodes
	 * This function will not change the original query given by renderWithCypher or the inital cypher.
	 * @param query 
	 */
	updateWithCypher(query) {
		this.render(query);
	}
```

**Comment by wedoso** [comment]
Ah... I got it. Thanks for spending time on this. You are helping me out.
