### ISSUE TITLE
node label background color

### ISSUE THREAD

**Issue by mvolkmann** [neo4j-contrib/neovis.js#140]
Is there are way to set the background color used for node labels or make it transparent so it matches what I assign to the background-color of the div that holds the diagram? The attached screenshot shows the issue. The div background is linen, but the background of the labels is white.
<img width="581" alt="Screen Shot 2020-11-12 at 11 02 34 AM" src="https://user-images.githubusercontent.com/79312/98971383-b1d41680-24d6-11eb-8ee9-77dae63b116a.png">

**Comment by thebestnom** [comment]
I don't think that currently this is supported in neovis
Ill want to make neovis merge configuraion with vis instead of using it's own, and after that this should be fully supported
