### ISSUE TITLE
meaning of "live data"

### ISSUE THREAD

**Issue by mvolkmann** [neo4j-contrib/neovis.js#141]
The first feature listed in the README is "Connect to Neo4j instance to get live data".
What does "live data" mean in this context?
Does it mean that the diagram will automatically update when the database is modified?
If so, is there something we need to do in our code to request that to happen?
It doesn't seem to happen by default.

**Comment by thebestnom** [comment]
It was written before I was here 😅
I understand that this is misleading, neovis only get data on render, and Im not sure neo4j have listening capabilities on it's driver

If there is I would gladly add live listening as a feature

 sorry for the confusion

**Comment by thebestnom** [comment]
After digging in neo4j for a bit all I found for live data is neo4j streaming, and I couldn't find integration for that in the driver...
https://neo4j.com/labs/kafka/4.0/
