### ISSUE TITLE
Merge Vis Node and Relation Configuration

### ISSUE THREAD

**Issue by thebestnom** [neo4j-contrib/neovis.js#144]

**Comment by dukesun99** [comment]
May I know how do you want to distinguish the `property name` and `Cypher query` way of inputting a config field? I feel it would be good to have both ways for all configurable fields (and maybe function way also).

**Comment by thebestnom** [comment]
Im thinking about that already, thinking what will be the best way to do that

Currently I'm thinking about splitting the config to cypher queries and static properties, but I'm sure there is a better and cleaner way that I'm not thinking about

**Comment by dukesun99** [comment]
@thebestnom So basically we need to support 4 types of properties: static (number, plain string, boolean and etc which will be directly passed to vis.js), property name, Cypher query, and function? Do you mean splitting by providing something like 
`
Node: {
    Cyphers: {
         size: "match ......"
    },
    consts: {
             caption: "a node"
    }
}
`

**Comment by thebestnom** [comment]
Yes, this was my first thought about that

Also great idea about the function property, I haven't thought about that!

Im not sure but what do you mean for property name

**Comment by dukesun99** [comment]
For example for size, static is like `3`, property name is like `weight` (Node have a weight property in Neo4j db).

**Comment by thebestnom** [comment]
Oh yeah, that sound reasonable

Currently the only other way I'm thinking right now is instead of objects of type do it the other way around and do type in object for example
```javascript
{
 //Other things
  prop: {value: 4, type: typeEnum.STATIC }
}
```
But im still leaning towards the first option

**Comment by dukesun99** [comment]
Yeah, I prefer the first option as well.

**Comment by dukesun99** [comment]
@thebestnom Do you need any help on the implementation or something else? I have some time to help recently.

**Comment by thebestnom** [comment]
@dukesun99 I would really appreciate it, I currently don't have the time for anything 😓

**Comment by dukesun99** [comment]
@thebestnom okay I will attempt to start implementing this, perhaps write some helper functions first.

**Comment by dukesun99** [comment]
@thebestnom May I know how can we know the type of config field to convert to if we do not explicitly specify them?

**Comment by thebestnom** [comment]
What do you mean? Can you give an example

**Comment by dukesun99** [comment]
@thebestnom Visjs config for size requires a Number, for label requires a String. Say if the user wants to use a Neo4j Int type property as the label, we need to convert it to String before sending it to Visjs, am I correct?

**Comment by thebestnom** [comment]
Hmm..  I don't think that it will actually need to be converted, Im pretty sure it will automatically be converted to string because javascript

And for anything else I'm pretty sure the user will just return the right thing from the cypher

**Comment by dukesun99** [comment]
Ok I see. Then in this case we only need to properly convert Neo4j numbers to JS numbers.

**Comment by dukesun99** [comment]
I found in the Neo4j JS driver doc that we can actually disable the lossless integers. What do you think? Do we just simply disable it to get rid of this integer issue completely.

**Comment by thebestnom** [comment]
I think that newer browser support bigint and I think that what the driver is going to do, I think that is good enough for us

**Comment by thebestnom** [comment]
Actually, Im remembered that driver version is bound to neo4j version, and Im not sure if bigint work for all driver version, do you mind checking which driver version started supporting that?

**Comment by thebestnom** [comment]
I have some time today and maybe tomorrow, do you need any help, or I go and do somthing else in the meantime?

**Comment by dukesun99** [comment]
I implemented a few helper functions. And refactored current code with these functions and pushed to my forked repo. Maybe I will try to complete this feature today and could you help to test and review it? > I have some time today and maybe tomorrow, do you need any help, or I go and do somthing else in the meantime?

**Comment by thebestnom** [comment]
Of course, but today I'll probably won't have time, Ill look at your fork probably tomorrow

**Comment by dukesun99** [comment]
Ok I'll make a PR by today with whatever I have currently.
