### ISSUE TITLE
Can we pass input variable to intial_cypher in config statement in neoviz script?  

### ISSUE THREAD

**Issue by masm900** [neo4j-contrib/neovis.js#145]
I am running this script, but not working.. $name is not recognizable although value is coming to console.log.  
initial_cypher: "MATCH (actor:Person {name: $name})-[:ACTED_IN]->(actorMovies) Match (actor)-[r]->() RETURN actor,actorMovies,r"

Any tip?

**Comment by dukesun99** [comment]
How do you pass the name in?

**Comment by masm900** [comment]
I got this work by passing string variable.  thank you for your reply
