### ISSUE TITLE
Relashionships and nodes color

### ISSUE THREAD

**Issue by JJn9** [neo4j-contrib/neovis.js#153]
Hello, I'm trying to apply some colors to my neovis graph but it seems like nothing happens when I follow what suggested by most users, here is my config code :

```
{
        container_id: "viz",
        server_url: "bolt://xxx:31270",
        server_user: "neo4j",
        server_password: "xxx",
        labels: {
          Device: {
            caption: "name",
            size: "pagerank",
            community: "community",
          },
        },
        relationships: {
          HAS_LINK: {
            thickness: 6,
            caption: true,
            color: "green",
          },
        },
        initial_cypher:
          "MATCH (n)<-[j:HAS_LINK]-(i)-[k:HAS_LINK]->(m) RETURN *;",
        arrows: true,
        hierarchical_layout: true,
        hierarchical_sort_method: "directed",
      };
```

As you can see, I added "color" attribute to my "HAS_LINK" relashionship but nothing happens it still renders the default blue color : 

![image](https://user-images.githubusercontent.com/33116767/105354635-1d321700-5bf1-11eb-8538-4cfc5f49e661.png)

Anyone can help me please ? 
Thanks in advance.

**Comment by thebestnom** [comment]
duplicate https://github.com/neo4j-contrib/neovis.js/issues/126

**Comment by thebestnom** [comment]
As I wrote there, were currently implementing this feature (and more 😄) it's ready but I want to add some small changes before publishing 2.0.0

**Comment by Rezu** [comment]
Thanks @thebestnom, can you please share the link where 2.0.0 will be published?

**Comment by Rezu** [comment]
ah I see it's already closed
