### ISSUE TITLE
Problems with Captions - only "_node" is shown

### ISSUE THREAD

**Issue by Kuhlig** [neo4j-contrib/neovis.js#154]
HI 

i just started using neovis. My example is simple and I get data - But with 2 labels I have "captions" problems . after draw the caption is "_node"

Her is my code - the rest is the simple example from the github repo ... 

```
.... 
            var config = {
                container_id: "viz",
                server_url: "bolt://edums.bpmspace.net:7687",
                server_user: "neo4j",
                server_password: "PASSWD",
                labels: {
					"topic": {
                        "caption": "name"
                    } ,
                    "course": {
                        "caption": "short_name"
                    } ,
                    "person": {
                        "caption": "name"
                    }
                },
                relationships: {
                    "allowed_to_teach": {
                        "caption": false
                    }
                },
                initial_cypher: "MATCH (per:person)-[r1:allowed_to_teach]->(cou:course)<-[r2:hasCourse]-(to:topic) RETURN * "
            };
...
```
 

 And here is a screenshot?

![grafik](https://user-images.githubusercontent.com/16413104/106424623-ca632580-6462-11eb-8f3f-1c4990ddb0ac.png)

what do I do wrong? The Names of the nodes with label person are ok. 
Thanks for help?
rob

PS 
I use

... src="https://cdn.neo4jlabs.com/neovis.js/v1.6.0/neovis.js"> ....

also tried it with 1.5.0 and 1.4.0 .. same error

there was an encoding error when i copied the example form the github. but with <meta charset="utf-8"/> the error was solved ....

**Comment by thebestnom** [comment]
Thats weird... Make sure that the labels are correct (case sensitive) other than that if that doesn't work Ill try to debug that later today

**Comment by Kuhlig** [comment]
I also thought my names are too long so i created SHort_name for the courses but still same error
BUt I think i have the REASON - E.G Person has MORE than one lable also the LAbel "_node" - see screenhsot

![grafik](https://user-images.githubusercontent.com/16413104/106460478-b4ba2400-6493-11eb-9ff4-41a4a8cc9a29.png)

![grafik](https://user-images.githubusercontent.com/16413104/106460160-2e054700-6493-11eb-96b0-d3fafdfbe7a8.png)

topic also has more then one label but somehow in different ordere - 

![grafik](https://user-images.githubusercontent.com/16413104/106460362-88060c80-6493-11eb-80b8-6b85dd6b1bd6.png)

**Comment by thebestnom** [comment]
Oh... So currently multi label are not supported (will take the first label) I am planing to add it on 2.0.0 and it will take a bit of time...

**Comment by Kuhlig** [comment]
when i do 
MATCH (n:course) REMOVE n:_node;
MATCH (n:course) REMOVE n:_edumsdemo;
 
 it sis working so it has soemthing todo with the 2nd or 3rd label!
still course not Course.name is shwon

**Comment by Kuhlig** [comment]
I sther a chance to make a label the FIRST ONE?

**Comment by thebestnom** [comment]
> it sis working so it has soemthing todo with the 2nd or 3rd label!

Yeah, that's what I said
But I have no idea how to set a specific label first... Sorry

**Comment by Kuhlig** [comment]
Joop - did not see your answer sorry - was writing on my testresults :-)
