### ISSUE TITLE
Uncaught TypeError: NeoVis is not a constructor while deploying in Heroku

### ISSUE THREAD

**Issue by ArturoGuerrero** [neo4j-contrib/neovis.js#159]
Hello,
I upload an app with a neo4j neovis.js script, but the script crashes due to an "Uncaught TypeError: NeoVis is not a constructor".
The app is working fine on a localhost, but not on an Heroku server.

**Comment by thebestnom** [comment]
Do you mind giving me more info? Are you using cdn? Npm package? Any code snippets?

**Comment by ArturoGuerrero** [comment]
Hello @thebestnom 
Thank you for your help.

Yes, I´m using cdn
The error message appears in this code line

` var viz = new NeoVis(config);`
 and this is the error:

Uncaught TypeError: NeoVis is not a constructor
    draw .../index:123
    onload .../index:1
index:123:17
    draw .../index:123
    onload .../index:1

And my code is like the example.
`<body onload="draw()">

  <div id="viz"></div>
  <script type="text/javascript">
    var viz;

    function draw() {
      var config = {
        container_id: "viz",
        server_url: ...,
        server_user: ...,
        server_password: ...,
        labels: {
          "Person": {
            caption: "name",
            font: {
              "size": 14,
            },
          },
          "Book": {
            caption: "present_shelfmark",
            font: {
              "size": 14,
            },
          },
          "Location": {
            caption: "city",
            font: {
              "size": 14,
            },
          },
        },
        relationships: {
          "AUTHOR": {
            "thickness": "weight",
            "font": {
              "size": 12
            }
          },
          "REVIEWER": {
            "thickness": "weight",
            "font": {
              "size": 12
            }
          }
        },

        initial_cypher: "MATCH (n)-[r]->(m) RETURN n,r,m",
       
      };

      var viz = new NeoVis.default(config);
      viz.render();
    }
  </script>`

**Comment by ArturoGuerrero** [comment]
Hello @thebestnom
Thank you for your help.

Yes, I´m using cdn
The error message appears in this code line

var viz = new NeoVis(config);
and this is the error:

Uncaught TypeError: NeoVis is not a constructor
draw .../index:123
onload .../index:1
index:123:17
draw .../index:123
onload .../index:1

And my code is like the example.
`
<script type="text/javascript"> var viz;

function draw() {
  var config = {
    container_id: "viz",
    server_url: ...,
    server_user: ...,
    server_password: ...,
    labels: {
      "Person": {
        caption: "name",
        font: {
          "size": 14,
        },
      },
      "Book": {
        caption: "present_shelfmark",
        font: {
          "size": 14,
        },
      },
      "Location": {
        caption: "city",
        font: {
          "size": 14,
        },
      },
    },
    relationships: {
      "AUTHOR": {
        "thickness": "weight",
        "font": {
          "size": 12
        }
      },
      "REVIEWER": {
        "thickness": "weight",
        "font": {
          "size": 12
        }
      }
    },

    initial_cypher: "MATCH (n)-[r]->(m) RETURN n,r,m",
   
  };

  var viz = new NeoVis.default(config);
  viz.render();
}

</script>`

**Comment by ArturoGuerrero** [comment]
Hello @thebestnom
Thank you for your help.

Yes, I´m using cdn
The error message appears in this code line

var viz = new NeoVis(config);
and this is the error:

Uncaught TypeError: NeoVis is not a constructor
draw .../index:123
onload .../index:1
index:123:17
draw .../index:123
onload .../index:1

And my code is like the example.
`
<script type="text/javascript"> var viz;

function draw() {
  var config = {
    container_id: "viz",
    server_url: ...,
    server_user: ...,
    server_password: ...,
    labels: {
      "Person": {
        caption: "name",
        font: {
          "size": 14,
        },
      },
      "Book": {
        caption: "present_shelfmark",
        font: {
          "size": 14,
        },
      },
      "Location": {
        caption: "city",
        font: {
          "size": 14,
        },
      },
    },
    relationships: {
      "AUTHOR": {
        "thickness": "weight",
        "font": {
          "size": 12
        }
      },
      "REVIEWER": {
        "thickness": "weight",
        "font": {
          "size": 12
        }
      }
    },

    initial_cypher: "MATCH (n)-[r]->(m) RETURN n,r,m",
   
  };

  var viz = new NeoVis.default(config);
  viz.render();
}

</script>
`

**Comment by ArturoGuerrero** [comment]
Hello @thebestnom
Thank you for your help.

Yes, I´m using cdn
The error message appears in this code line

`var viz = new NeoVis(config);`
and this is the error:

Uncaught TypeError: NeoVis is not a constructor
draw .../index:123
onload .../index:1
index:123:17
draw .../index:123
onload .../index:1

And my code is like the example.

`<script type="text/javascript"> var viz;

function draw() {
  var config = {
    container_id: "viz",
    server_url: ...,
    server_user: ...,
    server_password: ...,
    labels: {
      "Person": {
        caption: "name",
        font: {
          "size": 14,
        },
      },
      "Book": {
        caption: "present_shelfmark",
        font: {
          "size": 14,
        },
      },
      "Location": {
        caption: "city",
        font: {
          "size": 14,
        },
      },
    },
    relationships: {
      "AUTHOR": {
        "thickness": "weight",
        "font": {
          "size": 12
        }
      },
      "REVIEWER": {
        "thickness": "weight",
        "font": {
          "size": 12
        }
      }
    },

    initial_cypher: "MATCH (n)-[r]->(m) RETURN n,r,m",
   
  };

  var viz = new NeoVis.default(config);
  viz.render();
}

</script>`

**Comment by thebestnom** [comment]
Where the script tag to the cdn placed? It's client side so it's weird to not work on production

**Comment by thebestnom** [comment]
Btw it's `new NeoVis.default(config)` and not `new NeoVis(config)` on cdn

**Comment by ArturoGuerrero** [comment]
> 
> 
> Where the script tag to the cdn placed? It's client side so it's weird to not work on production

Hello I´ve put the cdn in a separate footer.ejs.

**Comment by thebestnom** [comment]
Make sure it loads before the script executes

**Comment by ArturoGuerrero** [comment]
I tried both `new NeoVis.default(config)` and not `new NeoVis(config)`, but none works.

**Comment by thebestnom** [comment]
Can you look at the network panel in chrome and make sure it executes the cdn before the draw?

**Comment by ArturoGuerrero** [comment]
@thebestnom 
Thank you for your help and patience!
Now I´ve change the position of the cdn and I´ve put it on the header and I change it to `new NeoVis.default(config)`
Now what I become is a different error  "DOMException: The operation is insecure." And it sends me to to the cdn neovis.js:43:18.
Thank you

**Comment by thebestnom** [comment]
Hmm... Never saw that problem, maybe you are connecting to insecure neo4j instance (without ssl) from https site?

**Comment by ArturoGuerrero** [comment]
It works, when I put only http and not https when calling the heroku site, but don´t you think this isn´t a good idea to solve the problem?

**Comment by thebestnom** [comment]
It's not an option, it's a security measures from the browser, you can fix that by adding ssl to your neo4j server and connecting with `encrypted: "ENCRYPTION_ON"` in the config

**Comment by thebestnom** [comment]
No problem, good luck! 😄
