### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by ghost** [neo4j-contrib/neovis.js#16]
When a node is clicked (aka selected), it would be great for an application to be able to (a) interact with that node's data and (b) fire a script.

For example, [here](https://imgur.com/T6jtpIo) I have a jquery panel that slides in the from the right to show the details associated with a node. An ajax neomodel query is made using the node's uid. Right now I just have this hooked up to a custom link that has an attribute `node-uid="147"` for a demo, but I'd like to be able to click on a node in order to access it's ID and fire a script.

I suppose better popover functionality would help, but I'd really like the freedom to interact with the data just like I've made a db query. When you click on a node in this [vivagraphjs example](http://www.yasiv.com/amazon#/Search?q=graph%20drawing&category=Books&lang=US) it pulls up a whole new set of DOM data.

**Comment by laynetrain** [comment]
Vis.js handles this through a click event as seen here: https://imgur.com/kkVSrHE

Looking into the neovis.js source code:
- Line 35,227; The only occurrences of "hover" and "click" happen within the minified vis.js and hammerjs. 
- Line 36350; Within `buildNodeVisObject(n) {` the id is set as `node['id'] = n.identity.toInt();`
- Line 36443; Hover already has a type of event where it returns the "label/ caption" when the edge is hovered over in the canvas
- Line 155; It looks like click would need to be added to (line 155) `vis.js: {interaction:{**click:true**, hover:true}}` too.


Perhaps a `.click()` callback to obtain the clicked node's ID could be added to `render(callback)` like so `n.click( var nodeId = $(this).attr('node-id'); )`?

**Comment by eayan** [comment]
Hi, is it possible to add "expand" function to the script?
best...

Erdal Ayan

**Comment by suchetaswabhav** [comment]
@HashRocketSyntax  and others ,

where to put this code and how to input it Neovis.js page code- 

       {
        “pointer”:
        {
              “DOM”: {
        
                   “x”: 337,
                   “y”:292
        },
        
              “canvas” : {
        
                  “x” : 31.23590,
                  “y” : 130.31659
        
        }
        },
        
        “event” : “[original event]”,
        “nodes”:  [
          5
        ],
        
        “edges” : [
                    “72cad4c7-d945-4810-a968-6537940e9f9f”
        ],
        
        “items”” [ ]
        
        }

**Comment by seansms** [comment]
Yes, I want this capability too, not just for nodes, but for edges as well.

**Comment by mhoangvslev** [comment]
Should be able to do with `registerOnEvent()`, like this

```javascript
this._renderer.registerOnEvent('selectNode', (properties) => {
    const nodes = properties.nodes;
    // Do something
});
```

**Comment by borosuman** [comment]
@HashRocketSyntax  Hi. Have you found any solution for this?

**Comment by HashRocketSyntax** [comment]
@borosuman i just switched over to vis.js entirely

**Comment by borosuman** [comment]
@HashRocketSyntax Thank you for your quick response. Have you implemented the click event handling successfully using vis.js?

**Comment by HashRocketSyntax** [comment]
yes

**Comment by tquiroga** [comment]
@HashRocketSyntax How did you implement click event? Could you share that?

**Comment by lmeow** [comment]
> 
> 
> Should be able to do with `registerOnEvent()`, like this
> 
> ```js
> this._renderer.registerOnEvent('selectNode', (properties) => {
>     const nodes = properties.nodes;
>     // Do something
> });
> ```

Hi! How and where would I need to implement registerOnEvent() in order for the click event to work?

**Comment by thebestnom** [comment]
I actually implemented it in the config in my private repo, so I could give different labels different handler

**Comment by pvillads** [comment]
> I actually implemented it in the config in my private repo, so I could give different labels different handler.
...

Can you possibly show how? I can't find the place to intercept the creation of the window with the node properties. It is driving me nuts.

**Comment by thebestnom** [comment]
Well, you first need to save the original properties somewhere on the _nodes and _edges in _addNode and _addEdges.
And than (and this is the gross part) in the end of onCompleted, you add to the _network a full click/double click/whatever event listener, see which nodes and edges where clicked there and than fire the right event inside the network event by checking the nodes and edges groups

**Comment by maxsombra** [comment]
> Well, you first need to save the original properties somewhere on the _nodes and _edges when you send them to _addNode and _addEdges.
> And than (and this is the gross part) in the end of onCompleted, you add to the _network a full click/double click/whatever event listener, see which nodes and edges where clicked there and than fire the right event inside the network event by checking the nodes and edges groups

sorry but you can show some code

**Comment by thebestnom** [comment]
No... Sorry, air gapped... I can try to implement it again after work

**Comment by thebestnom** [comment]
@maxsombra made a pretty quick and dirty implementation on my fork on feature/events branch, you can check the last commit to check what I did
https://github.com/thebestnom/neovis.js/tree/feature/events

**Comment by abansal21** [comment]
> > Well, you first need to save the original properties somewhere on the _nodes and _edges when you send them to _addNode and _addEdges.
> > And than (and this is the gross part) in the end of onCompleted, you add to the _network a full click/double click/whatever event listener, see which nodes and edges where clicked there and than fire the right event inside the network event by checking the nodes and edges groups
> 
> sorry but you can show some code
Hi, Here's how I did it

registerClickEvent(viz: NeoVis): void{
    viz.registerOnEvent("completed", (e)=>{
      viz["_network"].on("click", (event)=>{
        ... do something with event ..
        });
      });
    });
  }

**Comment by thebestnom** [comment]
@abansal21 the problem with that is that neovis does not save the original properties of the label, and because of that patch is required... So while I was at it I also added a way to add event per label or relationship type from the config

**Comment by abansal21** [comment]
> @abansal21 the problem with that is that neovis does not save the original properties of the label, and because of that patch is required... So while I was at it I also added a way to add event per label or relationship type from the config

Yes, I agree. If we need raw data we need to to change the code. In my case I parsed the html code :p 
I also saw your commit 
> thebestnom@b67066b
It's on right track.
in this you can just generate click event like completion event.

**Comment by thebestnom** [comment]
@abansal21 I did it on the config on purpose, it gives me easy control over which type will trigger it, it easier to do defaults in the future like that (also I hate the current event system, I am much more comfortable with config based events, but that is my opinion), that how I implemented it in my closed source code and it was really useful, I also implemented double click that way...

It's not hard to implement it in the current event system but I dont really want to do it, if someone wants to pull it of, good luck!

Btw, parsing html to implement it is the exact reason why I love js, its so broken its wonderful

**Comment by lx2pwnd** [comment]
@thebestnom I was searching for a way to handle the click event and reading in here I was able to find it. Thank you very much. But since I used the version on branch @b67066b, the labels under the nodes are not showing up anymore. Why ? thanks

**Comment by thebestnom** [comment]
I'm looking into it, and I saw that I already fixed that in a later version, I'm rebasing it now...

also I see that click event currntly is implemented already implemented very closly to how I did it, so you can try to use master

**Comment by thebestnom** [comment]
@lx2pwnd rebased if you'll still want to use my way

**Comment by thebestnom** [comment]
@lx2pwnd di it work for you?

**Comment by thebestnom** [comment]
@lx2pwnd did it work for you?

**Comment by lx2pwnd** [comment]
I have insert the 1.4.0 in my web app and,in the config, I left the snippet below to handle the click

`viz.registerOnEvent("completed", (e)=>{
        viz["_network"].on("click", (event)=>{
            // event.nodes[0] or event.edges[0] have id of node or edge  clicked
            // you can get data of node data as viz["_nodes"][event.nodes[0]], similarly do for edges
            console.log(event.nodes[0]);
        });
    });`

It seems to work fine. Is there a way to hide the label under each nodes ?

**Comment by spencerwuwu** [comment]
> I have insert the 1.4.0 in my web app and,in the config, I left the snippet below to handle the click
> 
> ```
> viz.registerOnEvent("completed", (e)=>{ 
>         viz["_network"].on("click", (event)=>{ 
>             console.log(event.nodes[0]);
>         });
>     });
> ```
> 
> It seems to work fine.

Works for me too. Thanks

**Comment by lx2pwnd** [comment]
> > I have insert the 1.4.0 in my web app and,in the config, I left the snippet below to handle the click
> > ```
> > viz.registerOnEvent("completed", (e)=>{ 
> >         viz["_network"].on("click", (event)=>{ 
> >             console.log(event.nodes[0]);
> >         });
> >     });
> > ```
> > 
> > 
> > It seems to work fine.
> 
> Works for me too. Thanks

Do u know a way to handle the color of the nodes ? Thanks

**Comment by denna10** [comment]
Sorry for resurrecting this, but could I ask for simple instructions on what I should do to be able to catch a click event on a node or edge? I'm using Neovis to visualize my data in an Angular app. I'm new to Angular, TypeScript, Neo4j, and thus Neovis, so I might be somewhat in over my head, but I was hoping to use the click event to show closer information about the node/edge to the user. I can see that people have had success with the code below, but I'm not sure about where I should put this code to make it work (it might simply be because I'm unused to TypeScript). I see in the code that there are ClickNode and ClickEdge events, but I can't make much sense of it. Any guidance is very much appreciated!

viz.registerOnEvent("completed", (e)=>{ 
        viz["_network"].on("click", (event)=>{ 
            console.log(event.nodes[0]);
        });
    });

**Comment by pvillads** [comment]
I started using neovis.js but had to give it up, for several reasons. One is that you will not see timely reactions from the maintainers. You will very quickly get in trouble for reasons like the one  you are mentioning, but also from the lack of ability to impact what the nodes look like. I also happen not to like having to provide database credentials to the rendering layer, but that is just me.

I went ahead and changed to using vis.js instead, and I am so happy that I did. If you want to see what I did you can take a look at Dynamics365FO-AppChecker/tools/Graph Explorer at master * microsoft/Dynamics365FO-AppChecker (github.com)<https://github.com/microsoft/Dynamics365FO-AppChecker/tree/master/tools/Graph%20Explorer>.

I hope this helps.

Best Regards

Peter Villadsen

**Comment by lx2pwnd** [comment]
> Sorry for resurrecting this, but could I ask for simple instructions on what I should do to be able to catch a click event on a node or edge? I'm using Neovis to visualize my data in an Angular app. I'm new to Angular, TypeScript, Neo4j, and thus Neovis, so I might be somewhat in over my head, but I was hoping to use the click event to show closer information about the node/edge to the user. I can see that people have had success with the code below, but I'm not sure about where I should put this code to make it work (it might simply be because I'm unused to TypeScript). I see in the code that there are ClickNode and ClickEdge events, but I can't make much sense of it. Any guidance is very much appreciated!
> 
> viz.registerOnEvent("completed", (e)=>{
> viz["_network"].on("click", (event)=>{
> console.log(event.nodes[0]);
> });
> });

To enable the click event, you must write something like this

`
function drawGraph(cmd, direction, dimension)
{
    $('.content').html('<div id="viz" style="height: 100%; width: 100%"></div>')

    let config = {
        container_id: "viz",
        server_url: "bolt://localhost:7687",
        server_user: "neo4j",
        server_password: "********",
        arrows: direction,
        labels: {
            'Friend': {
                'caption': 'name',
                'size': dimension,
            },
            'RemovedFriend': {
                'caption': 'name',
                'size': dimension,
            }
        },
        relationships: {
            "FRIEND": {
                "thickness": "count",
                "caption": false
        },
        initial_cypher: "MATCH ... WHERE ... RETURN ,,,,", 
    };

    viz = new NeoVis.default(config);
    viz.render();

    viz.registerOnEvent("completed", (e)=>{
        viz["_network"].on("click", (event)=>{
                           ....Put here what happen when click on a node....
        });
    });

}
`
generally you must insert the event click after the render of the graph

**Comment by denna10** [comment]
> > Sorry for resurrecting this, but could I ask for simple instructions on what I should do to be able to catch a click event on a node or edge? I'm using Neovis to visualize my data in an Angular app. I'm new to Angular, TypeScript, Neo4j, and thus Neovis, so I might be somewhat in over my head, but I was hoping to use the click event to show closer information about the node/edge to the user. I can see that people have had success with the code below, but I'm not sure about where I should put this code to make it work (it might simply be because I'm unused to TypeScript). I see in the code that there are ClickNode and ClickEdge events, but I can't make much sense of it. Any guidance is very much appreciated!
> > viz.registerOnEvent("completed", (e)=>{
> > viz["_network"].on("click", (event)=>{
> > console.log(event.nodes[0]);
> > });
> > });
> 
> To enable the click event, you must write something like this
> 
> `function drawGraph(cmd, direction, dimension)
> {
> $(.content).html(
> 
> )
> ```
> let config = {
>     container_id: "viz",
>     server_url: "bolt://localhost:7687",
>     server_user: "neo4j",
>     server_password: "********",
>     arrows: direction,
>     labels: {
>         'Friend': {
>             'caption': 'name',
>             'size': dimension,
>         },
>         'RemovedFriend': {
>             'caption': 'name',
>             'size': dimension,
>         }
>     },
>     relationships: {
>         "FRIEND": {
>             "thickness": "count",
>             "caption": false
>         }
>     },
>     initial_cypher: cmd,
> };
> 
> viz = new NeoVis.default(config);
> viz.render();
> 
> viz.registerOnEvent("completed", (e)=>{
>     viz["_network"].on("click", (event)=>{
>         ...put here what happen when click on a node or edge...
>     });
> });
> ```
> 
> }`
> 
> generally you must insert the event click after the render of the graph

Many thanks for your reply! Now it is just a matter of convincing TypeScript of doing what I want to do. The com/transpiler complains that "_network" is a property that doesn't exist on Neovis. I understand that the idea of  these predefined types is to help me further down the line, but as a beginner it sure feels like a struggle uphill. But this is more of a me vs TypeScript issue, rather than Neovis. Thanks again!

> I started using neovis.js but had to give it up, for several reasons. One is that you will not see timely reactions from the maintainers. You will very quickly get in trouble for reasons like the one you are mentioning, but also from the lack of ability to impact what the nodes look like. I also happen not to like having to provide database credentials to the rendering layer, but that is just me. I went ahead and changed to using vis.js instead, and I am so happy that I did. If you want to see what I did you can take a look at Dynamics365FO-AppChecker/tools/Graph Explorer at master * microsoft/Dynamics365FO-AppChecker (github.com)<https://github.com/microsoft/Dynamics365FO-AppChecker/tree/master/tools/Graph%20Explorer>. I hope this helps. Best Regards Peter Villadsen From: denna10 ***@***.***> Sent: Wednesday, April 14, 2021 1:25 PM To: neo4j-contrib/neovis.js ***@***.***> Cc: Peter Villadsen ***@***.***>; Mention ***@***.***> Subject: Re: [neo4j-contrib/neovis.js] Events (#16) Sorry for resurrecting this, but could I ask for simple instructions on what I should do to be able to catch a click event on a node or edge? I'm using Neovis to visualize my data in an Angular app. I'm new to Angular, TypeScript, Neo4j, and thus Neovis, so I might be somewhat in over my head, but I was hoping to use the click event to show closer information about the node/edge to the user. I can see that people have had success with the code below, but I'm not sure about where I should put this code to make it work (it might simply be because I'm unused to TypeScript). I see in the code that there are ClickNode and ClickEdge events, but I can't make much sense of it. Any guidance is very much appreciated! viz.registerOnEvent("completed", (e)=>{ viz["_network"].on("click", (event)=>{ console.log(event.nodes[0]); }); }); - You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneo4j-contrib%2Fneovis.js%2Fissues%2F16%23issuecomment-819808595&data=04%7C01%7CPeter.Villadsen%40microsoft.com%7Cf86d9ba5b4b24d47cb8908d8ff836bf9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637540287219393145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BDoLNqkqJtnz27cUbn6hUKw2dOsfrwRl%2F2vO%2F03iFyE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYNH7ISPJPBEHOFBAD3PXLTIX225ANCNFSM4E4CXMXA&data=04%7C01%7CPeter.Villadsen%40microsoft.com%7Cf86d9ba5b4b24d47cb8908d8ff836bf9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637540287219403099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9hIac3Nx2oWQtHOv6eqCq27%2FmCKtpVIoiDCmzoV4EuY%3D&reserved=0>.

Thank you for your fast reply! I think those are some important points that you make. I'll make sure to take a closer look!

**Comment by denna10** [comment]
> > Sorry for resurrecting this, but could I ask for simple instructions on what I should do to be able to catch a click event on a node or edge? I'm using Neovis to visualize my data in an Angular app. I'm new to Angular, TypeScript, Neo4j, and thus Neovis, so I might be somewhat in over my head, but I was hoping to use the click event to show closer information about the node/edge to the user. I can see that people have had success with the code below, but I'm not sure about where I should put this code to make it work (it might simply be because I'm unused to TypeScript). I see in the code that there are ClickNode and ClickEdge events, but I can't make much sense of it. Any guidance is very much appreciated!
> > viz.registerOnEvent("completed", (e)=>{
> > viz["_network"].on("click", (event)=>{
> > console.log(event.nodes[0]);
> > });
> > });
> 
> To enable the click event, you must write something like this
> 
> `function drawGraph(cmd, direction, dimension)
> {
> $(.content).html(
> 
> )
> ```
> let config = {
>     container_id: "viz",
>     server_url: "bolt://localhost:7687",
>     server_user: "neo4j",
>     server_password: "********",
>     arrows: direction,
>     labels: {
>         'Friend': {
>             'caption': 'name',
>             'size': dimension,
>         },
>         'RemovedFriend': {
>             'caption': 'name',
>             'size': dimension,
>         }
>     },
>     relationships: {
>         "FRIEND": {
>             "thickness": "count",
>             "caption": false
>         }
>     },
>     initial_cypher: cmd,
> };
> 
> viz = new NeoVis.default(config);
> viz.render();
> 
> viz.registerOnEvent("completed", (e)=>{
>     viz["_network"].on("click", (event)=>{
>         ...put here what happen when click on a node or edge...
>     });
> });
> ```
> 
> }`
> 
> generally you must insert the event click after the render of the graph

Many thanks for your reply! Now it is just a matter of convincing TypeScript of doing what I want to do. The com/transpiler complains that "_network" is a property that doesn't exist on Neovis. I understand that the idea of  these predefined types is to help me further down the line, but as a beginner it sure feels like a struggle uphill. But this is more of a me vs TypeScript issue, rather than Neovis. Thanks again!

**Comment by denna10** [comment]
Short update: I got it working by doing as lx2pwnd described it, and by turning of TypeScripts strict mode (then what's the point of TS in the first place? Might come back to thos later). To get more specific information on nodes and edges I used .on("selectEdge") and .on("selectNode") instead of .on("click"). Many thanks for the help!

**Comment by thebestnom** [comment]
I added network in 2.0.0 but Im too afraid to publish it because I don't have testers and it breaks a lot of things

**Comment by denna10** [comment]
> I added network getter in 2.0.0 but Im too afraid to publish it because I don't have testers and it breaks a lot of things(I did publish it as alpha)

I see. The network getter, does it make these thing run with TypeScript in strict mode?

**Comment by thebestnom** [comment]
Should, and I fix that if it won't (also remember that you can always use `as any` in struct mode)

**Comment by thebestnom** [comment]
viz._network or viz["_network"]

**Comment by thebestnom** [comment]
But in 2.0 you can just use viz.network as I added that as a getter

**Comment by nish-patel** [comment]
@thebestnom trying to use viz.network to utilize the vis.js afterDrawing event but am getting an error saying the property is null.

JS Code:

```js
            viz.network.on("afterDrawing", (e) => {
                console.log(e.recordCount)
                // Record the end time
                var drawendTime = performance.now();

                // Calculate the time taken
                var drawtimeTaken = drawendTime - startTime;

                // Display the time taken
                document.getElementById("timeTakenLabel2").innerText = "Time taken: " + (drawtimeTaken/1000).toFixed(2) + " seconds";
                });
```

Error (172 being the first line of the snippet above):

graph-visualization.html:172 Uncaught TypeError: Cannot read properties of undefined (reading 'on')

**Comment by thebestnom** [comment]
You can only use the network after the drawing, so it should be
`vis.on`

**Comment by nish-patel** [comment]
I tried that originally and got an error that its not a function

TypeError: viz.on is not a function

**Comment by thebestnom** [comment]
You're right, it's `vis.registerOnEvent`

**Comment by nish-patel** [comment]
vis.registerOnEvent only lets me do the four events present in [events.ts
](https://github.com/neo4j-contrib/neovis.js/blob/master/src/events.ts)

afterDrawing is a vis-js event and from my understanding of the above thread those are now implemented in 2.0+ but I'm unsure how to call it.  Below is the error if I try vis.registerOnEvent('afterDrawing')

Uncaught Error: Unknown event: afterDrawing

**Comment by thebestnom** [comment]
```js
 viz.registerOnEvent("afterDrawing", () => {
     viz.network.on("click", (e) => {
                
                console.log(e.recordCount)
                // Record the end time
                var drawendTime = performance.now();

                // Calculate the time taken
                var drawtimeTaken = drawendTime - startTime;

                // Display the time taken
                document.getElementById("timeTakenLabel2").innerText = "Time taken: " + (drawtimeTaken/1000).toFixed(2) + " seconds";
                })});
```

**Comment by nish-patel** [comment]
Gives the same unknown event error

<img width="334" alt="image" src="https://github.com/neo4j-contrib/neovis.js/assets/35316880/fdb9df9e-1b93-4f40-bff3-17af172243e9">

**Comment by thebestnom** [comment]
```js
viz.registerOnEvent("completed", () => {
     viz.network.on("click", (e) => {
                
                console.log(e.recordCount)
                // Record the end time
                var drawendTime = performance.now();

                // Calculate the time taken
                var drawtimeTaken = drawendTime - startTime;

                // Display the time taken
                document.getElementById("timeTakenLabel2").innerText = "Time taken: " + (drawtimeTaken/1000).toFixed(2) + " seconds";
                })});
```
Sorry, I thought you checked the docs before writing the code so I didn't double checked the names
@nish-patel
