### ISSUE TITLE
connect to remote server

### ISSUE THREAD

**Issue by gaotian98** [neo4j-contrib/neovis.js#160]
I modified the index.html for my own application and it ran well locally. When I downloaded the neo4j on a remote server and tried to deploy the static visualization page, I added "dbms.default_listen_address=0.0.0.0" in neo4j.conf and changed "localhost" to my server IP address for the "server_url" field in the html. The frontend threw "neovis.js:56 Neo4jError: Failed to establish connection in 30000ms".

Is there any other configuration change that I'm missing? Thanks for any advice!

**Comment by thebestnom** [comment]
Have you made sure that you are connecting through the correct port? Also have you tried connecting through the neo4j webpage with the same credentials?

**Comment by gaotian98** [comment]
Thank you. I think the port is correct. 
Do you mean try connecting to the neo4j browser? The neo4j console says "Remote interface available at http://xx.xx.xx.xxx:7474/" and I open the port on server using "firewall-cmd --permanent --add-port=7474/tcp", but when I try to access this IP address, it fails to display the neo4j browser. Do you know what else should be done?

**Comment by thebestnom** [comment]
Hmm... Never saw this kind of problem, mind opening issue on neo4j github, I think they would be more helpful on that kind of issues 😅

**Comment by gaotian98** [comment]
Sure. Thank you anyway!
