### ISSUE TITLE
TypeError: _this._strategy is undefined

### ISSUE THREAD

**Issue by ChristophNoack** [neo4j-contrib/neovis.js#163]
Hi,
when I try to run neovis.js with React I get the following error.
I didn't change the original code. So it's kind of crazy. Could you help me? I simply don't know how to interpret this error.
Thanks and best regards
Christoph

> TypeError: _this._strategy is undefined
> ./node_modules/neovis-ts/dist/neovis.js/NeoVis</NeoVis.prototype.formatNodes/<
> C:/Users/chris/Desktop/React/wikilines/wikilines/node_modules/neovis-ts/dist/neovis.js:433

```
   430 | var description = new Map();
   431 | keys.map(function (key) {
   432 |    var value = map.get(key);
> 433 |     var keyStrats = _this._strategy.NodeStrategy[key];
   434 |     if (keyStrats) {
   435 |         keyStrats.map(function (keyStrat) {
   436 |             if (keyStrat.htmlSuffix) {
```

**Comment by thebestnom** [comment]
That weird. What version do you use?

**Comment by ChristophNoack** [comment]
Hi, thanks for the rapid response. I use "neovis-ts": "^1.0.8"

**Comment by thebestnom** [comment]
Wait, that neovis-ts, thats not our code... Please use neovis.js if you want help here 😅

**Comment by thebestnom** [comment]
(neovis.js does support typescript)

**Comment by ChristophNoack** [comment]
what does that mean to me?

**Comment by thebestnom** [comment]
You install it by `npm i neovis-ts` this library is `neovis.js` which is a little bit different (if Im correct neovis-ts is a fork of this repo)

**Comment by ChristophNoack** [comment]
Now I am totally confused. I installed neovis-ts. Is that right or wrong? What shall I install instead? I only found that...
