### ISSUE TITLE
How do I display the name of an attribute on a node

### ISSUE THREAD

**Issue by chenlunyiyv** [neo4j-contrib/neovis.js#166]
I want to display the name attribute on the node, not over the mouse.
Just like this

**Comment by chenlunyiyv** [comment]
![aa](https://user-images.githubusercontent.com/52765930/113416519-1cd5a980-93f4-11eb-9a78-eb8ac14ff746.png)

**Comment by thebestnom** [comment]
```js 
{labels:{label:{caption: "atrribute"}}}
```
Or Im missing somthing?

**Comment by chenlunyiyv** [comment]
I may not have described it very well.
This is my result.
![bb](https://user-images.githubusercontent.com/52765930/113418441-15b09a80-93f8-11eb-883e-f01cb089330b.png)
But I want to display like this.
![ab](https://user-images.githubusercontent.com/52765930/113418548-4d1f4700-93f8-11eb-93a1-17d14f0750bb.png)

**Comment by thebestnom** [comment]
Oh, I understand, it's probebly a vis config, so I can't help you unless you try to use 2.0.0 alpha 😅, the current version doesn't support overriding vis config directly

**Comment by thebestnom** [comment]
Wait, what I said in the last comment was supposed to write the caption under the node, not inside the popup, I thought the problem of yours was the placement

**Comment by chenlunyiyv** [comment]
Can you tell me what I should do? I'm a beginner.Thank you very much.😃

**Comment by thebestnom** [comment]
Can you send tye configuration here so I can help you better?

**Comment by chenlunyiyv** [comment]
function draw() {
      var config = {
        container_id: "viz",
        server_url: "bolt://39.99.219.86:7687",
        server_user: "neo4j",
        server_password: "123456",
        labels: {
          Character: {
            caption: "name",
            size: "pagerank",
            community: "community",
            font: {
              size: 26,
              color: "#000000",
            },
            title_properties: ["name", "pagerank"],
          },
        },
        relationships: {
          INTERACTS: {
            thickness: "weight",
            caption: true,
          },
        },
        initial_cypher: "MATCH (n)-[r]->(m) RETURN n,r,m",
      };
      viz = new NeoVis.default(config);
      viz.render();
      console.log(viz);

This is the example above, and I haven't changed anything.

**Comment by thebestnom** [comment]
Hmm... That wierd `caption` should work... Let me check in tge code

**Comment by thebestnom** [comment]
Oh, you didn't add Person to the labels

**Comment by chenlunyiyv** [comment]
Hmm~ o(*￣▽￣*)o,Can you tell me where to put it.I don't really understand.

**Comment by thebestnom** [comment]
Just add 
```js
{ Person:{caption:"name"}}
```
To labels

**Comment by chenlunyiyv** [comment]
Nothing seems to have changed.🤣

**Comment by thebestnom** [comment]
Thats weird, can you send here an example node?

**Comment by chenlunyiyv** [comment]
![图片](https://user-images.githubusercontent.com/52765930/115222048-e494d180-a13c-11eb-934c-386180a0e49a.png)

**Comment by thebestnom** [comment]
I meant the data and labels, not an image 😅, but are you sure it didn't work? The caption is not Person anymore

**Comment by chenlunyiyv** [comment]
Oh,I am very sorry that I misunderstood your meaning.But what I want is to put the name of the node in the ball instead of showing it down there.And I want to make the ball a little bigger.

**Comment by thebestnom** [comment]
Oh, that way mote complicated, you'll have to upgrade to neovis.js@2.0.0-alpha and then configre some things, I could help you in few hours, ping again here if I don't respond in about 5 hours 😄

**Comment by chenlunyiyv** [comment]
Where can I download it.I can't seem to find it.😅

**Comment by thebestnom** [comment]
Are you using npm? If so run `npm i neovis.js@2.0.0-alpha.3`

If you are using cdn use `http://unpkg.com/neovis.js@2.0.0-alpha.3`

But make sure to look at the docs at https://github.com/neo4j-contrib/neovis.js/tree/2.0.0 because it breaks some configuration

**Comment by thebestnom** [comment]
Oh, sorry, I forgot, have you managed to make it work?

**Comment by chenlunyiyv** [comment]
Thank you for your concern. I haven't had time to read Guthub recently, so I forgot to reply. I still don't know how to use neovis.js@2.0.0-alpha, I'd better put the name under the ball.I really appreciate your help over the past month.
