### ISSUE TITLE
thickness between nodes

### ISSUE THREAD

**Issue by spyx** [neo4j-contrib/neovis.js#167]
hi all,

I see multiple connection between my nodes. I would like to set thickness of relation between them. I tried weight or count but i always see all relations between nodes.

my database look like
(A:node)-[:connectio1]-(B:node)
(A:node)-[:connectio1]-(B:node)
(B:node)-[:connectio1]-(C:node)
(C:node)-[:connectio2]-(D:different_node)
(C:node)-[:connectio2]-(D:different_node)
(C:node)-[:connectio2]-(D:different_node)

how i can set make thickness relation between nodes A, B and same time between nodes C, D

**Comment by thebestnom** [comment]
There is a default config (docs in the README) if you mean configure thickness in the same way

**Comment by spyx** [comment]
I tried that but i cant get it work. Look for solution on google but no luck. 

here is my config file

var config = {
                    container_id: "viz",
                    server_url: "bolt://localhost:7687",
                    //server_user: "neo4j",
                    //server_password: "sorts-swims-burglaries",
                    labels: {
                        "node": {
                            "caption": "name",
                            "thickness": "weight",
                        },
                        "different_node" : {
                            "caption": "name",
                            "thickness": "weight",
                        },
                    },
                    relationships: {      
                        "connectio1": {
                            "thickness": "weight",
                            "caption": false,
                            
                        },
                        "connectio1" : {
                            "thickness": "weight"
                            "caption": true,
                        },
                    },
                    arrows: true,
                    hierarchical: true,
                    initial_cypher: "match (p)-[r:connectio1]-(q)return * limit "+limit
                }

**Comment by thebestnom** [comment]
```js
var config = {
                    container_id: "viz",
                    server_url: "bolt://localhost:7687",
                    //server_user: "neo4j",
                    //server_password: "sorts-swims-burglaries",
                    labels: {
                        "node": {
                            "caption": "name",
                            "thickness": "weight",
                        },
                        "different_node" : {
                            "caption": "name",
                            "thickness": "weight",
                        },
                    },
                    relationships: {      
                        "connectio1": {
                            "caption": false,
                            
                        },
                        "connectio1" : {
                            "caption": true,
                        },
                        [NeoVis.NEOVIS_DEFAULT_CONFIG]: {
                            thickness: "weight"
                        }
                    },
                    arrows: true,
                    hierarchical: true,
                    initial_cypher: "match (p)-[r:connectio1]-(q)return * limit "+limit
 }
```

**Comment by thebestnom** [comment]
Like that?

**Comment by thebestnom** [comment]
Also you can do the same thing in node

**Comment by spyx** [comment]
still see multiple relations.

![image](https://user-images.githubusercontent.com/17102553/114308759-bc9cd280-9a99-11eb-8448-55c268698da2.png)

**Comment by thebestnom** [comment]
Ahh sorry, I didn't understood the question
You need to return count in the cypher, somthing like
```cypher
Match (a), (b)
Return a, b, size
return a, b, size((a)-[]-(b)) as wight
```
And put wight on a new relationship or somthing like that

**Comment by thebestnom** [comment]
Also you can try only returning a single relationship per node duo, and use neovis@2.0.0-alpha cypher value and count number of relationship there

**Comment by spyx** [comment]
there is twice return on you cypher. Is it correct?

**Comment by thebestnom** [comment]
Sorry, Im tired 😅, also even if it was correct it will not work because I never returned a relationship, the wight there should be plastered onto a relationship in order to work

**Comment by spyx** [comment]
i really looking into the most simplest solution. I have probably 5 different nodes and trying to "clear" most of relation to put them together when possible. I can add any properties into relation of needed....

**Comment by thebestnom** [comment]
Well... Neovis is mostly a visualize library, meaning that it's only shows what returns from the cypher, meaning that if you need anything that is not on the node themselves need tp be happening in the cypher (2.0.0 change that a bit, you can after the initializtion change the relationship)

**Comment by spyx** [comment]
i thought there is trick to make thickness depends on relation between nodes.

**Comment by thebestnom** [comment]
I think there is on nodes, not on relationship...  I think this is a possibility directly on vis, but unless you're on 2.0.0 you can't directly manipulate vis configuration...

**Comment by thebestnom** [comment]
Also checked doesn't look like a thing you can do in vis, you need to aggregate yourself in cypher...

**Comment by spyx** [comment]
Thank you so much... i probably misunderstand documentation. Please close this
