### ISSUE TITLE
Catch initial_cypher query syntax errors

### ISSUE THREAD

**Issue by Koshmaar** [neo4j-contrib/neovis.js#169]
Hi, I want to create simple form where user can type his own cypher query and it gets visualized. Just like the form-example from examples/ - I have it and it works. However, if user makes syntax error, the error will be displayed in developer console, and there's no way of dealing with it programatically, ie. this doesn't work
```js
        function run_query(query) {
            var config = {
                ...
                initial_cypher: query,
            };

            try {
                viz = new NeoVis.default(config);
                viz.render();
            }
            catch (exc) {
                console.log("caught error: ", exc);
                // set interactively some element on page to exc.details() etc
            }
```

There's no exception to caught, it just immediately dies in neovis internals with some message ie. `Neo4jError: Variable `nsd` not defined (line 1, column 22 (offset: 21))`

Is it possible at all with current neovis? If not, please treat it as feature request :)

**Comment by Koshmaar** [comment]
Indeed, what worked for me:
```
    viz = new NeoVis.default(config);
    viz.registerOnEvent("error", (err)=>syntax_error(err));

    $('#cypher-query-error').text('');
    viz.render();
}

function syntax_error(err) {
    $('#cypher-query-error').text(err.error_msg);
}
```
Thank you for quick response :) Info about it could be added to documentation. Closing this issue.

**Comment by thebestnom** [comment]
Added to the newer docs for 2.0.0 (auto generated from d.ts)... I should cherrypick that commit 😅
