### ISSUE TITLE
How do I add events to a node

### ISSUE THREAD

**Issue by chenlunyiyv** [neo4j-contrib/neovis.js#171]
When I click the node that has been generated, can I click the ball to realize the jump of the page, or display detailed information.

**Comment by thebestnom** [comment]
After complete you can run
```js
neovisInstance.network.on("click", (nodes) => console.log(node))
```
Or somthing like that, make sure you use that after init complete

**Comment by chenlunyiyv** [comment]
Where should I put it

**Comment by thebestnom** [comment]
```js
this.neovisInstance.registerOnEvent("complete", () =>
    //Here
``|

**Comment by chenlunyiyv** [comment]
Sorry, I still don't understand where it should be placed and when it should be finished.

**Comment by chenlunyiyv** [comment]
```
viz.registerOnEvent("completed", () => {
    console.log("It is completed.");
    viz._network.on("click", (nodes) => console.log(nodes));
  });
```
I have tried to do this, but it activates whenever there is a click event, which is not what I want.
I also tried the following situation, but with no results.
```
viz.registerOnEvent("completed", () => {
    console.log("It is completed.");
    viz._network.on("clickNode", (nodes) => console.log(nodes));
  });
```

**Comment by thebestnom** [comment]
Sorry for disappearing, have you made it?

**Comment by thebestnom** [comment]
No answer from op, and should be trivial on 2.x
