### ISSUE TITLE
Multiple instances of neovis not rendering with angular

### ISSUE THREAD

**Issue by JaredRackley** [neo4j-contrib/neovis.js#174]
I have an angular app that is using neovis to create a visualization of the database. 

This is what I use to render the neovis demonstration:
```js
neovis.component.ts:
import NeoVis from 'neovis.js/dist/neovis.js';

ngAfterViewInit(): void {
    const config = {
      container_id: 'viz',
      server_url: 'bolt://localhost:7687',
      server_user: '...',
      server_password: '...',
      initial_cypher: `...`
    };
      
    const viz = new NeoVis(config);
    viz.render();
    console.log(viz);
}

neovis.component.html:
<div id="viz"></div>

messenger.component.html:
<neovis-component *ngIf="..."></neovis-component>  

```

I am using this in a message component, so if the user types in a command, then the bot will respond with the neovis visualization. 

However, it seems that if I issue the command multiple times, the first instance will be rendered, while all of the others appear to be blank (as shown in the images below).

How can I get all the instances to render?

![vis-1](https://user-images.githubusercontent.com/37847039/118205697-c8bbdd00-b415-11eb-9d72-1df4b4c520fd.png)
![viz-2](https://user-images.githubusercontent.com/37847039/118205698-c9547380-b415-11eb-95c9-5fd3ada01391.png)

**Comment by thebestnom** [comment]
Hmmm, I think that because of the id on the div, neovis will probebly take the first one it finds with tge same id (I think thats an js thing), try geberating tge id by somthing (uuid maybe?)

**Comment by JaredRackley** [comment]
That was the issue! Once I generated the id dynamically, they all rendered! Thank you so much for the help!
