### ISSUE TITLE
Connection via bolt+s or bolt+scc

### ISSUE THREAD

**Issue by masonedmison** [neo4j-contrib/neovis.js#175]
Currently, I get an `Uncaught Error: Unknown scheme: bolt+s` when trying to connect with `bolt+s` or `bolt+scc` - is this indeed not possible?

**Comment by thebestnom** [comment]
I'm not sure, but it might be because you're using old neo4j driver, how are you using neovis?

**Comment by masonedmison** [comment]
It indeed ended up being a version issue - as soon as switching to the most recent neovis version, it now works :).

I'll close the issue.
