### ISSUE TITLE
Are the tooltips gone in 2.0.0?

### ISSUE THREAD

**Issue by aguinaldoabbj** [neo4j-contrib/neovis.js#176]
Hi all,

I have just tested branch 2.0.0 and noticed that tooltips are gone. Is that right? How are node properties shown?

**Comment by dukesun99** [comment]
The usage for 2.0.0 is a bit different, and it's not compatible with 1.x. You could check the modified example in 2.0.0 branch for how to add tooltip.

**Comment by aguinaldoabbj** [comment]
> The usage for 2.0.0 is a bit different, and it's not compatible with 1.x. You could check the modified example in 2.0.0 branch for how to add tooltip.

Thanks for helping.

Could you please point to me which of the examples covers adding tooltips? I can't locate in any. I've checked the code for neovis.js and I couldn't find the code snippet that deals with that.

**Comment by thebestnom** [comment]
Welp, I think that's common enough that I should add an easier way to do that... For now check https://github.com/neo4j-contrib/neovis.js/blob/2.0.0/examples/advanced-example.html

**Comment by aguinaldoabbj** [comment]
> Welp, I think that's common enough that I should add an easier way to do that... For now check https://github.com/neo4j-contrib/neovis.js/blob/2.0.0/examples/advanced-example.html
> It's under the function
Do you mean: `<script>
	$('#reload').click(function () {

		var cypher = $('#cypher').val();

		if (cypher.length > 3) {
			viz.renderWithCypher(cypher);
		} else {
			console.log('reload');
			viz.reload();

		}

	});

	$('#stabilize').click(function () {
		viz.stabilize();
	});

</script>`

By the way, I search the docs I couldn't find guidance on how to use the NeoVisAdvanceConfig interface to get static options nodes/relationships? Could you please give me a hint on this?

**Comment by thebestnom** [comment]
Oh, the docs doesn't show an example with advance?
Ill fix that! Thanks for testing 2.0.0!
It should be imported first with
```ts
import { NEOVIS_ADVANCED_CONFIG } from 'neovis.js'
config = {
   // ...
   labels: {
      label: {
         mappedProp: "prop from neo4j node",
         [NEOVIS_ADVANCED_CONFIG]: {
            functions: { a: (prosp) => props.color}
         }
      }
   }
   //...
}
```
The point of 2.0.0 is to make neovis change from a sloppy wrapper around vis.js to a full combination of vis and neo4j, so all properties are now vis.js properties and taken from the node props
(Ill add what I just wrote to the docs 😅)
So for example if you have a node in neo4j
```cypher
(Label: {color: green, lives: uk})
```
and you want the node color in the web to get the color from the neo4j node you check in vis.js how to set node color (which is color) and add to the label config `color: "color"` and it will take the color prop from the neo4j node
To make that even more versatile @dukesun99 added advance config which allows you to use a function that gets the props from the neo4j node and returns what you want in the vis prop, and also a static value that will always be added
(Everything here also applies to relationships)
So in vis to show tooltip you need to add title to the vis prop and do a util funtions in the advance that's takes the neo4j node props and make a tooltip string

**Comment by thebestnom** [comment]
Sorry for the long and complicated reply, I should make the simple tooltip way simpler

**Comment by aguinaldoabbj** [comment]
> Oh, the docs doesn't show an example with advance?
> Ill fix that! Thanks for testing 2.0.0!
> It should be imported first with
> 
> ```ts
> import { NEOVIS_ADVANCED_CONFIG } from 'neovis.js'
> config = {
>    // ...
>    labels: {
>       label: {
>          mappedProp: "prop from neo4j node",
>          [NEOVIS_ADVANCED_CONFIG]: {
>             functions: { a: (prosp) => props.color}
>          }
>       }
>    }
>    //...
> }
> ```
> 
> The point of 2.0.0 is to make neovis change from a sloppy wrapper around vis.js to a full combination of vis and neo4j, so all properties are now vis.js properties and taken from the node props
> (Ill add what I just wrote to the docs )
> So for example if you have a node in neo4j
> 
> ```
> (Label: {color: green, lives: uk})
> ```
> 
> and you want the node color in the web to get the color from the neo4j node you check in vis.js how to set node color (which is color) and add to the label config `color: "color"` and it will take the color prop from the neo4j node
> To make that even more versatile @dukesun99 added advance config which allows you to use a function that gets the props from the neo4j node and returns what you want in the vis prop, and also a static value that will always be added
> (Everything here also applies to relationships)
> So in vis to show tooltip you need to add title to the vis prop and do a util funtions in the advance that's takes the neo4j node props and make a tooltip string

So the only way to get different colors per node label is to encode the color in each node? Couldn't I just pick a static color for a node label?

I understood the point of 2.0.0  but I still couldn't get its mechanics.

In the excerpt of code you wrote:
```
 mappedProp: "prop from neo4j node",
         [NEOVIS_ADVANCED_CONFIG]: {
            functions: { a: (prosp) => props.color}
         }
```
mappedProp is just the name/description of a new neovis.js property? What does this inside function work? 

For advanced-example.html you code is a bit different:

`labels: {
					Character: {
						label: 'pagerank',
						group: 'community',
						[NeoVis.NEOVIS_ADVANCED_CONFIG]: {
							cypher: {
								value: "MATCH (n) WHERE id(n) = $id RETURN n.size"
							},
							function: {
								title: (node) => {
									return viz.nodeToHtml(node, undefined);
								}
							},
						}
					}
				}`

This [NeoVis.NEOVIS_ADVANCED_CONFIG] entry inside the configuration of a label isn't equivalent of "special" node property? What is resulting of this? A pair property:value as the regular ones? Is the tooltip "effect" is given by this nodeToHtml() function already defined in neovis.js?

I'm very helpful for your help. In fact, for now, I just need to control color and shape label-wise. And also control relationship color relationship-wise. I've managed to accomplish it in the past by editing node properties directly in neovis.js file in 1.0.0, but the result was really messy. When I noticed the 2.0.0 branch and the problems it's supposed to solve, I was very hopeful. But I'm really having a hard time trying to understand the mechanics of 2.0.0.

**Comment by dukesun99** [comment]
@aguinaldoabbj Sorry for the missing and incomplete documentation. If you want to keep a property constant for all nodes of the label, you can do something like

```
import { NEOVIS_ADVANCED_CONFIG } from 'neovis.js'
config = {
   // ...
   labels: {
      label1: {
         mappedProp: "prop from neo4j node",
         [NEOVIS_ADVANCED_CONFIG]: {
            static: { 
               color: "red"
            }
         }
      }
   }
   //...
}
```
And yes, the documentation of 2.0.0 is still very limited. You may experience a hard time understanding how to use them. Maybe you can check the code [here](https://github.com/neo4j-contrib/neovis.js/blob/689e3a91ef79db1dca0d68e14e9bd69545132812/src/neovis.js#L237) to get some idea of how the advanced config is handled to generate vis.js objects.

**Comment by dukesun99** [comment]
@aguinaldoabbj For the question regarding the `nodeToHtml()` function, this function is a pre-defined helper to display tooltips. The function is for easier migration from 1.x to 2.0.0. The feature of 2.0.0 is it gives you full control to vis.js properties, and the neovis.js only handles the data reading, and based on the configuration you provided to generate vis.js objects. The function field allows you to pass in a function, the return value of the function decides what to be put into the vis.js objects.

**Comment by aguinaldoabbj** [comment]
Just an addendum. Running the advanced-example.html as it is, I get the following for my graph:

![download](https://user-images.githubusercontent.com/13151704/119263792-db24dc00-bbb6-11eb-86af-75df8f1888f0.png)

In this example, tooltips are not showing... And nodes size are not proportional to the attribute size in the nodes as I was expecting because of the excerpt:
```
[NeoVis.NEOVIS_ADVANCED_CONFIG]: {
							cypher: {
								value: "MATCH (n) WHERE id(n) = $id RETURN n.size"
							},
							function: {
								title: (node) => {
									return viz.nodeToHtml(node, undefined);
								}
							},
						}

```

**Comment by dukesun99** [comment]
@aguinaldoabbj Emm that looks strange. It could be bugs in our code, either in the example or neovis. I am not sure if @thebestnom has time to look at it? If no I will find some time to do more testing of the code.

**Comment by thebestnom** [comment]
Ill look at that in a minute

**Comment by aguinaldoabbj** [comment]
NEOVIS_ADVANCED_CONFIG isn't supposed to be defined in neovis.js ? I assured 2.0.0 is the version of neovis.js being loaded. Or do I need to explicitly import it ? If so, where in the code should I import it? I've tried to put the line
`import { NEOVIS_ADVANCED_CONFIG } from 'neovis.js'` with no luck.

 In none of the examples in examples/ NEOVIS_ADVANCED_CONFIG is explicitly imported

However, I belive everything is being imported as I can't see problem related to loading in browser's inspector console

**Comment by thebestnom** [comment]
of course it is, if you use NeoVis used by using cdn object has the same properties as `import * as NeoVis from 'neovis.js'`

**Comment by aguinaldoabbj** [comment]
> of course it is, if you use NeoVis used by using cdn object has the same properties as `import * as NeoVis from 'neovis.js'`
> so you can use `NeoVis.NEOVIS_ADVANCED_CONFIG ` if you are using neovis from the cdn, but you can't use the object created from `new NeoVis()`

I'm using the example as it is. In the example, I believe neovis is loaded globally with` <script type="text/javascript" src="../dist/neovis.js"></script>`

This what I'm running:

```
<!doctype html>
<html>
<head>
    <title>Neovis.js Simple Example</title>
    <style type="text/css">
        html, body {
            font: 16pt arial;
        }

        #viz {
            width: 900px;
            height: 700px;
            border: 1px solid lightgray;
            font: 22pt arial;
        }

    </style>

    <!-- FIXME: load from dist -->
    <script type="text/javascript" src="../dist/neovis.js"></script> 


    <script
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>

    <script type="text/javascript">
		// define config car
		// instantiate nodevis object
		// draw

		
		var viz;
		import * as NeoVis from 'neovis.js/dist/neovis.js'

		function draw() {
			
			var config = {
				container_id: 'viz',
				neo4j: {
					server_url: 'bolt://localhost:7687',
					server_user: ''",
					server_password: ''"
				},
				visConfig: {
					nodes: {
						shape: 'square'
					},
					edges: {
						arrows: {
							to: {enabled: true}
						}
					},
				},
				labels: {
					Person: {
						label: 'pagerank',
						group: 'community',
						[NeoVis.NEOVIS_ADVANCED_CONFIG]: {
							cypher: {
								value: "MATCH (n) WHERE id(n) = $id RETURN n.size"
							},
							function: {
								title: (node) => {
									return viz.nodeToHtml(node, undefined);
								}
							},
						},
						mappedProp: "prop from neo4j node",
         				[NeoVis.NEOVIS_ADVANCED_CONFIG]: {
            				static: { 
               				color: "red", // static property is a constant property for all nodes of the type
            				shape: "circle"
							}
         				}
					}
				},
				relationships: {
					ACTED_IN: {
						value: 'weight',
						[NeoVis.NEOVIS_ADVANCED_CONFIG]: {
							function: {
								title: (edge) => {
									return viz.nodeToHtml(edge, undefined);
								}
							},
						}
					}
				},
				initial_cypher: 'MATCH (n)-[r]->(m) RETURN n,r,m'
			};

			viz = new NeoVis.default(config);
			viz.render();
			console.log(viz);

		}
    </script>
</head>
<body onload="draw()">
<div id="viz"></div>


Cypher query: <textarea rows="4" cols=50 id="cypher"></textarea><br>
<input type="submit" value="Submit" id="reload">
<input type="submit" value="Stabilize" id="stabilize">


</body>

<script>
	$('#reload').click(function () {

		var cypher = $('#cypher').val();

		if (cypher.length > 3) {
			viz.renderWithCypher(cypher);
		} else {
			console.log('reload');
			viz.reload();

		}

	});

	$('#stabilize').click(function () {
		viz.stabilize();
	});

</script>
</html>
```
This is exactly the advanced-example.html code, with few adjustments. I get no node names, no tootips and nodes sizes not proportional to the size property of my nodes...

No errors are shown in console.

**Comment by thebestnom** [comment]
Thats sounds like a bug, Ill test that Tomorrow, really sorry for the inconveniences... 😓

**Comment by aguinaldoabbj** [comment]
> Thats sounds like a bug, Ill test that Tomorrow, really sorry for the inconveniences...
Don't worry. I have to thank you for this great tool and for answering annoying issues on the weekend. 

I've managed to define the colors and names from your guidance, however, I'm still a bit confused on how things are supposed to work.
I've checked the API reference and there I can see 3 sets of configurations:

NeovisConfig: I understood this a more general, graph-wise configuration.
LabelConfig / RelationshipConfig: this more granular configuration regarding each type of labels and relations.
NeoVisAdvanceConfig: an advanced configuration divided in three sub-clases: static, cypher and function.

However, I think several configs overlap with each other. For example, according to the API, LabelConfig has the property 'color'. If I set this to 'red', It does not work. However, if I set the static property 'color' in NEOVIS_ADVANCED_CONFIG for a label type, it works.

The same does not occur for the 'label' property for LabelConfig. If set it to to the property 'name' existent in my nodes, I can get the names for the nodes in the drawing. By the way, I saw that the sizes of the nodes set are according to the length of the names. Isn't the reason I can't get sizes proportional to a property?

Another odd thing: in fact, tooltips are showing but only for relationships, as you can see in the figure 
![Screenshot_20210523_191204](https://user-images.githubusercontent.com/13151704/119278334-f9143000-bbfa-11eb-8321-6e1e38278d44.png)

I noticed that nodeToHtml() function is used both for nodes and relationships in the advanced-example.html. Is that right?

**Comment by thebestnom** [comment]
You almost understood completely 😄
The only thing that you missed is the default normal label/relationship config, in that the value is mapped from the neo4j node to the vis node
So in your example setting it to red will not work because neovis will try to take the property red from the neo4j node which it doesn't have (it probably have a color property or how you set that) that's the reason why `name` work, because it takes the property name from the neo4j node and put it on the vis node (so if you look at the end object you'll see the actual name and not `name` in the object), on the other hand the `static` in the advance config is to put a static value to all vis nodes with that label, so putting red in the color to all vis nodes and it will work

And that's the same in relationships so the util function `nodeToHtml` should work for it too

If you want to set size Im pretty sure that's the property value on the *vis* object so you need to map value from the neo4j object (if not Ill see the configuration in vis.js)

**Comment by thebestnom** [comment]
I think maybe removing the weird default map from neo4j and then removing the NEOVIS_ADVANCED_CONFIG, and then just putting all the advance straight into the labelConfig
```js
config = {
   //...
   labels: {
      Label: {
         mapped: {},
         functions: {},
         cypher: {},
         static: {}
      }
   }
}
but than it will be by default way less flat and I think that will make people go away from this library even more...

**Comment by aguinaldoabbj** [comment]
> You almost understood completely 
> The only thing that you missed is the default normal label/relationship config, in that the value is mapped from the neo4j node to the vis node
> So in your example setting it to red will not work because neovis will try to take the property red from the neo4j node which it doesn't have (it probably have a color property or how you set that) that's the reason why `name` work, because it takes the property name from the neo4j node and put it on the vis node (so if you look at the end object you'll see the actual name and not `name` in the object), on the other hand the `static` in the advance config is to put a static value to all vis nodes with that label, so putting red in the color to all vis nodes and it will work
> 
> And that's the same in relationships so the util function `nodeToHtml` should work for it too
> 
> If you want to set size Im pretty sure that's the property value on the _vis_ object so you need to map value from the neo4j object (if not Ill see the configuration in vis.js)

Thanks for your patience in explaining this in great detail. I believe I'm now figuring things out. I'm going to work on my application using 2.0.0.

One last thing still regarding tooltips:
I've noticed in 2.0.0 you no longer define node.title to show the tooltips anymore. Instead, you use the util function nodeToHTML() function. However, by using this function, the strings in the tooltip don't get formatted. So, for now in 2.0.0, all tooltips are shown as strings with HTML markups. On the other hand, just as it was before 2.0.0, if I define node.title inside buildNodeVisObject(), as a string with HTML markups, the tool tip is shown in the desired way (bold, itallic, linebreaks,etc.). I don't really get whats is the practical difference between the two modes in terms of rendering vis.js objects. Do you know why this happens and if is there an easy way to overcome this problem?

**Comment by thebestnom** [comment]
About the html, looks like vis.js diabled html parsing by default and it needs to be parsed by our code...
https://visjs.github.io/vis-network/examples/network/other/html-in-titles.html
I need to fix that in the code...

**Comment by aguinaldoabbj** [comment]
@thebestnom Thanks!
However, I was working on a function to replace that nodeToHtml() function and was about to make a PR with this:

```
titleToHtml(neo4jElem, title_properties) {
		//html string
		let titleString = '';
		
		//check if element is an edge or node
		//put node label or rel type on top of the tooltip
		if (neo4jElem.type) {
			//put relationship type on top of title
			titleString = `<strong><u>${neo4jElem.type}</u></strong><br>`;
		} else {
			//put node labe on top of title
			titleString = `<strong><u>${neo4jElem.labels[0]}</u></strong><br>`;
		}
		
		if (!title_properties) {
			title_properties = Object.keys(neo4jElem.properties);
		}
		for (const key of title_properties) {
			const propVal = this._retrieveProperty(key, neo4jElem);
			if (propVal) {
				titleString += this.propertyToString(key, propVal);
			}
		}

		//define a html container and put the html string
		let title = document.createElement("div");
		title.innerHTML = titleString;

		return title;
	}
```
![Screenshot_20210525_180948](https://user-images.githubusercontent.com/13151704/119569598-54722980-bd85-11eb-855e-9ac595a1b9e6.png)
![edge](https://user-images.githubusercontent.com/13151704/119569832-aadf6800-bd85-11eb-8976-b1fcf6b573db.png)

**Comment by thebestnom** [comment]
in a minute, wait for a second, just renamed it to be more consistent

**Comment by thebestnom** [comment]
look at  https://github.com/neo4j-contrib/neovis.js/pull/181
I changed where it takes it from (you don't need a neovis instance to use it

**Comment by thebestnom** [comment]
Ok, pushed to alpha.5
also remember that the whole point of 2.0.0 to be way more versetile, if this code is not generic enough you can just put it in your codebase 😄
(still didn't looked at your code, just putting it here as a reminder)

**Comment by thebestnom** [comment]
(also as a side note, if you put a language after the first ``` the code will be highlighted)

**Comment by thebestnom** [comment]
PR are always welcone!
the only problem I see with your current implemention is that `neo4jElem.type` is a very specific use case (also labels are on the properties?)
any other comment I would like to do on your PR 😁

**Comment by thebestnom** [comment]
I think we can now close this issue?

**Comment by aguinaldoabbj** [comment]
> PR are always welcone!
> the only problem I see with your current implemention is that `neo4jElem.type` is a very specific use case (also labels are on the properties?)
> any other comment I would like to do on your PR

No, in fact I created this function in order to make things more generic (in my opinion), in relation to the old code. 

neo4jElem is just a more generic way to refer to the returns of  buildNodeVisObject and buildEdgeVisObject. 
So I can receive one of them in this function to generate the HTML string for the tooltip. I this case I put both node label and relationship type in the top of the tooltip.
