### ISSUE TITLE
Change font size of relationship caption?

### ISSUE THREAD

**Issue by masonedmison** [neo4j-contrib/neovis.js#177]
I don't see it listed in the docs, but I'll ask just in case... is it possible to change the font size of relationship caption? I tried following the same key-value structure as "nodes" like:
```js
                     "font": {
                                "size":1,
                                "color":"#000000"
                        }  
```

with no luck

**Comment by thebestnom** [comment]
In 1 I don't think so, no... But in 2.0.0 alpha you can by changing font.size

**Comment by masonedmison** [comment]
Very cool, thanks for the quick reply. Is this available via CDN? If not, would you have a suggestion for the easiest way to integrate v2.0.0?

Thanks!

**Comment by thebestnom** [comment]
Ok, here a full migrating guide, https://github.com/neo4j-contrib/neovis.js/blob/2.0.0/MIGRATING.md
thanks for trying!

**Comment by thebestnom** [comment]
also the cdn is now unpkg, look at 2.0.0 README here https://github.com/neo4j-contrib/neovis.js/tree/2.0.0#cdn

**Comment by thebestnom** [comment]
sorry for takling so long to response 😅

**Comment by thebestnom** [comment]
as for you specific case you can add to the configuration
```js
//...
{
  labels: {
    Label: {
      font: {
        size: "level" // a node property
      }
    }
  }
}
```
or using any of the advance configuration to your use!

**Comment by thebestnom** [comment]
Trivial in 2.x
