### ISSUE TITLE
Using NEOVIS_ADVANCED_CONFIG in JSON config files

### ISSUE THREAD

**Issue by aguinaldoabbj** [neo4j-contrib/neovis.js#186]
Dear,

In 1.x.x I could pass the config parameters to my neovis app through JSON without any problems. I could easily get the JSON string and parse it to a JS object and use with neovis.

In 2.0.0 I'm struggling to get the same results using NEOVIS_ADVANCED_CONFIG. Somehow the NEOVIS_ADVANCED_CONFIG part of my JSON is not getting adequately read  by neovis:

```JSON
{
  "container_id": "viz",
  "neo4j": {
    "server_url": "neo4j://localhost:7687",
    "server_user": "",
    "server_password": ""
  },
  "visConfig": {
    "nodes": {
      "shape": "ellipse",
      "color": "red"
    },
    "edges": {
      "arrows": {
        "from": {
          "enabled": false
        },
        "to": {
          "enabled": false
        }
      },
      "color": "red"
    }
  },
  "labels": {
    "Movie": {
      "label": "title",
      "[NeoVis.NEOVIS_ADVANCED_CONFIG]": {
        "static": {
          "color": "blue",
          "shape": "square"
        }
      }
    }
  },
  "relationships": {},
  "initial_cypher": "MATCH p=()-[]-() RETURN p LIMIT 100"
}
```
Only the NEOVIS_ADVANCED_CONFIG parameters do not get read. I think the problem has to do with the parsing process for the "[ ]" syntax inside the object, but I cannot figure it out. How should this JSON be parsed to get a valid JS object for neovis ?

I know that my question has more to do with JS/JSON than with neovis but I hope some experienced JS code could help me out.

**Comment by thebestnom** [comment]
Hmm.... I haven't thought about JSON when I implemented this (same with NEOVIS_DEFAULT_CONFIG) and as far as I know you can't... The problem is that I want to allow to add to existing object without accedently overriding another config...

**Comment by thebestnom** [comment]
The [] parameter is a js operation, json can't by design do it...

**Comment by aguinaldoabbj** [comment]
> The [] parameter is a js operation, json can't by design do it...

Yes, I can get it. I wasn't familiar with that syntax until now. That's the first time I had a problem with JSON -> JS parsing. I believed that the parsing process (JSON.parse) could handle this new ES6 syntax, maybe another parser would do it.

Do you have any ideas on how to overcome this? Basically, my base app is a canvas with a JSON input (text area or load file). The idea is to pass the viz configuration to the app so the app can remain static.

**Comment by thebestnom** [comment]
Worst case scenario just eval 😂
But to be fair that is not a use case I thought about... 
I think maybe break API and change it to not be flat (still alpha) but Im not sure how the configuratiin would look like, any suggestion how you think it should look ?

**Comment by aguinaldoabbj** [comment]
> Worst case scenario just eval 
> But to be fair that is not a use case I thought about...
> I think maybe break API and change it to not be flat (still alpha) but Im not sure how the configuratiin would look like, any suggestion how you think it should look ?

I couldn't get how eval can be used in this problem.

When you say flat you mean that all config is done by a single object?

**Comment by thebestnom** [comment]
> I couldn't get how eval can be used in this problem.

You can eval the "json" that your client write and because json is a legal js code it will just work and as long as you import NeoVis before the eval the brackets will work

> When you say flat you mean that all config is done by a single object?

Currently the object looks like 
```js
{
//...
  "labels": {
    "Label": {
      "color": "node element"
      [ADVANCE_CONFIG]: {
        "cypher": {"value": "cypher"}
      }
    }
    [DEFAULT]: {
      //...
    }
  }
//...
}
```

Non flat means 
```js
{
//...
  "labels": {
    "Label": {
       "mapped": {"color": "node element"}
       "cypher": {"value": "cypher"} 
      }
    }
  }
  "defaultLabelConfig": {
    //...
  }
//...
}
```

**Comment by aguinaldoabbj** [comment]
> > I couldn't get how eval can be used in this problem.
> 
> You can eval the "json" that your client write and because json is a legal js code it will just work and as long as you import NeoVis before the eval the brackets will work
> 
> > When you say flat you mean that all config is done by a single object?
> 
> Currently the object looks like
> 
> ```js
> {
> //...
>   "labels": {
>     "Label": {
>       "color": "node element"
>       [ADVANCE_CONFIG]: {
>         "cypher": {"value": "cypher"}
>       }
>     }
>     [DEFAULT]: {
>       //...
>     }
>   }
> //...
> }
> ```
> 
> Non flat means
> 
> ```js
> {
> //...
>   "labels": {
>     "Label": {
>        "mapped": {"color": "node element"}
>        "cypher": {"value": "cypher"} 
>       }
>     }
>   }
>   "defaultLabelConfig": {
>     //...
>   }
> //...
> }
> ```
I know eval is dangerous, but I give it a try. By replacing JSON.parse to eval, I got the same results. I believe that the problem is that JSON keys are supposed to be enclosed with quotes, both eval and JSON.parse reads  "NeoVis.NEOVIS_ADVANCED_CONFIG]" as an ordinary string.

I think non-flat is more readable and familiar.

**Comment by thebestnom** [comment]
If you are taking the eval, because it's actually a js and not json you should remove the " from the brackets

**Comment by thebestnom** [comment]
And I think that Ill chang it to non flat, do you have a better names for the `mapped` and `defaultLabelConfig`?
Also remember that without eval you can't do functions in the config

**Comment by aguinaldoabbj** [comment]
> And I think that Ill chang it to non flat, do you have a better names for the `mapped` and `defaultLabelConfig`?
> Also remember that without eval you can't do functions in the config

`defaultLabelConfig` is supposed to be out of the scope of labels? Isn't a more general configuration already provided by `visConfig` ?

I believe `neo4-mapped` or maybe `from-neo4j` would be better names.

**Comment by thebestnom** [comment]
defaultLabelConfig is any label not already configured in Label, like a default property mapped and such (also for function it's pretty versetile)

**Comment by aguinaldoabbj** [comment]
I have managed the issue using eval. Although it would be a nice feature to load the config from a JSON file.

**Comment by thebestnom** [comment]
@aguinaldoabbj Ill add that as a feature, that's the right thing to do 😅

**Comment by thebestnom** [comment]
Added on the newest update 😄 will publish it tomorrow!

**Comment by aguinaldoabbj** [comment]
> Added on the newest update smile will publish it tomorrow!

That's good news! How should It be used? I have loaded your latest alpha in my app, disabled my terrible eval-based parser and tried to load the conf from a JSON file. Config is loaded without issue, but the drawing cannot "see" the parameters under "[Neovis.NEOVIS_ADVANCED_CONFIG]"

**Comment by thebestnom** [comment]
Yes, functions can't work that way 😅 there is no way to make that work unless you put default that adds to the output jskn
