### ISSUE TITLE
Implement option to set a shape on a given node label

### ISSUE THREAD

**Issue by SergiAguilo** [neo4j-contrib/neovis.js#187]
Hi,

It would be nice to add the shape option from Vis.js to NeoVis.js for the node labels. So, an implementation could look like this:

```js
var config = {
  ...
  labels: {
    "NodeLabel1": {
      "shape": "square", // All the NodeLabel1 are shown as squares
    },
    "NodeLabel2": {
      "shape": "diamond", // All the NodeLabel2 are shown as diamonds
    },
   }
}
```
Then, you could differentiate the communities of the nodes by the colour, and the node labels by the shape.

Thanks

**Comment by thebestnom** [comment]
You can on 2.0.0
