### ISSUE TITLE
aim: transform Neo4j Record to G6 , stuck at how to skip duplicate nodes

### ISSUE THREAD

**Issue by FrankScarlet** [neo4j-contrib/neovis.js#192]
## Aim

- transform Neo4j [Records](https://neo4j.com/docs/api/javascript-driver/current/class/lib6/record.js~Record.html) to [G6](https://g6.antv.vision/zh/docs/manual/middle/graph) format
- can not figure out how `neovis.js` avoid adding duplicate nodes

## Problem

Example Cypher: `MATCH (b)-[re]-(c) RETURN b, re, c LIMIT 10`

As the case of `neovis`

```javascript
  viz.render();
  console.log(viz._edges);
  console.log(viz._nodes);
// ----
{id: 59085, from: 11496, to: 15468, raw: Relationship, title: "", …}
{id: 59087, from: 18665, to: 15468, raw: Relationship, title: "", ...}
// ----
{id: 15468, raw: Node, value: 1, label: "  ", group: 2, …}
{id: 11496, raw: Node, value: 1, label: "  ", group: 2, …}
{id: 18665, raw: Node, value: 1, label: "  ", group: 2, …}
```

I use [use-neo4j](https://github.com/adam-cowley/use-neo4j) as a React wrapper to access Neo4j. It returns `Neo4jRecord` which is actually `Record` from `Neo4j-Driver` .

```javascript
[Record, Record, Record, Record, Record, Record, Record, Record, Record, Record]
Record.toObject()  // = > {n: Node, re: Relationship, b: Node}
```

Inevitably, I have to skip the duplicate nodes. I know `neovis` works well. I find a similar implementation at [this developer blog](https://neo4j.com/developer-blog/creating-a-neo4j-react-app-with-use-neo4j-hooks/), in which it says

```
Next, we have to convert the returned results from Neo4j which is a list of records into a format that is D3 compatible. 
neovis.js provides a very good guide on how to achieve this and for the most part, we copied their code.
```

**Comment by thebestnom** [comment]
I don't think we actually skip duplicates, if I remember correctly we add everything to vis DataSet by id, so it should just override the last one in case of duplicates (same as using hashmap)

(Neo4j node and relationship comes with unique id)

**Comment by FrankScarlet** [comment]
Thanks for quick reply.

OMG. I think I find the key to the problem, but I am still a little bit confused.

```javascript
_addNode(node) {
this._nodes[node.id] = node;
}
```

Yes, It will override the node with the same id.

As for the `developer blog`, I am not sure whether `Motif` inherit the `neo4j-driver` logic

```javascript
let nodes: Node[] = []; // Node from `neo4j-driver`
let startNode = buildNode(v.start);
nodes.push(startNode); 
```

Maybe the last line is equivalent to ` Node[startNode.identity] = startNode; `

**Comment by FrankScarlet** [comment]
I would complete my  `neo4j-g6-demo` this week.
After that, I will leave the link and close this issue.

**Comment by thebestnom** [comment]
> Thanks for quick reply.
> 
> OMG. I think I find the key to the problem, but I am still a little bit confused.
> 
> ```js
> _addNode(node) {
> this._nodes[node.id] = node;
> }
> ```
> 
> Yes, It will override the node with the same id.
> 
> As for the `developer blog`, I am not sure whether `Motif` inherit the `neo4j-driver` logic
> 
> ```js
> let nodes: Node[] = []; // Node from `neo4j-driver`
> let startNode = buildNode(v.start);
> nodes.push(startNode); 
> ```
> 
> Maybe the last line is equivalent to `Node[startNode.identity] = startNode;`

Nope 😅 it looks like they have the same problem as you (also the code is a little bit different on 2.0.0 but it does the same thing)

**Comment by thebestnom** [comment]
I think that if they use a network library most of them know as well to merge same id

**Comment by thebestnom** [comment]
But in their data it most likely have duplicates

**Comment by FrankScarlet** [comment]
I successfully implement it. The code is [here](https://github.com/FrankScarlet/gdb-neo4j-g6/blob/main/src/neog6.js)

I also combine it with [Graphin](https://graphin.antv.vision/) in the my [react-graphapp](https://github.com/FrankScarlet/gdb-neo4j-g6).

Although it works fine with my local Neo4j Docker instances , it still needs to be developed for richer customization. 

I think the issue is solved. Thanks.
