### ISSUE TITLE
arrows are not shown 

### ISSUE THREAD

**Issue by pg98gh** [neo4j-contrib/neovis.js#193]
I´m using  2.0.0 alpha and followed the new guide on the branch to add arrows, but the relationships still not show the arrows. If i set the limit of the query to 20, the arrows are shown magically, but when i erase the limit, the arrows are not shown anymore. If you want i can post the snippet of my code. 
BR

**Comment by pg98gh** [comment]
Hi sorry, i completely forgot about this issue here. It somehow resolved itself, so the arrows are shown. Howevere the names of the relationships like "Causes" or "Includes" are not displayed on the arrows. can you give me a hint how to show them,too?
this is my code regarding the realtionships: 
`relationships: {{
                                CAUSES:{{
                                    value: true,
                                    label: "name",
                                    [NeoVis.NEOVIS_ADVANCED_CONFIG]:{{
                                        cypher:{{}},
                                        function:{{
                                            title: NeoVis.objectToTitleHtml
                                        }},
                                        static:{{
                                            font:{{
                                                color:"black"
                                            }}
                                        }}
                                    }}                                    
                                }},
                                INCLUDES:{{
                                    label: true,
                                    value: "name",
                                    [NeoVis.NEOVIS_ADVANCED_CONFIG]:{{
                                        cypher:{{}},
                                        function:{{
                                            title: NeoVis.objectToTitleHtml
                                        }},
                                        static:{{
                                            font:{{
                                                color:"black"
                                            }}
                                        }}
                                    }}    
                                }}
                            }},`

**Comment by thebestnom** [comment]
Why the double `{`?

**Comment by thebestnom** [comment]
In 2.0.0 the default is to use propery, so by doing 
```js
{
   //...
   label: true
}
```
you put the `true` property from the relationship and put it onto the arrow, you'll need to change it to the property name where the label should be taken from

**Comment by thebestnom** [comment]
(value is the scale of the edge)

**Comment by pg98gh** [comment]
We are using streamlit to display the graph and we also pass some other variables into the neovis code, therefore the double {}.

thanks for your hint @thebestnom , i will adapt the code accordingly :)

**Comment by thebestnom** [comment]
everything working? can we close this issue?
