### ISSUE TITLE
How to use Neovis.updateWithCypher() ?

### ISSUE THREAD

**Issue by anom-tmu** [neo4j-contrib/neovis.js#194]
Hello,

Thank God, I found this Github. 

I am currently developing a real-time graph visualization using Neovis.JS. But when I create a refresh function, the graph will re-draw a new one. I just want to show what is the graph changes (before and after). 

Until I found "Neovis.updateWithCypher()" function. I try to run this function on a timer script, but the result, the graph is not shown. Can you help me, here is my code :

```html
<script type="text/javascript">
        var viz; 
        var timer = setInterval(myTimer, 1000);
        function myTimer() {    
            viz = new NeoVis.default(config);
            cypher =  "MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m" ; 
            viz.updateWithCypher(cypher);
        }
</script>
```

Thank you. 

Best regards,
Anom

**Comment by thebestnom** [comment]
You have to not create a new neovis instance every clock cycle, 
```html
<script type="text/javascript">
        var viz; 
        var timer = setInterval(myTimer, 1000);
        viz = new NeoVis.default(config);
        function myTimer() {    
            
            cypher =  "MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m" ; 
            viz.updateWithCypher(cypher);
        }
</script>
```
Also it's recommend to first render before calling `updateWithCypher`

**Comment by thebestnom** [comment]
*it's mandatory to first call `render`

**Comment by anom-tmu** [comment]
Wow... That's great.. Thank you very much.

**Comment by thebestnom** [comment]
No problem 😄

**Comment by mojo2go** [comment]
@anom-tmu Can you show your final updated code?  I'm not quite getting it, and want to achieve the same.

**Comment by anom-tmu** [comment]
This is my clean final code, hopefully it help you. Thank you.  Best regards.

`
<!DOCTYPE html>
<html>
    <head>
        <title>Graph Visualization</title>
        <style type="text/css">

            html, body {
                font: 10pt arial;
            }

            #viz{
                width: 1900px;
                height: 900px;
                border: 1px solid lightgray;
                font: 10pt arial;
            }
        </style>

        <script src="https://cdn.neo4jlabs.com/neovis.js/v1.5.0/neovis.js"></script>
    </head>

    <script type="text/javascript">

        var viz;

        function draw() {
            var config = {
                container_id: "viz",
                server_url: "bolt://localhost:7687",
                server_user: "neo4j",
                server_password: "....", //depend on your database
                arrows: true,

                labels: {
                    "NODE": {
                        caption: "name",
                    },                  
                },
                relationships: {
                    "EDGE": {
                        caption: "name",
                        thickness: "weight",
                  },
                initial_cypher: "MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m" 

  
            };

            viz = new NeoVis.default(config);
            viz.render();
        }
    </script>


    <script type="text/javascript">
        //var viz;
        var timer = setInterval(myTimer, 100);
        viz = new NeoVis.default(config);

        function myTimer() {

            cypher =  "MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m" ; 
            viz.updateWithCypher(cypher);
        }
    </script>


    <body onload="draw()">
        <div id="viz"></div>
    </body>
</html>
`

**Comment by thebestnom** [comment]
I suggest changing this to
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Graph Visualization</title>
        <style type="text/css">

            html, body {
                font: 10pt arial;
            }

            #viz{
                width: 1900px;
                height: 900px;
                border: 1px solid lightgray;
                font: 10pt arial;
            }
        </style>

        <script src="https://cdn.neo4jlabs.com/neovis.js/v1.5.0/neovis.js"></script>
    </head>

    <script type="text/javascript">
        var viz;
        function draw() {
            var config = {
                container_id: "viz",
                server_url: "bolt://localhost:7687",
                server_user: "neo4j",
                server_password: "....", //depend on your database
                arrows: true,
                labels: {
                    "NODE": {
                        caption: "name",
                    },                  
                },
                relationships: {
                    "EDGE": {
                        caption: "name",
                        thickness: "weight",
                  },
                initial_cypher: "MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m"   
            };
            viz = new NeoVis.default(config);
            viz.render();
        }
    
        var timer = setInterval(myTimer, 100);
        function myTimer() {
            cypher =  "MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m" ; 
            viz.updateWithCypher(cypher);
        }
    </script>

    <body onload="draw()">
        <div id="viz"></div>
    </body>
</html>

```
You should not create multiple vis instances (by calling new multiple time 😅) on the same div

**Comment by anom-tmu** [comment]
Thank you very much, thats very helpful.. 

Best regards.
