### ISSUE TITLE
caption configuration 

### ISSUE THREAD

**Issue by ESiham** [neo4j-contrib/neovis.js#195]
Hello everyone, 
My configuration is as follows,
 `labels: {
        Resource: {
          caption: "label",
          Size: 2.0,
          Color:"#000000" ,
          community: "community",
        },
       `
for some nodes the caption label is null so by default I got the label 'Resource in my graph, there is a way to define a condition inside caption that say if 'label' is null so choose another attribute for caption ?

**Comment by thebestnom** [comment]
You can on 2.0.0 alpha 😅 not on 1.0.0

**Comment by ESiham** [comment]
What is the syntax 😋 ?

**Comment by thebestnom** [comment]
Here is the migration guide for start https://github.com/neo4j-contrib/neovis.js/blob/2.0.0/MIGRATING.md
And here the docs https://github.com/neo4j-contrib/neovis.js/blob/2.0.0/docs/markdown/interfaces/neovisconfig.md
If you need any more help Ill gladly help 😄
