### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'hasChildNodes')

### ISSUE THREAD

**Issue by Terrific5454** [neo4j-contrib/neovis.js#196]
I use neovis in Vue follow the instruction in README, but the in browser console I got this information:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'hasChildNodes')
at Canvas._create (vis-network.js?7b7c:35548)
    at new Network (vis-network.js?7b7c:47396)
    at eval (neovis-without-dependencies.js?5f6a:1)
    at tryCatch (runtime.js?b391:63)
    at Generator.invoke [as _invoke] (runtime.js?b391:294)
    at Generator.eval [as next] (runtime.js?b391:119)
    at asyncGeneratorStep (asyncToGenerator.js?d164:5)
    at _next (asyncToGenerator.js?d164:27)

I can get the data from Neo4J database, follow the tree I found in vis-network object Canvas  has no container,  I don't know why  and how to fix this bug.
Here are my codes in a vue component file:

```html
<template>
    <div>
        <div id="neo"></div>
    </div>
</template>

<script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>


<script type="text/javascript">
import NeoVis from 'neovis.js'

export default {
    data() {
        return{
            // viz: Object
        }
    },
    mounted() {
        this.draw()
    },
    methods: {
        draw() {
            var config = {
                container_id: "viz",
                server_url: "bolt://3.86.232.254:7687",
                server_user: "neo4j",
                server_password: "plastic-machinery-tractor",
                labels: {
                    "Character": {
                        "caption": "name",
                        "size": "pagerank",
                        "community": "community",
                        "title_properties": [
                            "name",
                            "pagerank"
                        ]
                    }
                },
                relationships: {
                    "INTERACTS": {
                        "thickness": "weight",
                        "caption": false
                    }
                },
                initial_cypher: "MATCH (n)-[r:INTERACTS]->(m) RETURN *"
            };

            var viz = new NeoVis(config);
            viz.render();
            console.log(viz)
        },
    }
}
</script>

<style type="text/css">
    #neo {
        align-content: center;
        width: 900px;
        height: 700px;
        border: 1px solid lightgray;
        font: 22pt arial;
    }
</style>
```

**Comment by thebestnom** [comment]
First of all, thanks for working like a normal person, fun to read normal code for once 😂 (no harm for anyone else) 
Can you send `document.getElementById("viz")` instead of "viz" to container_id? I think it was changed in newer version of vis-network 😅

**Comment by thebestnom** [comment]
Also I will not be available for the next 25 hours, so I'll not see your response until then 😅 good luck for now 😅

**Comment by Terrific5454** [comment]
> First of all, thanks for working like a normal person, fun to read normal code for once 😂 (no harm for anyone else)
> Can you send `document.getElementById("viz")` instead of "viz" to container_id? I think it was changed in newer version of vis-network 😅
Thank for reply! I don't use "viz" named the component tag. I change it to "neo".
And I just send it to container_id. code like 
```
container_id: document.getElementById("neo"),
```

but still got the same bug

**Comment by thebestnom** [comment]
Ill try to help you more when I'll have time, good luck for now 😅

**Comment by Terrific5454** [comment]
> Ill try to help you more when I'll have time, good luck for now 😅

It's okay you get busy

**Comment by Terrific5454** [comment]
God damn it how silly I am! Read your suggestion again, change container_id into my div id, it works!
Thanks a lot! GOD BLESS U

**Comment by thebestnom** [comment]
No problem 😄 good luck

**Comment by honeygy** [comment]
so finally its container_id: "neo"，right?

**Comment by thebestnom** [comment]
containerId and not snakecase
