### ISSUE TITLE
Can we use vis.js with neovis.js?

### ISSUE THREAD

**Issue by ooker777** [neo4j-contrib/neovis.js#205]
For example, if I want to customize the edges by adding [vis.js options](https://visjs.github.io/vis-network/docs/network/edges.html?keywords=color# "vis.js - Edges documentation."), then how should I do this?

```js
var options = {
  edges:{
    arrows: 'to, from',
    color: 'red',
    font: '12px arial #ff0000',
    scaling:{
      label: true,
    },
    shadow: true,
    smooth: true,
  }
}

network.setOptions(options);
```

**Comment by thebestnom** [comment]
You couldn't 😅 unless you want to get nodes and edges from the vis object (which are public getter to the vis DataSet) and edit them directly

**Comment by thebestnom** [comment]
Ohhh, no, I forgot that in 1.x the nodes and edges are a normal object that later gets added as DataSet, so never mind, you can't 😅 you can by using the neovis.network.body.data I think

**Comment by SLMsunrise** [comment]
@thebestnom Hello, can you customize a group of colors for each group of relationships
