### ISSUE TITLE
[2.0.0] migrateFromOldConfig sets serverUser to server_url

### ISSUE THREAD

**Issue by jnichols-pdx** [neo4j-contrib/neovis.js#206]
I was unable to connect to neo4j server after trying to use `migrateFromOldConfig()`  with a working 1.x config on the 2.0.0 alpha.7 hosted on unpkg.
In neo4j console and browser console I receive this error:  "The client is unauthorized due to authentication failure." 

In neovis.ts, line 658 is the following: 
`serverUser: oldNeoVisConfig.server_url,`
Presumably this should set `serverUser` to `oldNeoVisConfig.server_user` instead.

I see that `migrateFromOldConfig()` is deprecated, but until it is removed this might be worth fixing.

**Comment by thebestnom** [comment]
My bad

**Comment by thebestnom** [comment]
Fixed in alpha.8, please test if working 😄

**Comment by jnichols-pdx** [comment]
Tested, confirmed working in alpha.8, many thanks for a quick fix!
