### ISSUE TITLE
Do you intend to open a training course?

### ISSUE THREAD

**Issue by ooker777** [neo4j-contrib/neovis.js#213]
Having asking you several questions that I acknowledge that it may feel uninteresting to you, I start feeling reluctant to ask. Nevertheless, if I don't ask then maybe my progress will be slow. Therefore, how about you open a training course on this library? The target audience maybe who has already known about Neo4j but not quite strong in JavaScript. There are tons of tutorial about JS out there, yes, but having someone to explain JavaScript terminology and syntax **that is tailored to this library** will be much much effiecient. In return, the learners will need to help you build the doc, and answer newcomers' questions. Maybe you should open a Discord server for easier to QA. I think this will be a win-win situation.

Or if you know someone who also has a deep understanding on how it works, and interest in building a community for it, you can ask them too. 

What do you think?

**Comment by dukesun99** [comment]
I will consider making a tutorial and perhaps also a crash course when I have time. But it will definitely not be in near future... There is actually a neo4j official discord server and a visualization topic. So you may try to seek help there.

**Comment by thebestnom** [comment]
Not really, sorry 😅 life too full as is, sorry
