### ISSUE TITLE
How to change the options of neovis' objects in console?

### ISSUE THREAD

**Issue by ooker777** [neo4j-contrib/neovis.js#222]
If I type in the console log an object like `option = {edges: {color: "black" } }` and use `viz.network.setOptions(option)`, then all the edges will turn black except the ones handled by neovis. I see that we have the object `viz._config.relationships.Neo4jEdgeLable`, but I'm not sure how to continue

**Comment by thebestnom** [comment]
You can add that to the visConfig in the config 😅

**Comment by thebestnom** [comment]
Vis takes by default the options from visConfig edges and nodes and it gets overridden by specific nodes and edges if there is config on them, neovis create each node and edge with all the options on neovis relationships and labels config meaning that it will not be overridden by the visConfig options 😅

**Comment by ooker777** [comment]
Is it possible to have methods that change neovis' options?

**Comment by ooker777** [comment]
Hello, do you still have interest in this topic? Is it possible to write a function to override Neovis' config?

**Comment by thebestnom** [comment]
I just don't understand the use case, can you give me an example of what are you trying to do?

**Comment by ooker777** [comment]
For example, I want to color all edges with type `belong` as red, and set its weight by 3. My code would be:
```js
relationships: {
    belong: {
        [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
            function: { 
                title: NeoVis.objectToTitleHtml,
            },
            static: {
                color: "red",
                value: 3
            }
        }
    },
```

Now I want the user to be able to hide it. That means that I need to inject the property `hidden: true`. Is there a way to achieve this?

**Comment by thebestnom** [comment]
Hmm ... You can use reinit and then reload, but that would reset the view...
You can also do viz.nodes to get the nodes than because the nodes are a DataSet you can get them by a property (`viz.nodes.get({group: <labelName>})`) and use https://visjs.github.io/vis-data/data/dataset.html#Data_Manipulation to add hidden true to those by the group

**Comment by ooker777** [comment]
I put `viz.nodes.get({group: "tag_m_legend" })` into the console and get this:

![](https://i.imgur.com/kgcwW3F.png)

I try `viz.nodes.get({group: "tag_m_legend" }).remove(45)` and it yields this error:
```
VM364:1 Uncaught TypeError: viz.nodes.get(...).remove is not a function
    at <anonymous>:1:41
```

I try `var data = new viz.nodes.get({group: "tag_m_legend"})` and it yields this error:
```
neovis.js@2.0.0-alpha.9:2 Uncaught TypeError: Cannot read properties of undefined (reading 'keys')
    at pp (neovis.js@2.0.0-alpha.9:2)
    at new value (neovis.js@2.0.0-alpha.9:2)
    at <anonymous>:1:12
```

**Comment by thebestnom** [comment]
Stop using new for no reason 😅

**Comment by thebestnom** [comment]
Try
```js
viz.nodes.remove(viz.nodes.get(group: "yourGroup"))
```

**Comment by ooker777** [comment]
```js
viz.nodes.remove(viz.nodes.get(group: "tag_m_legend"))
VM381:1 Uncaught SyntaxError: missing ) after argument list
```

**Comment by thebestnom** [comment]
Yeah, forgot to put {}, bit don't just copy random code from the internet, try to understand what I did 😅
```js
viz.nodes.remove(viz.nodes.get({group: "tag_m_legend"}))
```

**Comment by thebestnom** [comment]
Sorry, didn't meant to be mean 😅

I just updated your code to work, you can use updateOnly instead of remove to update properties, but Im not sure how, I think (without testing) it should be written
```js
viz.nodes.updateOnly(
  viz.nodes.get({group: "labelName"}).map(node => ({...node, hidden: true}))
)
```

**Comment by ooker777** [comment]
thanks. It just that in order to notice something wrong you need a decent knowledge of it first.

Anyway, I use that and all the nodes are hidden. I use 
```js
viz.nodes.add(viz.nodes.get({group: "tag_m_legend"}))
```
and nothing returns. There is no error, it's just that the array is empty.

Similarly if I use this for edges instead:
```js
viz.edges.remove(viz.edges.get({group: "Mauthuanvoi"}))
```

Also, it seems that the commands are to remove the data, not to inject properties

**Comment by thebestnom** [comment]
> Sorry, didn't meant to be mean 😅
> 
> I just updated your code to work, you can use updateOnly instead of remove to update properties, but Im not sure how, I think (without testing) it should be written
> 
> ```js
> viz.nodes.updateOnly(
>   viz.nodes.get({group: "labelName"}).map(node => ({...node, hidden: true}))
> )
> ```

Did you try?

**Comment by ooker777** [comment]
wait, how could I miss that? My bad 😅

Anyway, while I can toggle the property now, it still applies to all nodes, not the ones I select. What's more weird is that if I modify it to use with edges, but do it half-bakedly, then it still works. Like this:

```js
viz.edges.updateOnly(
  viz.edges.get({group: "Mauthuanvoi"}).map(node => ({...node, hidden: false})))
```

**Comment by shobhitexe** [comment]
@ooker777 

`viz.nodes.updateOnly(
                  viz.nodes.get().filter(isAdjacent).map(node => ({...node, hidden: true}))
                )`

`function isAdjacent(x) {
                return x.label == "Subject";
            }`

This hides all nodes with label Subject
