### ISSUE TITLE
Customize Node Caption 

### ISSUE THREAD

**Issue by SandyLuXY** [neo4j-contrib/neovis.js#223]
I need to customize the caption of a node, which should be the first element of a list and the list is from a property of the node. The function I write is to pass a node and return the element. 
```js
function getNodeCaption(node){ 
    const names = node["Name"]; 
    // console.log("names type",typeof(names)) 
    return names[0];
}
```
And I set the caption of the node label to be `caption: getNodeCaption` in the config.
When I print the type of the list, I get undefined. I wonder whether there is an example showing how to use a function to customize node caption. Thank you.

**Comment by thebestnom** [comment]
Can you show all the code in the config😅

**Comment by thebestnom** [comment]
I suggest moving to 2.0.0 where we completely broke how it works in 1.x

**Comment by SandyLuXY** [comment]
Here is my full code in config.
```
var neo4j_config = {
    container_id: 'viz',
    server_url: 'neo4j://localhost:7688',
    server_user: 'neo4j',
    server_password: 'password',
    labels: {
        UMLS_concept: {
            caption: getNodeCaption,
            size: 'pagerank',
            title_properties: [],
        },
    },
    relationships: {
        locate_on_chain: {
            thickness: 'weight',
            caption: false,
        },
    },
    initial_cypher:
        'MATCH p = (n1:UMLS_concept)-[r]->(n2:UMLS_concept) RETURN p LIMIT 5',
}
```

**Comment by thebestnom** [comment]
The caption function `node` gets the full raw node from neo4j, which means you need to use `node.properties.Name` to get the names 😄

**Comment by SandyLuXY** [comment]
Success! Thank you so much :-)

**Comment by thebestnom** [comment]
No problem ☺️

**Comment by ooker777** [comment]
> ```js
> function getNodeCaption(node){ 
>     const names = node["Name"]; 
>     // console.log("names type",typeof(names)) 
>     return names[0];
> }
> ```
I'm learning js. If you don't mind, can you explain what `node["Name"]` should do?

**Comment by SandyLuXY** [comment]
`node` is an object, `Name` is a key of the object. `node["Name"]` is the values in the object whose keys are `"Name"`.
