### ISSUE TITLE
Encryption both in config and in URI

### ISSUE THREAD

**Issue by pollomarzo** [neo4j-contrib/neovis.js#227]
I've been trying to use this with an AURA database, but in order to connect I need to use neo4j+s schema (otherwise, `Could not perform discovery.`)

Unfortunately, once it's included in the URI, no value for `encrypted` in config will avoid the ` Encryption/trust can only be configured either through URL or config, not both` Error (I tried `"ENCRYPTION_OFF"` as mentioned in the readme and false).

Weirdly, I only get this error instantiating neovis, while if I create a driver manually no error comes up. 

Any suggestion?

**Comment by thebestnom** [comment]
First of all, neovis.js just pass the configuration to neo4j driver, so if that's a thing I suggest opening an issue there.
But before you do that, try using the latest version directly, if it does work 2.x uses the last version and you can just upgrade 😄

**Comment by thebestnom** [comment]
Oh, I missed the last part 😅 highly suggest trying out 2.x alpha (I think it's mature enough for release, Ill probably release it this week)
It have a newer version of the driver, and you can even pass it an initialized driver 😄

**Comment by RayRemnant** [comment]
Having a hard time figuring it out too, none of the examples are using Neo4J Aura and I'm getting errors even if I set `ENCRYPTION_ON` as suggested down in the README. Can you provide a working example? Thanks!

**Comment by rthennan** [comment]
Working config for Aura by using an unencrypted connection URI and enforcing encryption in the config

        var config = {
            encrypted:"ENCRYPTION_ON",
            trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES",
            container_id: "viz",
            server_url: "neo4j://<dbid>.databases.neo4j.io",
            ...

**Comment by halcyondude** [comment]
What version of the driver are you using?

**Comment by halcyondude** [comment]
> Working config for Aura by using an unencrypted connection URI and enforcing encryption in the config
> 
> ```
>     var config = {
>         encrypted:"ENCRYPTION_ON",
>         trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES",
>         container_id: "viz",
>         server_url: "neo4j://<dbid>.databases.neo4j.io",
>         ...
> ```

Which version of the driver are you using?

**Comment by rthennan** [comment]
> > Working config for Aura by using an unencrypted connection URI and enforcing encryption in the config
> > ```
> >     var config = {
> >         encrypted:"ENCRYPTION_ON",
> >         trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES",
> >         container_id: "viz",
> >         server_url: "neo4j://<dbid>.databases.neo4j.io",
> >         ...
> > ```
> 
> Which version of the driver are you using?
I am using the latest version directly from https://rawgit.com/neo4j-contrib/neovis.js/master/dist/neovis.js
	<script src="https://rawgit.com/neo4j-contrib/neovis.js/master/dist/neovis.js"></script>
	<script type="text/javascript">

**Comment by hunkim** [comment]
@rthennan I still get an error after adding your configuration:

```
Neo4jError: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket `readyState` is: 3
```

Did you see any thing like this?
