### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by Milzi** [neo4j-contrib/neovis.js#231]
Hi, I am trying to use neovis on my nodejs server (I want to run it on the server-side, not the client-side). However, after installing neovis via npm and requiring the module: 

`var NeoVis = require('neovis.js')`

I get the error "ReferenceError: window is not defined" from the file: /usr/src/nodejs/node_modules/neovis.js/dist/neovis.js

Any idea what I can do? It works fine on the client-side via CDN.

**Comment by thebestnom** [comment]
I don't understand just what are you trying to do with this neovis on the server, it is a rendering library 😅

**Comment by Milzi** [comment]
Well I was trying to fetch the graph on the server side and then render it on the client side (like it should be). However, neovis seems to be 100% client side, which I want aware of when I posted this. So you can close this I guess ...

**Comment by thebestnom** [comment]
Hmm... I can add a function that does the data fetching will be in a different function, but than neovis client will be mostly reduntent on the client and you can actually use vis js straight on the client side

**Comment by thebestnom** [comment]
(if you use the method of fetching the cypher first on the server, the problem after that is that cypher properties will need a way to also get fetch and that only happens (currently) on the client side and making sure you fetch all cypher properties first makes no sense 😅)
