### ISSUE TITLE
update to sigma.js v2

### ISSUE THREAD

**Issue by chihpoc** [neo4j-contrib/neovis.js#232]
sigma.js released v2 with webgl support, which can handle much larger graphs. it'd be really nice to update this to sigma.js v2. thanks!

**Comment by thebestnom** [comment]
Changing to sigma.js is not so much updating and more of a overhaul 😅
I can try to add support but I think a new library should be better

**Comment by chihpoc** [comment]
that makes sense. thanks @thebestnom!
