### ISSUE TITLE
Directionality of hierarchical graphs in neovis.js

### ISSUE THREAD

**Issue by dbl94** [neo4j-contrib/neovis.js#234]
I recently started exploring neovis.js for visualisation of my graphs on a website. I was wondering if there is an option to decide on the direction of a hierarchical graph?

I know I can do this...
``` 
hierarchical: true, 
hierarchical_sort_method: "directed" 
```

...to have the graph directed vs hubsize, but I was wondering if there is something I can do to decide the direction itself, I know that in vis.js you can write LR, RL, UD, or DU as in:

```
layout: {
            improvedLayout: true,
            hierarchical: {
                enabled: true,
                sortMethod: 'directed',
                direction: "LR"
            };
```

if it's not possible to do that in neovis, is there then a way to connect some of the vis.js options with the neo4j graph implemented via neovis.js ?

**Comment by dbl94** [comment]
To answer my own question, I have figured it out. I was using the an older 1.x version of neovis where this probably wasn't possible, but with the new 2. version we can fully combine it with vis.js, so we can simply add the layout in visConfig

**Comment by boydkelly** [comment]
> To answer my own question, I have figured it out. I was using the an older 1.x version of neovis where this probably wasn't possible, but with the new 2. version we can fully combine it with vis.js, so we can simply add the layout in visConfig

How is this done?   Example?
