### ISSUE TITLE
Please upgrade Neo4j Driver dependency to 4.4

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neovis.js#235]

**Comment by thebestnom** [comment]
Why? The dependency is ^4.3.4 meaning that it should be at least that, so it support 4.4 by just running upgrade

**Comment by jexp** [comment]
Oh sorry I looked into the `default` master branch, which had 4.1.0

https://github.com/neo4j-contrib/neovis.js/blob/master/package.json#L62

Probably change the default branch on GH to 2.0 ?

**Comment by jexp** [comment]
Someone asked on twitch that they had problems connecting neovis to auradb free (which now runs 4.4)
