### ISSUE TITLE
Relationship tooltips 

### ISSUE THREAD

**Issue by BoniFederico** [neo4j-contrib/neovis.js#246]
Hi! Is it possible to remove the relationship tooltip or decide what to put in it? At the moment I have not found a way to add text to the relationship tooltips, and when I move the mouse hover I see it "empty":
![image](https://user-images.githubusercontent.com/67047565/165115437-2970a38d-34e7-44c9-935b-dd3cd29b6428.png)

**Comment by thebestnom** [comment]
Should be trivial in 2.x, can you test @BoniFederico ?
