### ISSUE TITLE
How to filter by node group doing redraw with the new values. [initial-release]

### ISSUE THREAD

**Issue by Sanchez9aa** [neo4j-contrib/neovis.js#251]
I want to make a list of checkboxes of all the category nodes differentiated by the group property.

When clicking in any checkbox that will appear marked since the graph will be complete I want to go doing redraw to the graph removing all the nodes inside that category.

The problem is that I can't find any function like redraw to repaint the network with the nodes and edges already filtered.

I don't know if this is even possible.

I think that a function like new network that would let me pass the data and the container would be useful and I could render it, but I don't see that this function exists.

Is it possible to do filtering in some way making nodes disappear or redraw?

**Comment by thebestnom** [comment]
Hmm... The easiest I think is to get `.edges` or `.nodes` and filter them (without quering again) they are visjs DataSet and you can read how to manipulate then in vis.js docs (and updating them auto update network)

**Comment by Sanchez9aa** [comment]
I don't know if I have understood correctly, but I am creating the new values of the vis after the filtering with DataSet before rendering, the problem is that I don't know how to render it without doing it with query, because when rendering it uses the query again:


`vis["_data"] = {nodes: visToRender.nodes, edges: visToRender.edges}`
`vis["_nodes"] = visToRender.nodesObject;`
`vis["_edges"] = visToRender.edgesObject;`

The problem is that the render method launches the query, and if I initialize it empty or null I get an error.

Thank you for your response

**Comment by thebestnom** [comment]
Nope, you need to use directly `vis.nodes.update(<data>)`

**Comment by Sanchez9aa** [comment]
This vis you are updating is the one from Neovis? 

I am doing the vis.nodes.update in the registerOnEvent("completed") so that once it has been rendered it is applied but it is not working.

If the update you tell me is the vis data update, how do I apply it to the Neovis one?

**Comment by thebestnom** [comment]
What version are you using?

**Comment by Sanchez9aa** [comment]
Im using this versions:

`"neovis.js": "^1.6.0"`
`"vis-data": "^7.1.4"`
`"vis-network": "^9.1.2"`

How i pass the dataset from vis-data to neovis to update?

**Comment by thebestnom** [comment]
I don't think I understand, the nodes are populated by the render function, from where are you getting the data from?

**Comment by thebestnom** [comment]
You don't need to create a new dataset, you can use the dataset fron vis.nodes directly and update there (and anything you update there will automatically update in the network)

**Comment by thebestnom** [comment]
Don't use update like that 😅 you need to filter the dataset, read the doc there 😅

**Comment by Sanchez9aa** [comment]
You were right, I didn't know that the neovis graph could be modified with the methods of the vis js dataset.

I have updated the code in the repository with the filtering already working, anyway I will put the filtering component below in case someone could use it at some point.

Thank you very much for your help @thebestnom

**Comment by Sanchez9aa** [comment]
```
import React, { useState, useEffect } from 'react'
import cloneDeep from "lodash/cloneDeep"

import { useVisContext } from "../../contexts/VisContext/VisContext";

export const NodeFiltering = () => {

  const { vis } = useVisContext();

  const [groups, setGroups] = useState();
  const [queryHistorial, setQueryHistorial] = useState([]);
  const [cloneVis, setCloneVis] = useState(null);
  
  useEffect(() => {
    if(vis){
      //we push query into queryHistorial
      setQueryHistorial(queryHistorial => [...queryHistorial, vis["_query"]]);
      //if query is not the same that the last query, we clone vis and set it to cloneVis
      if(vis["_query"] !== queryHistorial[queryHistorial.length + 1]){
        const visGraph = cloneDeep(vis);
        setCloneVis(visGraph);
      }
      
      const nodes = Object.values(vis["_nodes"])
      const group = nodes.map(node => {
        return node.group
      })
      const uniqueGroup = [...new Set(group)]
      const uniqueCheckValue = uniqueGroup.map(group => {
        return { value: group, active: true }
      })
      setGroups(uniqueCheckValue)
      console.log(uniqueCheckValue)
    }
  }, [vis])

  useEffect(() => {
    if (vis && groups) {
      //retrieve a filtered subset of the nodes that are in the object uniqueCheckValue and checked is true
      const filteredNodes = cloneVis.nodes.get({
        filter: (node) => {
          return groups.find(group => {
            return group.value === node.group && group.active
          })
        }
      })
      vis.nodes.clear()
      vis.nodes.update(filteredNodes)
    }
  }, [groups])

  const handleCheckNode = (e) => {
    const { value, checked } = e.target;
    const newGroup = groups.map(group => {
      if (group.value === value) {
        return { ...group, active: checked }
      }
      return group
    }
    )
    setGroups(newGroup)
  }

  return (
    <>
      <h2>Filter nodes</h2>
      <div style={{ display: "flex", flexWrap: "wrap", justifyContent: "center", flexDirection: "column" }}>
        {groups && groups.map(node => {
          return (
            <div style={{ display: "flex" }}>
              <input onChange={(e) => handleCheckNode(e)} type="checkbox" name="node" value={node.value} checked={node.active} />
              <label for={node.value}> {node.value}</label>
            </div>
          )
        }
        )}
      </div>
    </>
  )
}```

**Comment by thebestnom** [comment]
No problem 😄
