### ISSUE TITLE
Allow to get the data from a function instead of neo4j cypher

### ISSUE THREAD

**Issue by thebestnom** [neo4j-contrib/neovis.js#265]
Closes https://github.com/neo4j-contrib/neovis.js/issues/188 and https://github.com/neo4j-contrib/neovis.js/issues/185
Also closes https://github.com/neo4j-contrib/neovis.js/issues/35 I think

**Comment by dolleyj** [comment]
Does the recent activity on this indicate this will be a new feature in an upcoming release, or is this ticket consolidation?

Neovis is a candidate of mine, but it's a non-starter if neo4j credentials are stored directly in the javascript. I'd prefer flask to serve the graph data to neovis.

**Comment by dolleyj** [comment]
@thebestnom , thanks. I appreciate the quick response. Cheers

**Comment by thebestnom** [comment]
@dolleyj hey, just published 2.1.0-alpha with the PR code if you want to test, API not final but it's good enough for now

just add to the config `dataFunction` with a iterator function that yields Records and it should work

**Comment by nielsjansendk** [comment]
@thebestnom I am going to give it a shot.

**Comment by thebestnom** [comment]
Make sure to see what I edited in the function 😅

**Comment by nielsjansendk** [comment]
@thebestnom I think maybe there is a problem. It is trying to connect to localhost:7687. However, in my dataFunction, I have specifically instructed it to connect to: 'http://localhost:7474/db/neo4j/tx/commit'; I think maybe it tries to connect to localhost:7687 because I have removed the neo4j part of my config, and then it falls back to the default. But if there is a dataFunction it really shouldn't attempt to talk to directly to neo4j from neovis, right? If that part of the config is missing, it should look for a datafunction and if that is not there it should throw an error of some sort.It is quite possible I didn't program the datafunction properly, but I still think t should never attempt to connect directly to neo4j if it has not been configured to do so. That can lead to confusing errors.

**Comment by thebestnom** [comment]
Yeah, guessed somthing was not right by not testing that in `#init` but it shouldn't make the render to fail, it should just log railing to connect but continuing aniway, no?

**Comment by thebestnom** [comment]
Ok, published 2.1.0-alpha4 with a working exmaple, tested that it works and should be good
https://github.com/neo4j-contrib/neovis.js/blob/add-function-data-input/examples/simple-dataFunction-example.html
https://github.com/neo4j-contrib/neovis.js/blob/add-function-data-input/examples/server/server.ts

**Comment by nielsjansendk** [comment]
@thebestnom I got it to work, but I had to remove the group option from the labels config. This did not work:

```
var config = {
                containerId: "viz",
                labels: {
                    Character: {
                        label: "name",
                        value: "pagerank",
                        group: "community"
                    }
                },
                relationships: {
                    INTERACTS: {
                        value: "weight"
                    }
                },
                dataFunction: test
            };

```

The error message was:

```
caught (in promise) Error: updateGroupOptions: group values in options don't match.
    at Function.value (vis-network.js:24254:22)
    at Function.value (vis-network.js:24372:9)
    at t.value (vis-network.js:23753:16)
    at new t (vis-network.js:23717:40)
    at t.value (vis-network.js:24794:28)
    at t.value (vis-network.js:24734:16)
    at t.value (vis-network.js:24719:5)
    at zj.setData (vis-network.js:43130:58)
    at new zj (vis-network.js:42876:10)
    at TB.GB (neovis.ts:747:137)

```
But when I remove the group option, it works and draws the graph.

**Comment by nielsjansendk** [comment]
@thebestnom Would if be possible to call the dataFunction with a parameter? Such that the cypher code can be specified by the initialCypher config option? Suppose I want to call it with a node id and return something like 'MATCH (n:Node{id: 12345})<-[r:KNOWS]-(m:Node) return n,r,m' I don't want to write a datafunction for every single possible id. So basically, let the dataFunction take initialCypher as input.

**Comment by nielsjansendk** [comment]
@thebestnom Sorry, I realise that wouldn't be a good idea since the server handles cypher. However, I do need to be able to specify a parameter for the url. So the function should be something like:

```
async function *test(node_id) {
	const data = await (await fetch("http://localhost:8080/data/node_id")).json();
	for(const da of data) {
		yield da;
	}
}
```

I just don't know how you would specify a parameter in the config object, since you are not actually calling the function from the config. It would have to be in another part of the config object, right? So neovis can check for it and call the dataFunction with it.

**Comment by nielsjansendk** [comment]
@thebestnom Also, for some weird reason using the dataFunction instead of connection directly to neo4j ignores all styling in config->relationships. It uses the correct styling from config->labels.

**Comment by thebestnom** [comment]
Hmm.. I don't think that's a good idea to try to send parameter, I think a better approach would be to get the IDs you need in the function, somthing like

```ts
async function *test(node_id) {
        
	const data = await (await fetch("http://localhost:8080/data/all_ids")).json();
	for(const id of data) {
                const single_id_data = await (await fetch(`http://localhost:8080/data/${id}`)).json();
		yield single_id_data;
	}
}
```

Or somthing like that

**Comment by thebestnom** [comment]
@nielsjansendk Also looking at the group bug

**Comment by nielsjansendk** [comment]
@thebestnom Not if you have millions and millions of nodes. The server will crash trying to send them all. So that is definitely a no. There needs to be some way to pass information through to the datafunction.

**Comment by nielsjansendk** [comment]
@thebestnom Could this part be changed like this:

```
async #runFunctionDataGetter() {
		let recordCount = 0;
		try {
			const dataBuildPromises: Promise<unknown>[] = [];
			//change here:
			for await (const record of this.#config.dataFunction!(this.#config.dataFunctionParams)) {
				dataBuildPromises.push(this.#createSingleRecord(record));
				recordCount++;
			}
			await Promise.all(dataBuildPromises);
		} catch (error) {
			this.#events.generateEvent(NeoVisEvents.ErrorEvent, { error });
			return;
		}
		this.#completeRun();
		this.#events.generateEvent(NeoVisEvents.CompletionEvent, { recordCount });
	}
```
And then datafunctionParams is an empty hash as a default.

**Comment by nielsjansendk** [comment]
@thebestnom Which means that the datafunction need to check the parameters. Like I could set config.dataFunctionParams.my_parameter: 3 Then in my dataFunction I could look for the value for my_parameter, check that it is valid and send it to the server. If there are options I don't want to send to the server, I need to handle it. If I build a datafunction to get a specific path for a specific node, I need to accept that it can get that kind of path for all nodes. But if I want my users to be able to draw an graph for all possible nodes that is fine. Otherwise, I will have to restrict it in the datafunction. I can't see how that can be abused, but maybe I am missing something.

**Comment by thebestnom** [comment]
That noy what I said, what I meant from outside I meant somthing like
```ts
let dataParameters = {somthing : 5}
let config = {} // normal config
function dataFunction() {
   //Use global dataParameter
}

neovis.render()
//Wait render complete
dataPrameter.somthing = 6
//rerender
```
The second thing I suggested was 
```ts
function dataFunction(parameters) {
}
const config = {}// normal config
neovis.render(undefined, {somthing: 5})// the first is saved for query for now, and {somthing:5 } will be sent to dataFunction
```
For now global works, and I will probably only add the second option, I don't think adding it to the config makes sense as the config should be mostly static unless somthing bug needs change

**Comment by nielsjansendk** [comment]
@thebestnom Ah, I get what you are saying. If I define my datafunction as a nested function inside my draw function, it will have access to the variables that are available inside my draw function. Yeah, that totally works. Now it's just the group thing and the missing styling of the relationships, then it is a very useful feature. Maybe you can update the example to have the datafunction as a nested function inside draw()?

**Comment by thebestnom** [comment]
I'll try later today, also I think Ill do add the parameters, and the nested

Also the group is vis bug, Ill fix that also
And style is probably how I handled deserializing of the neo4j data Ill also fix that

**Comment by nielsjansendk** [comment]
@thebestnom Well, this is weird, integer values come back with as a object like this (from the test dataset):

```
{
"identity": {
"low": 0,
"high": 0
},
"labels": [
"Character"
],
"properties": {
"name": "Addam-Marbrand",
"pagerank": 0.0016587120473340751,
"community": {
"low": 0,
"high": 0
}
},
"elementId": "4:8f1b6617-e9da-4467-b5d3-a7da7a2dd5e7:0"
},
```

This might be the cause of the group bug too.

**Comment by thebestnom** [comment]
Yeah, all identity became serialized to this, and I didn't deseriallized the properties so it's partially my bad
(It's actually neo4j drivers fault as they serialize the objects really badly and my deseriallize should work on the Result structure, but it would be harder on properties unless I add myself a seriallize function but I don't really want to as it wouldn't work on any non js servers

**Comment by nielsjansendk** [comment]
@thebestnom Could you detect if integers are serialized or not? The high/low properties on the identity could be a give-away.

**Comment by thebestnom** [comment]
Im not seriallizing, Im only deseriallzing, and that exactly how I deseriallize the other identities, but deserialling the properties very risky as it can he high and low that someone added himself, there is no way to know what was it seriallized from

**Comment by nielsjansendk** [comment]
@thebestnom So the solution is to use a different driver for the server? I'll work on something and see if it makes a difference.

**Comment by thebestnom** [comment]
Im not think a different driver will help, worst case I add a seriallize function that seriallize the data correctly in a new library, Im also thinking about adding this as a feature to neo4j driver and open a PR there

**Comment by thebestnom** [comment]
Ok, published a new version that fixed most of the bugs, but couldn't repreduce the group bug, Ill try to create small test for it

**Comment by thebestnom** [comment]
Also added more examples

**Comment by nielsjansendk** [comment]
@thebestnom Also, there does not seem to be a 2.1.0-alpha5 tag in this repository.

**Comment by thebestnom** [comment]
> @thebestnom Is is possible to have NeoVis.objectToTitleHtml take arguments? Like this: NeoVis.objectToTitleHtml(node, ['my_id','my_date["year"]["low"]')?

@nielsjansendk yes, just do `(prop) => objectToHtml(prop, config)` instead of using it directly

Yeah, I forgot to push the tag, but I did push it to npm

**Comment by nielsjansendk** [comment]
@thebestnom I'm sorry, I don't get how that works. Suppose this is my configuration:

```
 [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
                function: {
                    title: (node) => NeoVis.objectToTitleHtml(node, ['my_id',
                                                                    'my_date'])
                    }
                    }
```
The date now comes out as an object. Would it be something like:

```
 [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
                function: {
                    title: (node) => NeoVis.objectToTitleHtml(node, ['my_id',
                                                                    objectToHtml('my_date', ['year','month','day'])])
                    }
                    }
```
Where does objectToHtml come from? What if I wanted to call toStandardDate from the neo4j driver on the property, would that be possible?

**Comment by thebestnom** [comment]
Yeah, I said temporal are not supported for now as it means funding and desriallzing more objects and I didn't had time for that, so currently you cant call to string as it's dump object, but you can currently edit the object directly before passing it to objectToHtml like
```ts
// Import neo4j driver
import * as Neo4j from "neo4j-driver";
(node) => {
    const date = node.properties.my_date;
    node.properties.my_date = new Neo4j.types.Date(date.year, date.month, date.day) //I think, check real api, this is educated 😅
    return NeoVis.objectToHtml(node, ['id', 'my_date'])
```

**Comment by nielsjansendk** [comment]
@thebestnom I am getting some weird negative integers. The problem is definitely in the driver, not in neovis, so this is just a heads up. These are very large integers, so it might have something to do with that.

**Comment by thebestnom** [comment]
Hmm... The high, end should what allow the big integers, which means somewhere is broken, the seriallization but might be my deseriallzation

**Comment by nielsjansendk** [comment]
@thebestnom What I did was get the result directly from the driver. It is definitely broken from there, even before it gets to neovis. The value is an integer, but it's not returned correctly. Neither the high or the low value has anything to do with the integer that it's supposed to be.

**Comment by thebestnom** [comment]
The number is too high for js, so they represent it by 2 number, Im pretty sure the low means how many int does it pass or somthing like that, not sure though, not sure also if that a bug on my end Ill test that later

**Comment by thebestnom** [comment]
They did it before BigInt was a thing 😅

**Comment by thebestnom** [comment]
Ok, found out we where working with integer wrong all this time, fixed that
published 2.1.0-alpha7, added tests and deserialize *all* neo4j types including the Time I asked you to do workaround for
I want to close this soon as I think it works correcly, but I do want to know if there is anything that I can do better with naming of the API as I didn't think hard enough for that (if you have better name for `dataFunction` please say so)

**Comment by nielsjansendk** [comment]
@thebestnom I am still getting errors for dates, but not datetimes. I hope that's an easy fix, since they are just a less complex version of datetime.

I think maybe a name with with hook, or maybe dataConnection? I'm not super good with naming things.

**Comment by thebestnom** [comment]
Can you send here how the date look in the json? Maybe I didn't know some fields are optional

**Comment by nielsjansendk** [comment]
@thebestnom sorry, I was wrong, dates actually work, I hadn't reloaded my app with the new version. Everything looks great now.

**Comment by thebestnom** [comment]
Anything more you think the api needs? I think about publishing it in the following days, I think maybe renderWithFunction

**Comment by nielsjansendk** [comment]
@thebestnom I'm sure other people will have different problems than I have, but it works for me. Maybe an example where the dataFunction is defined inside the draw function? To show how the datafunction can get access to variables.

**Comment by thebestnom** [comment]
Have you looked at the new examples? Can you say how can I make it better?

**Comment by nielsjansendk** [comment]
@thebestnom Just a heads up: this can't deal with NaN. By mistake I had some calculations that resulted in NaN for a node property, and the way I found out was that the visualisation would not render. It might be a good idea to throw an error message when a number is a NaN.

**Comment by thebestnom** [comment]
That's a bug 😅 ill fix that it will return NaN string 😅

**Comment by thebestnom** [comment]
published as 2.1.0, I fix the bug on next patch 😅

**Comment by thebestnom** [comment]
@nielsjansendk fixed in https://github.com/neo4j-contrib/neovis.js/pull/349
published in 2.1.1-alpha1 if you want to test before I merge

**Comment by PeterPilley** [comment]
Just discovered this thread, does this mean we can use the output of neo4j result.records.map and then load it into neovis without using cypher directly in neovis?

if so is there a working example?

**Comment by thebestnom** [comment]
Yep, @PeterPilley there is an example with example server in examples directory
