### ISSUE TITLE
not working after upgrade to to 4.10

### ISSUE THREAD

**Issue by abhay8051** [neo4j-contrib/neovis.js#268]
I am unable to use Neovis after upgrading to Neo4j 4.1.0, Crome console throws this error " Neo4jError: The Client is unauthorized due to authentication failure "

The request URL shown it the Network section is ws://localhost:7687/ and Status Code is  101 Switching Protocols
The same user name and password works fine in the Neo4j Browser

If i bypass security in Neo4j config dbms.security.auth_enabled=false , i get below error
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'hasChildNodes')

Edit :
I was able to get solve the Authentication error by, ensuring the correct config for the new version. I messed up between the snake_case and camelCase

I just came across this, The NeoVis.js script is running the below query on the database, which is returning "null" and hence the error "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'hasChildNodes')"

query -  "MATCH (n) WHERE exists(n.pagerank)\n WITH (n), RAND() AS random\n ORDER BY random LIMIT 3000\n OPTIONAL MATCH (n)-[r]-(m)\n WITH n,r,m WHERE exists (n.pagerank) AND exists (m.pagerank) AND exists(m.community)\n RETURN n,r

**Comment by hantongyou** [comment]
The same issue... Testing on Neo4j Desktop version=4.3.3

**Comment by thebestnom** [comment]
@abhay8051  Which version of neovis are you using?

**Comment by hunkim** [comment]
Same here with "ws://localhost:7687/" related error.

**Comment by abhay8051** [comment]
The problem was quite simple and I am quite ashamed :) 
There was a problem with the new conifg definition some of the elements of the config we still old , and hence I think the script defaults to default config and query. In my case it was "initial_cypher" (old) where it should have been "initialCypher" (new). There are changes in the snake_case to camelCase and its not flat anymore there are objects

foll this to the T https://github.com/neo4j-contrib/neovis.js/blob/master/MIGRATING.md
