### ISSUE TITLE
Neovis events

### ISSUE THREAD

**Issue by lalquier** [neo4j-contrib/neovis.js#27]
Since it is not possible to attach events to a vis.js structure before it is rendered, it would be extremely useful if Neo4vis,js could fire a 'vizCompleted' type of event when the render() function is completed.

That would help with adding click() events on the vis.js structure itself or trigger additional customizations on top of the options Neovis.js provides (and it would keep you from having to wrap every single option from vis.js inside Neovi.js).

**Comment by mozark24** [comment]
Agree!

**Comment by iou2much** [comment]
+1

**Comment by tquiroga** [comment]
+1

**Comment by thebestnom** [comment]
You can just get visInstance.network and use vis.js directly

**Comment by nick-trustlab** [comment]
> You can just get visInstance.network and use vis.js directly

@thebestnom can you show an example or explain a bit more what you mean by this?
