### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'hasChildNodes')

### ISSUE THREAD

**Issue by AntonyNitheesh** [neo4j-contrib/neovis.js#274]
![image](https://user-images.githubusercontent.com/91648565/181450787-f1c7180f-7972-4a0c-8a6f-eff7baa679d4.png)

**Comment by thebestnom** [comment]
Check if the test initialQuery returns anything, I need to fix that output in that case 😅

**Comment by AntonyNitheesh** [comment]
I am using Vue (nuxt js) and neovis.js version 2.0.2 for rendering graph but it is showing the above error

**Comment by thebestnom** [comment]
Please send me the config so I can see if somthing there was wrong 😅

**Comment by AntonyNitheesh** [comment]
![image](https://user-images.githubusercontent.com/91648565/181451434-ab3d3c75-0e30-4f39-8ea6-9dd37d7ec94c.png)

**Comment by AntonyNitheesh** [comment]
{
            var config = {
                containerId: 'viz',
                neo4j: {
                    serverUrl: 'bolt://localhost:7687',
                    serverUser: 'neo4j',
                    serverPassword: 'password123',
                    driverConfig: {
                        encrypted: "ENCRYPTION_ON",
                        trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES"
                    },
                },
                labels: {
                    Paper: {
                        caption: 'name',
                    },
                    Author: {
                        caption: 'name',
                    },
                },
                relationships: {
                    added_via_search:{}
                },
                initialCypher: `MATCH p=()-[r:added_via_search]->() RETURN p LIMIT 25`,
            };
            console.log(config.containerId)
            var viz = new NeoVis(config);
            viz.render();
            console.log(viz)
        }

**Comment by thebestnom** [comment]
This is not the config 😅 I mean the config object you sent to `new NeoViz(<this config>)

**Comment by thebestnom** [comment]
Are you sure you have viz div ready before the code runs? (In vue make sure that the functions runs after the render)

**Comment by AntonyNitheesh** [comment]
var config = {
                containerId: 'viz',
                neo4j: {
                    serverUrl: 'bolt://localhost:7687',
                    serverUser: 'neo4j',
                    serverPassword: 'password123',
                    driverConfig: {
                        encrypted: "ENCRYPTION_ON",
                        trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES"
                    },
                },
                labels: {
                    Paper: {
                        caption: 'name',
                    },
                    Author: {
                        caption: 'name',
                    },
                },
                relationships: {
                },
                initialCypher: `MATCH p=()-[r:added_via_search]->() RETURN p LIMIT 25`,
            };

**Comment by thebestnom** [comment]
Does it run after render?

**Comment by AntonyNitheesh** [comment]
Now the graph is rendered but value is not displaying after calling function in a button click

**Comment by AntonyNitheesh** [comment]
![image](https://user-images.githubusercontent.com/91648565/181453426-b6ea4a20-078b-461e-87e0-89660ead8495.png)

**Comment by thebestnom** [comment]
Please send a data sample that you are comfortable with 😅

**Comment by thebestnom** [comment]
Nvm, replace `caption` with `label`

**Comment by AntonyNitheesh** [comment]
After giving label it is working

**Comment by AntonyNitheesh** [comment]
![image](https://user-images.githubusercontent.com/91648565/181455351-6544b7fe-3d0a-462a-85eb-43bb7c970f8c.png)
The graph is not looking nice how to make that look good

**Comment by AntonyNitheesh** [comment]
![image](https://user-images.githubusercontent.com/91648565/181455566-5cd6229d-aeb7-4515-91d5-03f126c6597a.png)
I am expecting a graph like this

**Comment by AntonyNitheesh** [comment]
Thank you🎊🎊🎊
