### ISSUE TITLE
Neo4j Graph Visualization Design issues

### ISSUE THREAD

**Issue by AntonyNitheesh** [neo4j-contrib/neovis.js#275]
My graph is generated using neovis.js and Vue but it doesnot showing the names in nodes and all nodes are in same color.
I need different colors for nodes and labels to be displayed

**Comment by AntonyNitheesh** [comment]
![image](https://user-images.githubusercontent.com/91648565/181460644-e399e330-5e53-49ae-bf0f-274645563ba9.png)

**Comment by thebestnom** [comment]
I really need to add template that asks for config 😅

**Comment by AntonyNitheesh** [comment]
Can u share an example for fixing that

**Comment by thebestnom** [comment]
https://github.com/neo4j-contrib/neovis.js/issues/272

**Comment by AntonyNitheesh** [comment]
labels: {
                    Paper: {
                    label: "title",         
                    [NeoVis.NEOVIS_ADVANCED_CONFIG]:{
                        static:{
                            group:"title"
                        }
                    }
                    },
                    Author: {
                    label: "name",         
                    [NeoVis.NEOVIS_ADVANCED_CONFIG]:{
                        static:{
                            group:"name"
                        }
                    }
                },

**Comment by AntonyNitheesh** [comment]
![image](https://user-images.githubusercontent.com/91648565/181471626-fe3e0300-51a1-451c-9788-361afb111313.png)

**Comment by AntonyNitheesh** [comment]
How can I change the colors of nodes

**Comment by thebestnom** [comment]
Are you inporting NeoVis as *?

**Comment by AntonyNitheesh** [comment]
Noo just Neovis

**Comment by AntonyNitheesh** [comment]
If I import Neovis as * it shows me an error like this...
![image](https://user-images.githubusercontent.com/91648565/181472708-f96725b5-60e9-4398-a9f5-87f7b0558671.png)

**Comment by AntonyNitheesh** [comment]
After importing Neovis as * and changing Neovis(config) to Neovis.Neovis(config) the color changes but the shape also changes to oval but I need a circle shape is that possible.
![image](https://user-images.githubusercontent.com/91648565/181474511-a2663325-61c5-41a0-9316-ed28e8e87057.png)

**Comment by AntonyNitheesh** [comment]
How to change the size and shape of nodes using neovis.js 2.0
