### ISSUE TITLE
Change size of nodes in neovis.js

### ISSUE THREAD

**Issue by AntonyNitheesh** [neo4j-contrib/neovis.js#276]
The graph generated using vue and neovis.js 2.0.2 has a larger node size. I need to reduce the size of the node smaller and the size of all nodes should be same. How can I do that.

**Comment by thebestnom** [comment]
Please read the docs 😅

**Comment by AntonyNitheesh** [comment]
What docs can u share that

**Comment by AntonyNitheesh** [comment]
I dont have any pagerank value without that pagerank can I reduce the size of nodes

**Comment by thebestnom** [comment]
https://neo4j-contrib.github.io/neovis.js/interfaces/LabelConfig.html
https://neo4j-contrib.github.io/neovis.js/interfaces/NeovisConfig.html#visConfig

**Comment by AntonyNitheesh** [comment]
![image](https://user-images.githubusercontent.com/91648565/181500161-4c145b70-f0c1-4687-b004-bb546b958d23.png)
My graph nodes are coming this big😅
