### ISSUE TITLE
Display Graph Perspective using Neovis.js

### ISSUE THREAD

**Issue by AntonyNitheesh** [neo4j-contrib/neovis.js#280]
I am developing a project using Vue Js and neovis.js 2.0.2 for displaying the graph and its label in two columns. The left column should contain the graph and right column should display the distinct nodes in that graph so user can understand the graph. Now the graph is displayed on left column but I can't display the graph nodes in right column. Can you help me how to do that.

I am expecting an output looks like below image...

![image](https://user-images.githubusercontent.com/91648565/181716188-e1d80b60-9d3b-49f0-a3b1-7feb54106bac.png)

**Comment by AntonyNitheesh** [comment]
I used neo4j-driver for getting the labels available in the graph and I have declared the colors as constants. Then I have displayed the graph labels with its corresponding color for reference.

**Comment by iceabing** [comment]
How did you solve this problem?
