### ISSUE TITLE
cannot config labels and edges

### ISSUE THREAD

**Issue by jyyy03** [neo4j-contrib/neovis.js#285]
I tried to add colors for nodes and edges, and none of them work. How to fix it? 
```js
TableNode: {
            label: "tableName",
            value: "tableId",
            borderWidth: "10px",
            },
          ColumnNode: {
            label: "columnName",
            color:"#C0FDFB",
            borderWidth: "10px"
          }
```

**Comment by thebestnom** [comment]
Static value to properties like specific color and such need yo be added in static advance config, please look at the docs or example
In the default config takes the properties from the node itself
