### ISSUE TITLE
Dynamically adding label configs from neo4j server to neovis config

### ISSUE THREAD

**Issue by Niveydhithaa** [neo4j-contrib/neovis.js#290]
### Discussed in https://github.com/neo4j-contrib/neovis.js/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **Niveydhithaa** September 15, 2022</sup>
Hi guys, I have defined a labels config for the existing nodes' labels like 
![image](https://user-images.githubusercontent.com/108443521/190408530-ae8c426b-599f-4802-9706-db9ba743d1dc.png)
. 

TO my requirement, say I have new nodes with a different with a new label in neo4j, then my neovis render shows up just the new nodes empty without its name. I have no idea how to do this. 

Can someone help me out?</div>

**Comment by thebestnom** [comment]
You can use DEFAULT_CONFIG which gives the same config to apl labels that doesn't have a label config

**Comment by Niveydhithaa** [comment]
Hi, thanks for the reply!  So yeah I tried the DEFAULT_CONFIG, but just got the nodes without names with the same color (attached images). 

Have I given the DEFAULT_CONFIG right? 

![image](https://user-images.githubusercontent.com/108443521/190424954-2cf69691-c1a1-409e-b16c-9edbbf9079bd.png)
![image](https://user-images.githubusercontent.com/108443521/190425029-00157ee0-7f93-4689-9eca-6437f7ec5620.png)

**Comment by thebestnom** [comment]
Yeah, I got a problem that you can't use the label from mapped porp, you can still get it in function map and assign the group that way

```js
ADVANCED_CONFIG: {
  functions: {
     group: (node) => node.label[0]
  }
}
```

Or something like thta

(BTW Look at the migration guide, you are using old configs)

**Comment by Niveydhithaa** [comment]
Yeah sure. Ill look into it (the migration thing)

**Comment by Niveydhithaa** [comment]
In the advanced config, the "group" parameter can be changed into something else too right, like in my case can I give it as "name" as i want that to be displayed in the node?

**Comment by thebestnom** [comment]
Of course, but if you only want it to read from props put the `name` outside of the advanced

**Comment by Niveydhithaa** [comment]
Great. Thanks I'll try.

**Comment by Niveydhithaa** [comment]
Also I have another priority issue regarding, whether I can get the NODE ids of all nodes present in my current render? Thanks in

**Comment by thebestnom** [comment]
Umm. Yes, visObject.nodes is  DataSet with all the nodes currently in view (and it's bound to the view so changing it change the view)

**Comment by Niveydhithaa** [comment]
Great. Thanks a lot

**Comment by Niveydhithaa** [comment]
Hi @thebestnom , I tried the above as well (labels config dynamic adding). So basically from a form I try to add new labels. But even after giving the advanced config we discussed here, the nodes created under new label aren't showing up with colors or names.

Is there any possibility for you to share the code along with the data you have? Thanks a lot in advance!

> Yeah, I got a problem that you can't use the label from mapped porp, you can still get it in function map and assign the group that way
> 
> ```js
> ADVANCED_CONFIG: {
>   functions: {
>      group: (node) => node.label[0]
>   }
> }
> ```
> 
> Or something like thta
> 
> (BTW Look at the migration guide, you are using old configs)

**Comment by thebestnom** [comment]
Can you give the config here so I can see? 😅

**Comment by Niveydhithaa** [comment]
Yeah sure

**Comment by Niveydhithaa** [comment]
This is the place where I want to generalize the config for any existing or new label thats created 
![image](https://user-images.githubusercontent.com/108443521/191710052-15380ce8-bebb-4a8e-b43f-55f1141aeb09.png)

**Comment by thebestnom** [comment]
You want to put it in [NeoVis.DEFAULT_LABEL] and not in any_label for it to be used by all labels 😅

**Comment by Niveydhithaa** [comment]
Argh, okay ..

**Comment by Niveydhithaa** [comment]
Yep, tried it too 
![image](https://user-images.githubusercontent.com/108443521/191711745-774a81fa-d446-439f-9785-419bdf426089.png)
No progress, the graph is again without any styles we've applied
![image](https://user-images.githubusercontent.com/108443521/191711861-4b292c02-da03-4782-9d76-68e4a27b9323.png)

**Comment by Niveydhithaa** [comment]
ahh. okay okay got it

**Comment by Niveydhithaa** [comment]
wow. wonderful. thanks a lot, it has applied the config!

**Comment by Niveydhithaa** [comment]
thanks much. Also, is it possible for randomizing colors for each label ?

**Comment by thebestnom** [comment]
Im pretty sure it is kinda rendomized, Im not sure how viz choose color for group

**Comment by Niveydhithaa** [comment]
oh okay, by default its giving smewhat "skyblue" like the below one. and if i give color inside adavnced, it accordingly changes all nodes' colors 
![image](https://user-images.githubusercontent.com/108443521/191714419-c183d430-70da-4546-84cf-272b973fd44d.png)

**Comment by Niveydhithaa** [comment]
but it will be great if it could assign a color on random, like what neo4j does in its display
cause colors aid the sense of discriminating node categories

**Comment by Niveydhithaa** [comment]
maybe if its fine for you, better we can open a new discussion based out of this
