### ISSUE TITLE
Encryption/trust can only be configured either through URL or config, not both

### ISSUE THREAD

**Issue by 4sm-ops** [neo4j-contrib/neovis.js#291]
Hi! 

New BaseNeovisConfig does not have encrypted parameter. But error message somehow presume it is available. 

https://neo4j-contrib.github.io/neovis.js/interfaces/BaseNeovisConfig.html

Encrypted is in OldNeoVisConfig.

https://neo4j-contrib.github.io/neovis.js/interfaces/OldNeoVisConfig.html

What will be the correct setup? Why connection to cloud Aura instance cause this error? Can I get a link to old driver for OldNeoVisConfig, so I can use https://github.com/neo4j-contrib/neovis.js/issues/227 solution? Because with 2.0.2 you cannot use old configuration file.

`function draw() {
var config = {
containerId: "viz",
      neo4j: {
      serverUrl: "neo4j+s://ADDRESS:7687",
      serverUser: "neo4j",
      serverPassword: "PASS"
      },
`

I was able to find 1.5.0 driver, and successfully connect to my database. But I believe I should not use 2 years old driver.

**Comment by thebestnom** [comment]
I don't understand what is your error that you get 😅 it should work regardless

**Comment by thebestnom** [comment]
Ha... The docs are wrong,  https://neo4j.com/docs/api/javascript-driver/current/function/index.html#configuration
Is the correct configuration for driverConfig
You can absolutely use encrypted

**Comment by 4sm-ops** [comment]
Hey @thebestnom 

thank you for the prompt response.
For the record, working config with 2 years old driver. 

<img width="486" alt="Screenshot 2022-09-16 at 15 16 13" src="https://user-images.githubusercontent.com/47212326/190637142-619b1054-50af-4ea4-9e59-612cbadf1329.png">

**Comment by thebestnom** [comment]
Why? 😅

**Comment by thebestnom** [comment]
You can use old config, there is auto migrator function 😅

**Comment by 4sm-ops** [comment]
@thebestnom see above

**Comment by thebestnom** [comment]
This is neo4j driver problem https://github.com/grand-stack/grand-stack-starter/issues/129
This is their reasoning

**Comment by 4sm-ops** [comment]
<img width="995" alt="Screenshot 2022-09-16 at 15 34 12" src="https://user-images.githubusercontent.com/47212326/190640240-db09dd61-2c16-4ca0-85c8-8af35d4f8ecc.png">

neo4j:// - does not work, as `encrypted: "ENCRYPTION_ON",` is no longer supported, as far I understand.

could you please confirm that neovis is no longer compatible with cloud Aura?

**Comment by thebestnom** [comment]
Again, that's not neovis, that's neo4j driver 😅 you can even pass neo4j driver instance to the config in 2.x if you need somthing that missing from the config (there shouldn't be

I thin you need neo4j+s:// to make encryption on

**Comment by 4sm-ops** [comment]
@thebestnom ok, neo4j+s:// does not work,
I think I need to find neo4j driver developers

https://github.com/neo4j-contrib/neovis.js/issues/291#issuecomment-1249305300

**Comment by thebestnom** [comment]
I see why, the default config sends secure off and it gets sent 😅 put ENCRIPTION_ON in the driverConfig, it should work (without neo4j+s

**Comment by 4sm-ops** [comment]
thanks a lot, @thebestnom 

Working config for Cloud Aura:
```
neo4j: {
serverUrl: "neo4j://DBNAME.databases.neo4j.io",
serverUser: "neo4j",
serverPassword: "PASS",
   driverConfig: { 
   encrypted: "ENCRYPTION_ON",
   trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES"
   }				
},
```

**Comment by boydkelly** [comment]
with all the discussion here is the error message not the answer?  

 **either** through **URL** or **config** not **both**

So **either** use:

````
encrypted: "ENCRYPTION_ON",
   trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES"
````

**or**

````
neo4j+s://
````

but **NOT BOTH**

**Comment by Mingaaaaaaa** [comment]
Hi there,I meet the same question and don't konw how to solve:
  https://645e6efe0459690dba85257b--stellar-semifreddo-d2866e.netlify.app/
`



    <title>Neovis.js Simple Example</title>
    <style type="text/css">
        html,
        body {
            font: 16pt arial;
        }

        #viz {
            width: 900px;
            height: 700px;
            border: 1px solid lightgray;
            font: 22pt arial;
            background-color: antiquewhite;
        }
    </style>

    

    <script src="https://unpkg.com/neovis.js@2.0.2"></script>


    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

    <script type="text/javascript">
        // define config car
        // instantiate nodevis object
        // draw

        var viz;

        function draw() {
            var config = {
                containerId: "viz",
                neo4j: {
                    serverUrl: "neo4j://ysjy.alplune.top:7687",
                    serverUser: "xxx",
                    serverPassword: "xxx",
                    driverConfig: {
                    encrypted: "ENCRYPTION_ON",
                    trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES",
                },
                },
              
                labels: {
                    Troll: {
                        caption: "user_key",
                        size: "pagerank",
                        community: "community",
                    },
                },
                relationships: {
                    RETWEETS: {
                        caption: false,
                        thickness: "count",
                    },
                },
                initialCypher: "MATCH (n) RETURN n LIMIT 25"
            };

            viz = new NeoVis.default(config);
            viz.render();
            console.log(viz);

        }
    </script>


<body onload="draw()">
    <div id="viz"></div>

</body>

`
