### ISSUE TITLE
assigning colors randomized to labels present in graph

### ISSUE THREAD

**Issue by Niveydhithaa** [neo4j-contrib/neovis.js#293]
![image](https://user-images.githubusercontent.com/108443521/191716586-143f3240-110f-4ec7-ae9f-0d12006499b2.png)
Say I want this graph through neovis, i have a set of categories or node labels -> but through neovis i wish to see them with different colors, as in neo4j

My config:
![image](https://user-images.githubusercontent.com/108443521/191717534-044071f0-0557-41b9-8e47-c146564106c7.png)

**Comment by Niveydhithaa** [comment]
[initial discussion at [https://github.com/neo4j-contrib/neovis.js/issues/290](url)

**Comment by thebestnom** [comment]
If you put the group to be also mapped by function (you commented that out) the color should be different for each label

**Comment by thebestnom** [comment]
(and remove the static)

**Comment by thebestnom** [comment]
Worse case scenario put color as function and use the label as seed to random color 😅

**Comment by Niveydhithaa** [comment]
Agh. okay, sure. I'll try and let you know

**Comment by Niveydhithaa** [comment]
Thanks for the help @thebestnom !
