### ISSUE TITLE
the graph is taking lot of time to load

### ISSUE THREAD

**Issue by Niveydhithaa** [neo4j-contrib/neovis.js#295]
Hi, so im trying to render 2 graphs. the first one worked perfect, could see the graph in some milliseconds. (has around 20nodes)

But, the other neo4j graph , its taking around 20mins to load (has around 200nodes). Does size matter for rendering?

**Comment by thebestnom** [comment]
I suggest testing to see how much time it take to do the same query in the neo4j desktop, neovis should not be much slower unless you have also a lot of cypher config

**Comment by Niveydhithaa** [comment]
thanks for the suggestion. we have just the config thats required to handle the graph. 
and checked the time it takes (AuraDB cloud is our main neo4j db)
* on neo4j browser : **3 seconds**
* on rendering with neovis (through React webapp) - **1min 10sec**

This was tested with ~190mbps speed. Any way I can reduce this to < 1min ?

**Comment by abhikarsh-gupta** [comment]
> thanks for the suggestion. we have just the config thats required to handle the graph. and checked the time it takes (AuraDB cloud is our main neo4j db)
> 
> * on neo4j browser : **3 seconds**
> * on rendering with neovis (through React webapp) - **1min 10sec**
> 
> This was tested with ~190mbps speed. Any way I can reduce this to < 1min ?

on neo4j browser, it has access to the database on the cloud, consider it like having a backend and front end both on your local machine. 

when we use neovis, we establish a connection and the query runs somewhere else, so query run time, plus time to send data. your network speed is fast so that shouldn't be the issue. but remember the difference will be there..

**Comment by thebestnom** [comment]
How did you test the speed?

The reason is probably that you have a lot of small query of you use cypher config, every cypher config runs 
I suggest to to see in the network panel in devtools to see how the same query hanles because there should be 0 difference between the db web and neovis
