### ISSUE TITLE
The display problem of this figure

### ISSUE THREAD

**Issue by tianchiguaixia** [neo4j-contrib/neovis.js#296]
Why can't I reproduce the effect of the sample with the same code

My picture
![image](https://user-images.githubusercontent.com/29837553/192408099-c74ba5e2-2be3-44da-880e-fcb0bbf19d2f.png)

Sample diagram
![image](https://user-images.githubusercontent.com/29837553/192408194-97da0441-bcc2-4d63-bed2-98ac3a0f0ec9.png)

mycode：

  <html>
<head>
<title>DataViz</title>
<style type="text/css">
#viz {
width: 2000px;
height: 1000px;
}
</style>
<script src="../dist/neovis.js"></script>
</head>
<script
        src="https://unpkg.com/neovis.js@2.0.2"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
        
<script type="text/javascript">
// define config car
// instantiate nodevis object
// draw

var viz;

function draw() {
var config = {
containerId: "viz",
neo4j: {
serverUrl: "bolt://localhost:7687",
serverUser: "",
serverPassword: ""
},
labels: {
Department: {
       label: "name",
       size: "matchs"
},
Disease: {
        label: "name"
}
},
relationships: {
belongs_to: {
value: "weight",
caption: true,
label: "name",
thickness: "score"
}
},
initialCypher: "MATCH p=()-[r:belongs_to]->() RETURN p LIMIT 25"
};

viz = new NeoVis.default(config);
viz.render();
console.log(viz);

}
</script>
<body onload="draw()">
<div id="viz"></div>
</body>
</html>

**Comment by tianchiguaixia** [comment]
How can I set it to achieve the same effect

**Comment by abhikarsh-gupta** [comment]
I was also not able to replicate with my data set, downgraded to v1.4 and everything started working like magic.

**Comment by thebestnom** [comment]
I forgot to color by label in the last release, the pr is open but didn't had time to test @abhikarsh-gupta

**Comment by abhikarsh-gupta** [comment]
> I forgot to color by label in the last release, the pr is open but didn't had time to test @abhikarsh-gupta

Okay. thanks! On a slightly off-topic, my data set has a lot of different labels, is there a way, that I can set some default config for all labels rather than doing it for each label? The node size is way smaller when compared to the labels, so it makes the graph ugly

**Comment by thebestnom** [comment]
@abhikarsh-gupta https://github.com/neo4j-contrib/neovis.js/issues/290
