### ISSUE TITLE
visConfig and [NEOVIS_DEFAULT_CONFIG] not having any effect on the graph. neovis v1.4

### ISSUE THREAD

**Issue by abhikarsh-gupta** [neo4j-contrib/neovis.js#298]
The visConfig object, and the labels section with the default config don't seem to have any effect on the graph. I am trying to tweak how the nodes look and the label size or color, I have around 30 40 labels from a cypher and it is not possible to hardcode the labels as they may change based on cypher.. Any help is highly appreciated. 

P.S. I started with neovis 2.0, but didn't get the relationship names, node colors, arrows anything, so had to downgrade to 1.4 and now everything seems to be smooth. Just need some help with config. 

_Also, do we have a discord server or something where we can collaborate and ask questions? Would be helpful!_
Below is my config.. 
```js
      const config = {
        container_id: "graph-container",
        server_url: "",
        server_user: "",
        server_password: "",
        labels: {
          [NEOVIS_DEFAULT_CONFIG]: { font: "2px arial orange", color: "blue" },
        },
        visConfig: {
          nodes: {
            color: "red",
            font: "8px arial green",
          },
          manipulation: {
            enabled: true,
          },
          interaction: {
            hideNodesOnDrag: true,
          },
        },
        relationships: {
          RESOURCE: {
            caption: false,
            thickness: "1",
          },
        },
        arrows: true,
        heirarchial: true,
        hierarchical_sort_method: "directed",}
```

**Comment by thebestnom** [comment]
It does work on 1.4, make sure to import it correctly and use the latest 1.x (neovis.js and not .ts it's not official)

**Comment by abhikarsh-gupta** [comment]
> It does work on 1.4, make sure to import it correctly and use the latest 1.x (neovis.js and not .ts it's not official)

Thank you very much @thebestnom !!

Yeah, I was importing from the wrong place.
