### ISSUE TITLE
It's slow when i changed cypher

### ISSUE THREAD

**Issue by royhuang813** [neo4j-contrib/neovis.js#299]
Hi, there's a simple demo for this question: [demo](https://codepen.io/royhuang813/pen/OJZrOyB)

just set your config~
```js
   neo4j: {
                serverUrl: "bolt://localhost:7687",  // your local server
                serverUser: "neo4j",  // your user
                serverPassword: "qwer1234",  // your password
            },
```

as you see, it spent about 2s when click `update 250`, in my actual project this would cost more

Is there any optimization plan?  thank you ~

**Comment by royhuang813** [comment]
![image](https://user-images.githubusercontent.com/29953318/195280544-c7a5f41b-eb56-4a74-b1b7-2e036a36e86d.png)

oh~ the promise spend long time, it's sync over all

**Comment by thebestnom** [comment]
Yep 😅 can change it to configurable sync or not, but most likely what slows the sync is the cypher configs

**Comment by royhuang813** [comment]
btw, I found that the cause of the slowdown was more because of vis.js itself, like [vis.js basic demo](https://codepen.io/royhuang813/pen/GRdzNBE)

I will keep to find the optimization scheme of vis.js, of course maybe vis.js is not good at handling large amounts of data as d3~

thanks again~

**Comment by thebestnom** [comment]
Yep, d3 is much faster, but it way less intuitive, and neovis started as a way to quickly set it up and customize for your website as quickly as possible, maybe one day Ill create a fork with d3 or somthing that uses wengpu or somthing
