### ISSUE TITLE
How to set the label for each relationship

### ISSUE THREAD

**Issue by Markaeov** [neo4j-contrib/neovis.js#300]
I set the label for each relationship by this, but it dosen't work.
```js
nan: {
[NeoVis.NEOVIS_ADVANCED_CONFIG]: {
    static: {
        label: "nan",
    },
}},
```

**Comment by thebestnom** [comment]
What you did is to add label to each nan relationship, it should work for that, did you mean somthing else?

**Comment by Markaeov** [comment]
But it didn’t actually work, the label was not displayed on the edge.&nbsp;
I tried this
nan: {
&nbsp;label: ‘nan’
}
it didn’t work too.

发自我的iPhone


------------------ Original ------------------
From: thebestnom ***@***.***&gt;
Date: Tue,Oct 18,2022 10:28 PM
To: neo4j-contrib/neovis.js ***@***.***&gt;
Cc: Markaeov ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [neo4j-contrib/neovis.js] How to set the label for eachrelationship (Issue #300)

**Comment by thebestnom** [comment]
I couldn't understand, what is the relationship types?

**Comment by Markaeov** [comment]
I want to display the relationship type on the edge. What can I do to implement it? In the old version, we can set ‘caption’ to true to&nbsp;implement it. I don’t know how to do it in the current version&nbsp;. The attempts just mentioned do not take effect.



发自我的iPhone


------------------ Original ------------------
From: thebestnom ***@***.***&gt;
Date: Tue,Oct 18,2022 10:57 PM
To: neo4j-contrib/neovis.js ***@***.***&gt;
Cc: Markaeov ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [neo4j-contrib/neovis.js] How to set the label for eachrelationship (Issue #300)





 
I couldn't understand, what is the relationship types?

**Comment by thebestnom** [comment]
```js
{
   labels: {
      [neovis.NEOVIS_DEFAULT_CONFIG]: {
          [neovis.NEOVIS_ADVANCED_CONFIG]: {
            functions: {
               label: (rel) => rel.type[0]
            }
        }
     }
}
```
it should look somthing like thta

**Comment by Markaeov** [comment]
`relationships: {
            [NeoVis.NEOVIS_DEFAULT_CONFIG]: {
              [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
                function: {
                  label: (r) => {
                    return r.type[0];
                  }
                }
              }
            },
            nan: {},
            anatomy_disease: {},
            disease_drug: {},
            disease_symptom: {},
            disease_treatment: {},
            drug_ade: {},
            drug_amount: {},
            drug_frequency: {},
            drug_method: {},
            reason_disease: {},
            reason_symptom: {},
            test_disease: {},
            test_reason: {},
            treatment_ade: {},
          },
`
![image](https://user-images.githubusercontent.com/58562766/196629395-b3868b58-dd28-4070-93de-3e580d686330.png)

I don't know what went wrong, but it still can't show the label on the edge.

**Comment by thebestnom** [comment]
Any update?

**Comment by Markaeov** [comment]
I seem to find the reason. When I use CDN to import neovis.js, it can display the label on the edge. When I use npm to install neovis.js and use it as module in my vue project, some properties cannot be set, but others can be set. This confused me.

example (when use it as module)
```
labels: {
    entity_1: { 
        label: "text",  // text is a property of entity_1.    take effect
        group: "label" //  group is a property of entity_1.    take effect
     },
},
relationships: {
    [NeoVis.NEOVIS_DEFAULT_CONFIG]: {
        [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
            function: {
              label: (rel) => rel.type // not take effect
             }
         }
      },
    relationship_1: {
        arrows: { // not take effect
            to: {enabled: true}
        },
        text: 'prop', // prop is a property of relationship_1.    take effect
    }
}，
visConfig: { // all take effect in visConfig
    edges: {
        arrows: {
          to: {enabled: true}
        },  
        smooth: false,
    },
    nodes: {
        shape: 'dot',
    }
},
```

**Comment by thebestnom** [comment]
Well, arrow is static so you need to add it as static config in advanced, in the current way it try to take true prop from the relationship
Try `rel.raw.type`
If it's not working mind debugging to check if it gets to the function? 😅

**Comment by thebestnom** [comment]
Also make sure to import NEOVIS_DEFAULT_CONFIG correctly

**Comment by thebestnom** [comment]
Can you update? Did it work for you? Can I close the issue?

**Comment by Markaeov** [comment]
OK, thank you for your help, I have solved my problems by importing neovis.js via CDN.
But label still can't be displayed on edge when I import neovis.js as a module and I didn't find the reason.

**Comment by thebestnom** [comment]
There shouldn't be any different importing from cdn from importing by
`import * as NeoVis from "neovis.js`
Just saying 😅

**Comment by thebestnom** [comment]
(and then youll have to do new NeoVis.default(config) again)

**Comment by Markaeov** [comment]
I don't think they should be any different, too. That's why I'm confused for a long time.

**Comment by thebestnom** [comment]
Im not sure which cdn do you use, but the cdn in the readme gives the 2.x version which should work the same as the npn (because it's actually just access the npm) 😅

**Comment by Markaeov** [comment]
Wow!!! I solved it from importing by `import * as NeoVis from "neovis.js"`.
I imported it by `import NeoVis from "neovis.js"` before and it caused my problem.
Thank you!!!

**Comment by thebestnom** [comment]
Yep, I suggest that you learn about how import work in js in the meantime, good luck!
