### ISSUE TITLE
Using neovis.js in vue project

### ISSUE THREAD

**Issue by Markaeov** [neo4j-contrib/neovis.js#301]
In my vue project,
`viz = new NeoVis.default(this.config);`
This code will generate [Vue Warn] and TypeError
![image](https://user-images.githubusercontent.com/58562766/196721740-656707a3-ba06-48be-b461-62e7d1ac8397.png)
How can I solve it?

**Comment by thebestnom** [comment]
How do you import the neoviss.js?

**Comment by thebestnom** [comment]
Yep, if you import by `import NeoVis from "neovis.js"` you are already importing the default import so you need to use it by `const viz = new NeoVis(config)` and not NeoVis.default(config)
