### ISSUE TITLE
How to set the attributes of a specific node independently

### ISSUE THREAD

**Issue by Markaeov** [neo4j-contrib/neovis.js#303]
How to set the attributes of a specific node independently

**Comment by Markaeov** [comment]
（after render）

**Comment by thebestnom** [comment]
There is a getter to the nodes, `viz.nodes` which is a vis DataSet binded to the network, any change in the nodes will be reflected in thr network, so you can do somthing like (not remembering the specific api) 
```js
viz.nodes.update(id:5, label: "new label")
```

**Comment by Markaeov** [comment]
Thx!



发自我的iPhone


------------------ Original ------------------
From: thebestnom ***@***.***&gt;
Date: Fri,Oct 21,2022 8:25 PM
To: neo4j-contrib/neovis.js ***@***.***&gt;
Cc: Markaeov ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [neo4j-contrib/neovis.js] How to set the attributes of a specificnode independently (Issue #303)

**Comment by thebestnom** [comment]
here is the DataSet docs: https://visjs.github.io/vis-data/data/dataset.html
