### ISSUE TITLE
How to limit the max count of neighbors?

### ISSUE THREAD

**Issue by xixibaobei** [neo4j-contrib/neovis.js#304]
In neo4j browsers, I can set limitation of max neighbors, avoding crowed cluster. any similar functions in neovis?
![image](https://user-images.githubusercontent.com/101168060/198202335-6df4351a-19dd-42b0-99cd-bb2b8a81f881.png)

**Comment by thebestnom** [comment]
You can't do it configuration wise, but you can just put `LIMIT`in the cypher
