### ISSUE TITLE
how to use neovis in uniapp?

### ISSUE THREAD

**Issue by yyl31500** [neo4j-contrib/neovis.js#306]
uniapp 不支持dom的getElementById,how to use neovis in uniapp?

**Comment by thebestnom** [comment]
What is uniapp? 😅

**Comment by yyl31500** [comment]
> What is uniapp? 😅
https://uniapp.dcloud.net.cn/ ，是开发小程序的一个框架。不支持document.getElementById，这种有什么好的处理方式推荐吗？

**Comment by thebestnom** [comment]
Are you sure it's not? It's run by vue.js, which has `created` hook, maybe you can put it there, also not knowing chinese so had to google translate everything in chinese 😅

**Comment by thebestnom** [comment]
Also you can use ref ( https://vuejs.org/guide/essentials/template-refs.html ) instead, just make sure to run after the component mounted

**Comment by yyl31500** [comment]
> Are you sure it's not? It's run by vue.js, which has `created` hook, maybe you can put it there, also not knowing chinese so had to google translate everything in chinese 😅

**Comment by yyl31500** [comment]
yes,because i wanted to run it in Wechat Mini Program,and it does not support document

**Comment by yyl31500** [comment]
> I don't know how wechat works and couldn't found by googling it easily, but if vue refs doesn't work for you I'm not sure if it cam be helped 😅 you have to be able to somehow get the ref to the component in a way that canvas will be added there

ok,thank you very much
