### ISSUE TITLE
Highlight node, its neighbor nodes and edges, with greying the rest

### ISSUE THREAD

**Issue by xixibaobei** [neo4j-contrib/neovis.js#308]
From my personal perspective,  functions in neovis.js are inherented from vis.js, is it possible to do highlighting and greying like the vis.js example.
 https://visjs.github.io/vis-network/examples/network/exampleApplications/neighbourhoodHighlight.html.

**Comment by thebestnom** [comment]
They are not inherited, neovis just creates vis.js network config that "extends" vis.js config but actually you have full control on the network after it get rendered by `visObject.network` and you can set any vis config in the visConfig or label or relationship in the config
