### ISSUE TITLE
Set node colour based on node property value

### ISSUE THREAD

**Issue by dhruv-ahuja** [neo4j-contrib/neovis.js#309]
Hello, I want to set the colour of individual nodes based on specific properties. So if say, there is a node `User` and I want to set the colour as white if the `user_status` property is is True else I want to set it as black. 
How can I do this? 

Any help would be much appreciated. Thank you.

**Comment by thebestnom** [comment]
Use functions in advance_config, you can do it as
```ts
[NeoVis.NEOVIS_ADVANCED_CONFIG]: {
   function: {
       color: node => node.raw.user_status ? "white" : "black"
   }
}
```

**Comment by dhruv-ahuja** [comment]
Hello, sorry for the super late response. I had to focus on the backend of the project and have only now picked up the graph visualization part again. 

this is my sample config that I am using to try and visualize things, the graph works correctly when i remove the line, it does not render when I try out your solution: 

`  function draw() {
    var config = {
      containerId: "viz",
      neo4j: {
        serverUrl: "neo4j://<db_id>.databases.neo4j.io",
        serverUser: username,
        serverPassword: password,
        driverConfig: {
          encrypted: "ENCRYPTION_ON",
          trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES",
        },
      },

      labels: {
        User: {
          label: "user_first_name",
          community: "user_first_name",
          group: "community",

          [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
            function: {
             // **this causes error!**
              color: (node) => (node.raw.user_first_name ? "white" : "black"),
            },
          },
        },
      },

      initialCypher: "MATCH (u:User) RETURN u;",
    };

    viz = new NeoVis.default(config);
    viz.render();
  }
`

**Comment by thebestnom** [comment]
Try console log node to see wgat properties does it have

**Comment by dhruv-ahuja** [comment]
Got it, the node object looks like this:
```js
{
    "identity": 0,
    "labels": [
        "User"
    ],
    "properties": {
        "user_email": "test@gmail.com",
        "user_id": "999"
    }
}
```

was able to set the colour using 
`color: (node) => node.properties.user_email === "test@gmail.com" ? "white": "black"`
