### ISSUE TITLE
Groups are not assigned to nodes

### ISSUE THREAD

**Issue by Nkaskaj** [neo4j-contrib/neovis.js#311]
I am trying to assign group for nodes, but I can't get it working.
![image](https://user-images.githubusercontent.com/12019437/204568007-dada723c-bd91-45ff-a752-cce457941d0e.png)

**Comment by Nkaskaj** [comment]
got it working with this:
`Clovek: {
                    label: "name",
                    [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
                        static: {
                        group: "clovek"
                        }
                    }
                },
`
but I think, that's not how it's supossed to work.

**Comment by thebestnom** [comment]
Nope, that's exactly how it should work, I have a PR that I haven't tested yet that auto adds group per label config but I didn't had the time to test it yet but it should work
