### ISSUE TITLE
How to show label of each edge

### ISSUE THREAD

**Issue by XinyeYang** [neo4j-contrib/neovis.js#315]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/61686580/209445442-68b7ac4b-a572-4956-9830-e2fb81cc703a.png">

```js
visConfig: {
                    nodes: {
                        shape: 'dot',
                        size: 20
                    },
                    edges: {
                        arrows: {
                            to: { enabled: true }
                        },
                        selectionWidth: 10,  //边选中时的宽度
                        color: {
                            color: "#00ffff",
                            highlight: "#ff0000",
                        },
                        label: "xxxx"
                    },
                    physics: {
                        // barnesHut: {
                        //     "avoidOverlap": 1
                        // },
                        repulsion: {
                            "nodeDistance": 100
                        }
                    },
                },
```

I set a fixed attribute “xxxx” for the edge label 😭
Can you show me a detailed case about the way of setting edge labels dynamically?

**Comment by thebestnom** [comment]
Please check examples, if you are still stuck please reach again, but I won't have time to help in the current time 😅

**Comment by liyiche** [comment]
Hi dear,I am facing the same problem. Have you found a solution yet?

**Comment by liyiche** [comment]
Sorry to bother you again!  Fixed code according to your guide, but edge label still missing. I'm confused about this.
Here is my code and chart. The Neo4j dashboard query response and table structure are as follows.
Looking forward to your reply. 比心.
```
    async draw(){
      let viz;
      var config = {
        containerId: "viz",
        neo4j: {
          serverUrl: neo4j_url,
          serverUser: neo4j_user,
          serverPassword: neo4j_password,
        },
        visConfig: {
	   nodes: {
            shape: 'circle',
            size: 20,
            font: {
              color: '#343434',
              size: 14, // px
            }
	},
	edges: {
	  arrows: {
	    to: {enabled: true}
	     }
	   }
	},
        labels: {
            Movie:{
              label: "title"
            },
            Person:{
              label: "name"
            }
        },
        relationships: {
          ACTED_IN: {
            value: 'weight',
            [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
              static: {
                label: "ACTED_IN_AA",     //content on edge
                color: "#674ea7",   //edge color
                font: {
                  "background": "none",
                  "strokeWidth": "0",
                  "size": 20,
                  "color": "#f9dc73"  //font color on edge
                }
              }
            }
          }
        },

        initialCypher: "MATCH p=(:Person {name: 'Tom Hanks'})-[r:ACTED_IN]->(k) RETURN p,r,k"
      };

      viz = new NeoVis(config);
      viz.render();
    }
```

<img width="1364" alt="neo4j dashboard" src="https://user-images.githubusercontent.com/16568471/228822693-143a4007-c262-4347-9742-254c38f0b16d.png">
<img width="1372" alt="neo4j response table" src="https://user-images.githubusercontent.com/16568471/228822713-2161f403-fb94-446b-8220-04f10c9c2b48.png">
<img width="660" alt="vuepage" src="https://user-images.githubusercontent.com/16568471/228822728-5fb4ef6f-74aa-45af-82fb-bf314adc598a.png">

**Comment by XinyeYang** [comment]
I'm not sure where the problem is. Do you use the latest **neovis.js** version(2.0.2)?
I use ```viz = new NeoVis.default(config);``` before ```render()```.
I can't run with```new NeoVis(config);```.

Here is my page.
![](https://user-images.githubusercontent.com/61686580/228844848-df085924-8cbd-4a34-b0e2-233458422864.png)

**Comment by XinyeYang** [comment]
I have tried your code and it does work and I guess the problem is **initialCypher**.
I use ```MATCH (n:标签)-[r]->(m) RETURN * LIMIT 100```
You can have a try.
![](https://user-images.githubusercontent.com/61686580/228848236-a9ab4eee-56b5-41d5-8bb4-d66fb4daec3c.png)
![](https://user-images.githubusercontent.com/61686580/228848454-497ff72c-499e-417b-adde-3ca0af8bfa41.png)
