### ISSUE TITLE
need help regarding graph visualization

### ISSUE THREAD

**Issue by dhruv-ahuja** [neo4j-contrib/neovis.js#318]
Hi, I have a couple of doubts on a few aspects of the graph visualization part, please help me out-
How can I implement an image for a particular node type? Say `User` nodes on my graph. Inside labels, 
```js
User: {
          label: "user_first_name",
          community: "user_first_name",
          group: "community",

          shape: "image",
          image:
            "https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg",
            ...}
``` 
doing this does not work, any guidance regarding this would be really appreciated, I have been looking at vis.js' docs but not really grasping how this can be done. 

Also, how can I set border colours for the nodes? 
I tried creating a `color` property inside the User node and setting a `border: "red"` value there but nothing happened.

Any help would be much appreciated, I have been trying several things to get these things working but to little success.

**Comment by thebestnom** [comment]
The shape and image are static, so it should be in advanced config under static

**Comment by dhruv-ahuja** [comment]
thanks a lot, I have been able to successfully load the images. 
Is there a guide or proper reference where I can find all these options and refer to them? that would be a big help.

**Comment by thebestnom** [comment]
https://neo4j-contrib.github.io/neovis.js/interfaces/NeovisConfig.html
This is currently the best doc, I should really write a better doc 😅

**Comment by thebestnom** [comment]
All the other options come from vis.js https://visjs.github.io/vis-network/docs/network/nodes.html or edges.html
