### ISSUE TITLE
Is there a npm package for this?

### ISSUE THREAD

**Issue by chiraggw15** [neo4j-contrib/neovis.js#32]
I can't find a npm package for this. I wanted to use this library in a react application. I tried various methods to use the script tag, nothing seemed to work.

**Comment by debugpoint136** [comment]
Here with same issue. Please let me know if there is a way to use with React app

**Comment by chiraggw15** [comment]
Write script tag in head tag of index.html (main root). And then use viz variable by writing window.viz. it should work. Worked for me.

**Comment by debugpoint136** [comment]
That helped! Thanks @chiraggw15 !!!

**Comment by jackdbd** [comment]
I did a similar thing.

In `public/index.html`:

```html
<script src="https://cdn.rawgit.com/neo4j-contrib/neovis.js/master/dist/neovis.js"></script>
<script>window.Neovis = Neovis</script>
```

And in my component:

```js
this.vis = new window.NeoVis.default(config);
```

Not sure how to test it though...

**Comment by ssmails** [comment]
Tried the above but get below error at this line. Any idea what I am missing ?
<script>window.Neovis = Neovis</script>

Uncaught ReferenceError: Neovis is not defined
    at (index):19
(anonymous) @ (index):19

**Comment by jackdbd** [comment]
Maybe you forgot to load neovis.js?

Be sure to place this:

```
<script src="https://cdn.rawgit.com/neo4j-contrib/neovis.js/master/dist/neovis.js"></script>
```

before this:

```
<script>window.Neovis = Neovis</script>
```

I'll try to update the README of my example repo. Open me an issue if you have any trouble in making it work. :smiley:

**Comment by suchetaswabhav** [comment]
Hi jackdbd,

I am getting error -

        Property 'NeoVis' does not exist on type 'Window' 

on entering it like this in my index.html file of my angular2 app

<script src="https://cdn.rawgit.com/neo4j-contrib/neovis.js/master/dist/neovis.js"></script>
<script>window.Neovis = Neovis</script>

code in angular app -

 this.viz = new window.NeoVis.default(config);

**Comment by sai-velamuri** [comment]
I'm getting the same error too. Not sure how to resolve.

**Comment by brunoenribeiro** [comment]
Got it to work. I checked the neovis.js package, and in the `index.d.ts` file I found this:

```
declare class Neovis {
    constructor(config: INeovisConfig);
    render(): void;
    clearNetwork(): void;
    registerOnEvent(eventType:string, handler: (event: any) => void);
    reinit(config: INeovisConfig): void;
    reload(): void;
    stabilize(): void;
    renderWithCypher(query: string): void;
}
export default Neovis;
```
As you can see, the constructor is declared right inside `class Neovis`, instead of in `Neovis.default`.
So this works:
1) Run `npm i --save neovis.js`;
2) On your component, code: `import Neovis from 'neovis.js'` (it can be any name you want, the package export the "Neovis" object by default);
3) Code your config file and:
```
var viz = new Neovis(config); // without .default
viz.render();
```

**Comment by thebestnom** [comment]
Almost always `.default` is what you'll get if you do `require(package)` or `import * as package from 'package'`, so if you do `import package from 'package'` you shouldn't use .default
