### ISSUE TITLE
Help: How can I pass JSON object instead of relying on query for rendering graph?

### ISSUE THREAD

**Issue by dhruv-ahuja** [neo4j-contrib/neovis.js#322]
Hi, is there anyway that I can pass in a JSON object and render that using NeoVis, rather than getting data using an `initialQuery`? 
If so, is there any documentation that I can refer to or any example code? 
Any help would be much appreciated.

**Comment by thebestnom** [comment]
Currently you can't 😅 you can try working with vis.js directly

But it is in the roadmap and PR are welcome 😄

**Comment by thebestnom** [comment]
Duplicate: https://github.com/neo4j-contrib/neovis.js/issues/265
