### ISSUE TITLE
how neovis.js connect   to the remote server.

### ISSUE THREAD

**Issue by SongQMei** [neo4j-contrib/neovis.js#33]
hi, I used neovis.js to show my neo4j databse.  when I put the database  on local computer, it's work well. but when I put the database to the remote server. It can't work. the server is works good, I used the code below to connect to it. but I config the neovis.js, it's not work. can you help me, Is there other config I wanted to do? thank you very much.
      var bolturl = "bolt://210.XX.57.XX:7687";
        var username = "neo4j";
        var password = "psw";
        var authToken = neo4j.v1.auth.basic(username, password);
        console.log(authToken);
        driver = neo4j.v1.driver(bolturl, authToken, {encrypted:false});
        session = driver.session();        
        return session.run(statement, parameters)

**Comment by johnymontana** [comment]
Do you get any error message in the console when using the remote server credentials?

**Comment by Rezu** [comment]
Howdy I would ask this same question for connecting to GrapheneDB. This is using Node.js framework

In my index.ejs file I have the var config = { set up as such pointing to my GranpheneDB instance...

 container_id: "viz",
             server_url: "bolt://blah.dbs.graphenedb.com:12345",
             server_user: "user",
             server_password: "pword"

and it doesn't seem to work where encrypted: "ENCRYPTION_ON" or OFF, but it's on for this inquiry.

I can make this work on my local if I point to my local neo4j db:7474, but if I can only view this on my local, why wouldn't I just use Neo4j browser?

In what scenario does neovis work when pointing to a remote Neo4j db?

Thanks!

**Comment by thebestnom** [comment]
GrapheneDB doesn't work as it doesn't allow browser connect
