### ISSUE TITLE
Feature request: make Neo4j connection optional

### ISSUE THREAD

**Issue by JeroenDeDauw** [neo4j-contrib/neovis.js#331]
Is it possible to use this library without connecting to Neo4j?

Context: I have a bunch of data already obtained from Neo4j to display, and the client should not have access to Neo4j.

**Comment by thebestnom** [comment]
Not currently 😅

**Comment by thebestnom** [comment]
Duplicate: https://github.com/neo4j-contrib/neovis.js/issues/265
