### ISSUE TITLE
I was confused when I used your code.Do you have the document of option setting instead of some demos?

### ISSUE THREAD

**Issue by liliComing** [neo4j-contrib/neovis.js#334]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
Before sending unsolicited pull requests, please open a feature request to discuss your proposal.

If you have questions on usage, please ask on [the Discussion Forum](https://community.neo4j.com) instead of creating an issue here.

## Feature description (Mandatory)

Add any considered drawbacks.

## Considered alternatives

Maybe there is something in the project that could be reused?

## How this feature can improve the project?

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by thebestnom** [comment]
There us a d.ts file https://github.com/neo4j-contrib/neovis.js/blob/master/dist/neovis.d.ts
And api docs with explainations https://neo4j-contrib.github.io/neovis.js/modules.html
If there any way for making them clearer don't mind commenting here

**Comment by thebestnom** [comment]
https://neo4j-contrib.github.io/neovis.js/interfaces/LabelConfig.html
For the label config

**Comment by liliComing** [comment]
However,exg.it didn’t work when I setting color.I use neovis in vite and init render successfully.please help me check out.



发自我的iPhone


------------------ Original ------------------
From: thebestnom ***@***.***&gt;
Date: Wed,Apr 5,2023 3:39 PM
To: neo4j-contrib/neovis.js ***@***.***&gt;
Cc: liliComing ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [neo4j-contrib/neovis.js] I was confused when I used your code.Doyou have the document of option setting instead of some demos? (Issue #334)





 
https://neo4j-contrib.github.io/neovis.js/interfaces/LabelConfig.html
 For the label config

**Comment by thebestnom** [comment]
Can you please send your code or part of it so I could see how you are using it and what are you trying to do?

**Comment by liliComing** [comment]
ok
import NeoVis from 'neovis.js/dist/neovis.js';
export default function () {
&nbsp; &nbsp; const executeCypher2 = (scenicList)=&gt;{
&nbsp; &nbsp; &nbsp; &nbsp; let neoViz;
&nbsp; &nbsp; &nbsp; &nbsp; const config = {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; containerId: "chart4",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; neo4j: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; serverUrl: "bolt://localhost:7687",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; serverUser: "neo4j",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; serverPassword: "qazwsxedc",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; labels: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; scenic:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label: "scenic_name",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; color:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; background:"red"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; user:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"name",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; color:"pink"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; follow_people:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"follow_name",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; tag:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"tag"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; fan:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"fan_name"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; relax_type:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"relax_type"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; scenic_type1:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"category1"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; scenic_type2:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"category2"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; scenic_type3:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"category3"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; city:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"city_name"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; core_type:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"core_type"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; province:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"province_name"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; rank:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"scenic_rank"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; scenic_rank:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"scenic_rank"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; relationships: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; INTERACTS: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; value: "weight"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; initialCypher: "MATCH p=(n:scenic)-[*..5]-&gt;(t) &nbsp;where n.scenic_name='湖心亭' or n.scenic_name='华顶国家森林公园' or n.scenic_name='灵峰景区' and ALL(n1 in nodes(p) where size([n2 in nodes(p) where id(n1) = id(n2)])=1 ) &nbsp;RETURN p"
&nbsp; &nbsp; &nbsp; &nbsp; };

&nbsp; &nbsp; &nbsp; &nbsp; neoViz = new NeoVis(config);
&nbsp; &nbsp; &nbsp; &nbsp; console.log(neoViz._config)
&nbsp; &nbsp; &nbsp; &nbsp; neoViz.render();
&nbsp; &nbsp; }
&nbsp; &nbsp; return { executeCypher2 }
}






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neo4j-contrib/neovis.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月5日(星期三) 下午4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neo4j-contrib/neovis.js] I was confused when I used your code.Do you have the document of option setting instead of some demos? (Issue #334)





 
Can you please send your code or part of it so I could see how you are using it and what are you trying to do?

**Comment by thebestnom** [comment]
Mind fixing the comment? It's unreadable

**Comment by liliComing** [comment]
Ok,I simplify the code&nbsp;
// import the Neovis
import NeoVis from 'neovis.js/dist/neovis.js';
export default function () {
&nbsp; &nbsp; // package graph render as a function
&nbsp; &nbsp; const executeCypher = ()=&gt;{
&nbsp; &nbsp; &nbsp; &nbsp; let neoViz;
&nbsp; &nbsp; &nbsp; &nbsp; //config setting
&nbsp; &nbsp; &nbsp; &nbsp; const config = {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // dom id
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; containerId: "chart4",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // neo4j server
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; neo4j: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; serverUrl: "bolt://localhost:7687",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; serverUser: "neo4j",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; serverPassword: "qazwsxedc",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; labels: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // "scenic" is one of Entity type
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; scenic:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // show scenic name
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label: "scenic_name",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // this prop dosen't work
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; color:"red"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; user:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"name",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; color:"pink"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; follow_people:{
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; label:"follow_name",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; relationships: {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; // use CQL to get the data ,which means abstractly the path about nodes and their multi-layer Neighbor node 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; initialCypher: "MATCH p=(n:scenic)-[*..5]-&gt;(t) &nbsp;where n.scenic_name='湖心亭' or n.scenic_name='华顶国家森林公园' or n.scenic_name='灵峰景区' and ALL(n1 in nodes(p) where size([n2 in nodes(p) where id(n1) = id(n2)])=1 ) &nbsp;RETURN p"
&nbsp; &nbsp; &nbsp; &nbsp; };

&nbsp; &nbsp; &nbsp; &nbsp; neoViz = new NeoVis(config);
&nbsp; &nbsp; &nbsp; &nbsp; neoViz.render();
&nbsp; &nbsp; }
&nbsp; &nbsp; return { executeCypher }
}




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neo4j-contrib/neovis.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月5日(星期三) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [neo4j-contrib/neovis.js] I was confused when I used your code.Do you have the document of option setting instead of some demos? (Issue #334)





 
Mind fixing the comment? It's unreadable

**Comment by thebestnom** [comment]
The problem is not the code, the problem is that your comment have weird chars &nbsp; &nbsp; &nbsp; &nbsp; neoViz = new NeoVis(config);
&nbsp; &nbsp; &nbsp; &nbsp; neoViz.render();
&nbsp; &nbsp; }
&nbsp; &nbsp; return { executeCypher }
}

**Comment by liliComing** [comment]
> 

sorry,i just used the email System to send the code ,now switch the github
`// import the Neovis
import NeoVis from 'neovis.js/dist/neovis.js';
export default function () {
    // package graph render as a function
    const executeCypher = ()=>{
        let neoViz;
        //config setting
        const config = {
            // dom id
            containerId: "chart4",
            // neo4j server
            neo4j: {
                serverUrl: "bolt://localhost:7687",
                serverUser: "neo4j",
                serverPassword: "qazwsxedc",
            },
            labels: {
                // "scenic" is one of Entity type
              scenic:{
                // show scenic name
                label: "scenic_name",
                // this prop dosen't work
                color:"red"
              },
              user:{
                label:"name",
                color:"pink"
              },
              follow_people:{
                label:"follow_name",
              }
              
            },
            relationships: {
            },
            // use CQL to get the data ,which means abstractly the path about nodes and their multi-layer Neighbor node 
            initialCypher: "MATCH p=(n:scenic)-[*..5]->(t)  where n.scenic_name='湖心亭' or n.scenic_name='华顶国家森林公园' or n.scenic_name='灵峰景区' and ALL(n1 in nodes(p) where size([n2 in nodes(p) where id(n1) = id(n2)])=1 )  RETURN p"
        };

        neoViz = new NeoVis(config);
        neoViz.render();
    }
    return { executeCypher }
}`

**Comment by liliComing** [comment]
> The problem is not the code, the problem is that your comment have weird chars

sorry, i just used the email system to send,now switch the github
```
// import the Neovis
import NeoVis from 'neovis.js/dist/neovis.js';
export default function () {
    // package graph render as a function
    const executeCypher = ()=>{
        let neoViz;
        //config setting
        const config = {
            // dom id
            containerId: "chart4",
            // neo4j server
            neo4j: {
                serverUrl: "bolt://localhost:7687",
                serverUser: "neo4j",
                serverPassword: "qazwsxedc",
            },
            labels: {
                // "scenic" is one of Entity type
              scenic:{
                // show scenic name
                label: "scenic_name",
                // this prop dosen't work
                color:"red"
              },
              user:{
                label:"name",
                color:"pink"
              },
              follow_people:{
                label:"follow_name",
              }
              
            },
            relationships: {
            },
            // use CQL to get the data ,which means abstractly the path about nodes and their multi-layer Neighbor node 
            initialCypher: "MATCH p=(n:scenic)-[*..5]->(t)  where n.scenic_name='湖心亭' or n.scenic_name='华顶国家森林公园' or n.scenic_name='灵峰景区' and ALL(n1 in nodes(p) where size([n2 in nodes(p) where id(n1) = id(n2)])=1 )  RETURN p"
        };

        neoViz = new NeoVis(config);
        neoViz.render();
    }
    return { executeCypher }
}
```

**Comment by thebestnom** [comment]
You are trying to put static color in property mapping config, what you did tries to copy "red" property from the neo4j node to the graph node, what you want is advance config with static
Add
```js
import NeoVis, {NEOVIS_ADVANCED_CONFIG} from 'neovis.js/dist/neovis.js';
//...
scenic: {
  // Properties config
  [NEOVIS_ADVANCED_CONFIG]: {
   static: {
    color: "red"
   }
  }
 // More configs
```

**Comment by liliComing** [comment]
> You are trying to put static color in property mapping config, what you did tries to copy "red" property from the neo4j node to the graph node, what you want is advance config with static Add
> 
> ```js
> import NeoVis, {NEOVIS_ADVANCED_CONFIG} from 'neovis.js/dist/neovis.js';
> //...
> scenic: {
>   // Properties config
>   [NEOVIS_ADVANCED_CONFIG]: {
>    static: {
>     color: "red"
>    }
>   }
>  // More configs
> ```

nagative saddly,the console reports
```
neo4jToGraph.js?t=1680685662641:16 Uncaught (in promise) ReferenceError: NEOVIS_ADVANCED_CONFIG is not defined
    at executeCypher2 (neo4jToGraph.js?t=1680685662641:16:22)
    at ECharts2.<anonymous> (UserPaint.vue:309:5)
```
not NEOVIS_ADVANCED_CONFIG but NeoVis.NEOVIS_ADVANCED_CONFIG .However this modification also didn't work
```
 scenic: {
                    label: "scenic_name",
                    [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
                        static: {
                            color: "red"
                        }
                    }
                },
```

**Comment by liliComing** [comment]
> You are trying to put static color in property mapping config, what you did tries to copy "red" property from the neo4j node to the graph node, what you want is advance config with static Add
> 
> ```js
> import NeoVis, {NEOVIS_ADVANCED_CONFIG} from 'neovis.js/dist/neovis.js';
> //...
> scenic: {
>   // Properties config
>   [NEOVIS_ADVANCED_CONFIG]: {
>    static: {
>     color: "red"
>    }
>   }
>  // More configs
> ```

I try it again. It dose work and than you very much,will give you a star. So, the line's color also do like that?

**Comment by thebestnom** [comment]
Yep, If the doc from doesn't help you don't hesitate to open a discussion 😄
