### ISSUE TITLE
How to display labels outside its node?

### ISSUE THREAD

**Issue by aizaz-sparkai** [neo4j-contrib/neovis.js#335]
I'm currently using neovis.js 2.0.2 version for my react app.

According to [initial docs](https://github.com/neo4j-contrib/neovis.js) label display out side of its node like:

<img width="317" alt="Screenshot 2023-04-05 at 3 04 59 PM" src="https://user-images.githubusercontent.com/111278961/230049638-ec7647e1-3eee-457a-a31a-c87ae0680cc1.png">

but In my react app it display like:

<img width="713" alt="Screenshot 2023-04-05 at 3 06 34 PM" src="https://user-images.githubusercontent.com/111278961/230049983-56ce91a6-ead3-4c42-83d9-4a0673e6461d.png">

I want to display labels outside of its node.

Please guide me the right direction.

**Comment by thebestnom** [comment]
I think that need to change from circle to dot, but Im not sure, check in vis docs

**Comment by aizaz-sparkai** [comment]
you are the real hero.

**Comment by aizaz-sparkai** [comment]
Can we show relation label also?

**Comment by thebestnom** [comment]
Yep, same way you do for node

**Comment by aizaz-sparkai** [comment]
currently I don't have properties in relations and I want to display type of relationship as label of relationship
