### ISSUE TITLE
Need to send a wss instead of ws in my project

### ISSUE THREAD

**Issue by Mingaaaaaaa** [neo4j-contrib/neovis.js#340]
I deploy my web on https (mini  program required) 
but I find out that the graph can't render cause it send  a wss request to my server.
![image](https://user-images.githubusercontent.com/96101748/233790503-680d29c5-2864-43fd-82c1-8d87e5582338.png)

**Comment by thebestnom** [comment]
Neovis does support wss, you'll need to use bolt+s though instead of bolt

**Comment by Mingaaaaaaa** [comment]
But when  I tried bolt+s or neo4j+s  it became another error.  
And I find a similar issue  on https://github.com/grand-stack/grand-stack-starter/issues/129.
 still don't know how to solve this .
<img width="870" alt="截屏2023-04-23 21 44 13" src="https://user-images.githubusercontent.com/96101748/233843788-b5b0d540-753e-487d-9d41-8f862ebdf670.png">

**Comment by thebestnom** [comment]
https://github.com/neo4j-contrib/neovis.js/issues/291

**Comment by thebestnom** [comment]
Can I close?

**Comment by Mingaaaaaaa** [comment]
maybe not,  I try the config but still send a ws request
![image](https://user-images.githubusercontent.com/96101748/233851708-82b78b49-ab23-44c3-b830-9459e2679b28.png)

**Comment by thebestnom** [comment]
Can you send a censored config as text here?

**Comment by thebestnom** [comment]
Ohh you're using the config incorrectly, not `server_url`, serverUrl unless you are using 1.x for some reason

**Comment by thebestnom** [comment]
Same with user and password

**Comment by Mingaaaaaaa** [comment]
sry  I did use the 1.4.0  cause I fork an old repo
config below

  const config = {
            container_id: 'id1',
            server_url: "neo4j://xxxxx",
            server_user: "xxxx",
            server_password: "xxxxx",
            driverConfig: { 
                 encrypted: "ENCRYPTION_ON",
                trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES"
                },
            labels: {
                Troll: {
                    caption: "user_key",
                    size: "pagerank",
                    community: "community",
                },
            },
            relationships: {
                RETWEETS: {
                    caption: false,
                    thickness: "count",
                },
            },
            initial_cypher: "MATCH (n) RETURN n LIMIT 25"
        };

**Comment by thebestnom** [comment]
If you're using old 1.x you need to put encrypted and trust flat on the config instead of inside driverConfig
```js
  const config = {
            container_id: 'id1',
            server_url: "neo4j://xxxxx",
            server_user: "xxxx",
            server_password: "xxxxx",
            
            encrypted: "ENCRYPTION_ON",
            trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES"
            
            labels: {
                Troll: {
                    caption: "user_key",
                    size: "pagerank",
                    community: "community",
                },
            },
            relationships: {
                RETWEETS: {
                    caption: false,
                    thickness: "count",
                },
            },
            initial_cypher: "MATCH (n) RETURN n LIMIT 25"
        };
```
though I do suggest using 2.x as it is much more flexible and can do pretty much everything vis network can do

**Comment by Mingaaaaaaa** [comment]
wss work!  
but 
  Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1682267644588, routers=[], readers=[], writers=[]]
  is this mean my server  need to config something?

**Comment by thebestnom** [comment]
I actually never saw this bug 😅

**Comment by thebestnom** [comment]
https://github.com/neo4j/neo4j-javascript-driver/issues/516
Probably this?

**Comment by thebestnom** [comment]
Anyway, closing as complete, good luck! 😄
