### ISSUE TITLE
Different situations on different browser

### ISSUE THREAD

**Issue by Mingaaaaaaa** [neo4j-contrib/neovis.js#344]
Hi,I use your Neovis.js Simple Example HTML to link my neo4j database on my server.And I deploy it on [here](https://ysjy.alplune.top/index.html). and [here](https://stellar-semifreddo-d2866e.netlify.app/)  
But I found out that my Edge、Safari and Firefox work successfully. but in Chrome or on my phone It can't work 
```js
{
neo4j: {
                    serverUrl: "neo4j://ysjy.alplune.top",
                    serverUser: "aaaa",
                    serverPassword: "aaaa",
                    driverConfig: {
                    encrypted: "ENCRYPTION_ON",
                    trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES",
                },
                }
}
```

 What I want to do is visit this web via web-view on phone. But It will console the same error :
 

> neovis.js@2.0.2:2 Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1683984347375, routers=[], readers=[], writers=[]]

**Comment by thebestnom** [comment]
Hey, this is a neo4j driver problem
https://aura.support.neo4j.com/hc/en-us/articles/5290730835859--Could-not-perform-discovery-No-routing-servers-available-while-connecting-to-an-AuraDB-instance-from-Neo4j-browser
Good luck!

**Comment by Mingaaaaaaa** [comment]
I read this, and I still don't know   why . I test my 443、7687 and 7474 port ,all fine .  
And I can connect  on Edge and Firefox ,so it should't be fail login ,
but the fact that I can't connect on Chrome is confusing me cause it also supported browser.😫

**Comment by thebestnom** [comment]
Try connecting from the neo4j website, and see if it's different

**Comment by Mingaaaaaaa** [comment]
<img width="718" alt="image" src="https://github.com/neo4j-contrib/neovis.js/assets/96101748/cc97de4e-94bb-4f9f-bf55-370fb38dc95e">

How can I figure it out. ?  I can connect on my own [web](https://ysjy.alplune.top:7473)

**Comment by thebestnom** [comment]
Try opening dev tools and see if the network tab gives more information, more than that I have no idea 😅 that's a driver bug, not neovis.js one

**Comment by Mingaaaaaaa** [comment]
ok, just now I  try connect on edge and firefox also success,but fail in chrome...

![image](https://github.com/neo4j-contrib/neovis.js/assets/96101748/650b1825-81e3-455f-9d6d-09d5dd8edd35)
![image](https://github.com/neo4j-contrib/neovis.js/assets/96101748/8396e80a-cf7a-410c-a2c7-ab77cc04ae09)

**Comment by thebestnom** [comment]
https://github.com/neo4j/neo4j-javascript-driver/issues/516
Maybe this will help?
