### ISSUE TITLE
Changing database name in config

### ISSUE THREAD

**Issue by NudistBeaaach** [neo4j-contrib/neovis.js#359]
Hi, is it possible to specify a different database name from the default one of neo4j (with the name "neo4j") in the config ? I did not find example of how to do this.

**Comment by thebestnom** [comment]
https://neo4j-contrib.github.io/neovis.js/interfaces/BaseNeovisConfig.html#serverDatabase

**Comment by NudistBeaaach** [comment]
Thx a lot, that was obvious!

**Comment by thebestnom** [comment]
No problem 😄
