### ISSUE TITLE
Expose all vis.js config settings for override

### ISSUE THREAD

**Issue by johnymontana** [neo4j-contrib/neovis.js#36]
Originally neovis.js was designed to hide the complexity of configuring the styling and physics of the visualization. However, it has become apparent that many users would like the flexibility to override the underlying vis.js configuration for styling and physics. Therefore we should expose *all* vis.js config options as optional overrides, rather than manually mapping and exposing a few config options.

**Comment by HashRocketSyntax** [comment]
what might be more valuable is a driver for vis.js that let’s you easily run queries and work with results

**Comment by HashRocketSyntax** [comment]
^ so if neovis was a plugin that sat on top of visjs rather than trying to duplicate visjs

**Comment by suchetaswabhav** [comment]
Hey Johny,

I want images instead of the circular structures. How to do that in Neovis.js ?

**Comment by suchetaswabhav** [comment]
> Originally neovis.js was designed to hide the complexity of configuring the styling and physics of the visualization. However, it has become apparent that many users would like the flexibility to override the underlying vis.js configuration for styling and physics. Therefore we should expose _all_ vis.js config options as optional overrides, rather than manually mapping and exposing a few config options.


@johnymontana  Great Thought !  When can we start implementing !

**Comment by jexp** [comment]
I really like this idea, just pondering the implementation.

I guess something like a deep object-merge onto the defaults would make most sense.

So you can either override entries or add new entries or remove  them with values being `null`

https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge

**Comment by vmauricio93** [comment]
We need this!!

**Comment by thebestnom** [comment]
It doesn't sound very hard, I would suggest opening a pr because I don't think anyone would take actions, and it shouldn't be hard

**Comment by vincentkollebolle** [comment]
Up up :) this is good good stufff :)

**Comment by vincentkollebolle** [comment]
Before it, is there a workaround to be abble to do that ?

**Comment by kaveUW** [comment]
So has this been done? It wouldn't appear so.
In the dist > neovis.js file, I've edited options as follows, but only some options/properties work i.e. shape: 'ellipse' works color.background: 'red' does not, what do I need to do for the following to be true...
`let options = 
                    nodes: {
                        shape: 'ellipse',
                        color: {
                        background: 'red',
                        border: 'black'
                        }
`

**Comment by kaveUW** [comment]
Can anyone point me to the original vis.js Configuration Options? They used to live here... http://visjs.org/docs/timeline/#Configuration_Options

**Comment by danielsilva2017** [comment]
I solved  this by adding a immutable node by instance/community which its coordinates are always base on the center of the network, which I think is what in the vis js example is done

**Comment by dukesun99** [comment]
> It doesn't sound very hard, I would suggest opening a pr because I don't think anyone would take actions, and it shouldn't be hard

Have you done that? I checked the issues and found this one. I feel it is a good idea to have it.

**Comment by thebestnom** [comment]
@dukesun99 I don't have time for that, my company stopped using neovis and but Im still trying to help because I think this library can be really good if someone would take ownership over this

**Comment by thebestnom** [comment]
well, I trying using neo4j sandbox but the only version that I get there is 3.5.0, and there everything work as intended, Ill try later on newer Neo4j

**Comment by ninjakx** [comment]
@thebestnom : I see there are some features that need to be implemented. If you don't mind can I ask you why your company stopped using neovis? 

I created cluster and coloured them differently by assigning different labels to them (this was the only solution to keep the colour different so wrote a cypher query for that)
![Screenshot from 2021-03-04 16-20-34](https://user-images.githubusercontent.com/29797787/109953130-a6b32980-7d05-11eb-8ea4-c40cb483ebfc.png)

This is what I get in *neovis*:
![Screenshot 2021-03-04 16:24:07](https://user-images.githubusercontent.com/29797787/109953462-19240980-7d06-11eb-941b-57983c5247c3.png)

Is there any better solution apart from `neovis` and `popotojs` which have got almost same functionality as that of neo4j browser graph visualization?

**Comment by thebestnom** [comment]
My company stopped using neo4j as a whole because we moved project

On 2.0.0 alpha you can give full vis configuration (I do admit I need testers 😅)

**Comment by ninjakx** [comment]
@thebestnom : Thanks.
![Screenshot 2021-03-04 17:10:09](https://user-images.githubusercontent.com/29797787/109959256-3c05ec00-7d0d-11eb-8d81-c3073950b512.png)

Finally ended up with this on configuration.

Do you have any idea how to collapse and expand the nodes?

**Comment by thebestnom** [comment]
You mean by double click?

**Comment by ninjakx** [comment]
Yes


> You mean by double click?

Yes

**Comment by thebestnom** [comment]
Umm how Im not sure about how to collapse, but you can expand by listening on double click and use updateWithCypher with the id

**Comment by thebestnom** [comment]
Currently there is no out of the box solution 😅

**Comment by ninjakx** [comment]
> Currently there is no out of the box solution

You mean that hover thing right?

**Comment by thebestnom** [comment]
No, I mean for expanding/collapsing on doubleclick

**Comment by thebestnom** [comment]
What do you mean by hover?

**Comment by ninjakx** [comment]
look at this: https://eisman.github.io/neo4jd3/

![Screenshot from 2021-03-04 17-27-22](https://user-images.githubusercontent.com/29797787/109960528-e6324380-7d0e-11eb-8764-5cd98ca55e00.png)

**Comment by thebestnom** [comment]
Oh, yes, there is no out of the box but you can implement that by listening to hover 😅

Sorry...

**Comment by thebestnom** [comment]
2.x now out!
