### ISSUE TITLE
Export static assets

### ISSUE THREAD

**Issue by zekenie** [neo4j-contrib/neovis.js#361]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. 
Before sending unsolicited pull requests, please open a feature request to discuss your proposal.

If you have questions on usage, please ask on [the Discussion Forum](https://community.neo4j.com) instead of creating an issue here.

## Feature description (Mandatory)

I'd love to share some visualizations on github pages with my company, is it possible to save data from neo4j into some format and run neovis off of that?

Add any considered drawbacks.

## Considered alternatives

Screenshots?

Maybe there is something in the project that could be reused?

## How this feature can improve the project?

If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by zekenie** [comment]
it seems like in that example a node server is hitting neo4j. I'm looking for something that could be statically exported without any server and hosted as just files, how tricky would that be?

**Comment by thebestnom** [comment]
https://github.com/neo4j-contrib/neovis.js/blob/master/examples/simple-dataFunction-example.html

**Comment by thebestnom** [comment]
Look at this example closely, one of them doesn't fetch data from server
