### ISSUE TITLE
Is there a double click event feature in neovis.js?

### ISSUE THREAD

**Issue by SeXyTeA-x** [neo4j-contrib/neovis.js#371]
I want to implement the function of double-clicking the node, but I find that the api document seems to provide only the event of clicking the node, may I ask whether there is a double-clicking node event in neovis.js

**Comment by thebestnom** [comment]
Hmm... The neovis api doesn't have it, you jave 2 options, hook the network object normal double click api and check which node/rel was clicked, second options is to add it to neovis and open PR which is always welcome 😄

**Comment by SeXyTeA-x** [comment]
emmm,do you mean to use this？
`viz.network.addEventListener('dblclick', function(event) {
                console.log(event)
});`
But the code is wrong

**Comment by thebestnom** [comment]
Yes, but make sure that's it runs after the render completes

**Comment by SeXyTeA-x** [comment]
Here's how I use it：
```js
viz.registerOnEvent('completed', (e) => {
                console.log(viz.network);
                viz.network.addEventListener('dblclick', function() { 
                    console.log(1) 
                });
 });
```
But console.log(1) is not triggered when I double-click

**Comment by thebestnom** [comment]
https://visjs.github.io/vis-network/docs/network/#Events
The event is named doubleClick

**Comment by SeXyTeA-x** [comment]
Oh, I didn't pay attention. Thank you for your patience

**Comment by thebestnom** [comment]
No problem 😄
