### ISSUE TITLE
How do I get the return value of cypher

### ISSUE THREAD

**Issue by SeXyTeA-x** [neo4j-contrib/neovis.js#373]
Sorry, I have another question, when I am using this. Viz. RenderWithCypher (cypher) execution of cypher statement, how to obtain the return values of cypher statements. For example, if I am executing
`MATCH p = allshortestpaths((a)-[r*0..4]-(b)) WHERE a.name = "${this.object1}" AND b.name= "${this.object2}" RETURN p,extract(n in nodes(p)| n.name)`
 how do I get the returned `extract(n in nodes(p)| n.name)` value

**Comment by thebestnom** [comment]
Use the neo4j driver directly, neovis doesn't saves the output directly, you can use vis.nodes or vis.edges and from there get the raw node, but you can't get any other data from there

**Comment by SeXyTeA-x** [comment]
Ok, I see. Thank you
