### ISSUE TITLE
Add label to all the relationship by default

### ISSUE THREAD

**Issue by pviral** [neo4j-contrib/neovis.js#381]
Hi,

I want to show labels for all the edges in the node. However, it seems like the library only shows labels when mentioned under the relationship object in the config. Is there a configuration where I can show all the relationship label?
```
relationship: {
   <RELATIONSHIP_NAME>: {}
}
```
## Expected Behavior (Mandatory)
Screenshot from neo4j desktop
<img width="458" alt="Screenshot 2024-01-31 at 3 30 20 PM" src="https://github.com/neo4j-contrib/neovis.js/assets/739767/746a770f-76aa-4a5a-bb7c-5ffd4b12f378">

## Actual Behavior (Mandatory)
Notice that the relationship label is missing
<img width="541" alt="Screenshot 2024-01-31 at 3 31 13 PM" src="https://github.com/neo4j-contrib/neovis.js/assets/739767/4306f672-92e4-4a2c-b110-8837b1a59c8e">

## How to Reproduce the Problem
Get the latest sample example from the directory and do

### Simple Example
Took the example from README.md

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: macOs
  - Library: neovis.js
  - Neo4j: 4.4.20

**Comment by ptrjeffrey** [comment]
I have the same issue too.BTW, the arrows are hidden as well

**Comment by ptrjeffrey** [comment]
Hi Guy,I found the answer there
#353  and #369 
Finally, I fixed all the issues.The result of my test project likes below
<img width="424" alt="无标题" src="https://github.com/neo4j-contrib/neovis.js/assets/13477121/7bf3f756-51a0-42a7-beb2-522e831aa753">
I think you can close the issue
