### ISSUE TITLE
 Error - Cannot read property 'constructor' of null while using Neovis.js

### ISSUE THREAD

**Issue by suchetaswabhav** [neo4j-contrib/neovis.js#40]
Information:

neo4j version - 3.4.7 Enterprise,
browser version - Version 3.4.7
what kind of API / driver do you use - I am using Neovis.js
With cypher query -
var cypherQuery =

      "MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m LIMIT 10";

**I get proper response -**

![neovis-1](https://user-images.githubusercontent.com/37062796/46991410-7b731400-d123-11e8-9e0f-eb9df0025914.png)

**Issue is - I get an error message**

      ERROR TypeError: Cannot read property 'constructor' of null

when my Limit in the cypher query increases beyond 10.

(say )- var cypherQuery =

         "MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m LIMIT 15";

**complete log of error -**

ERROR TypeError: Cannot read property 'constructor' of null
at neovis.js:36514
at Record.forEach (neovis.js:33630)
at Object.onNext (neovis.js:36511)
at _RunObserver.onNext (neovis.js:33014)
at Connection._handleMessage (neovis.js:31442)
at Dechunker.Connection._dechunker.onmessage (neovis.js:31392)
at Dechunker._onHeader (neovis.js:30537)
at Dechunker.AWAITING_CHUNK (neovis.js:30490)
at Dechunker.write (neovis.js:30548)
at WebSocketChannel.self._ch.onmessage (neovis.js:31365)

Please help.

**Source code -**

      const url = 'bolt://localhost:11001';
      const username = 'neo4j';
      const password = 'Vab1';
      const encrypted = true;
 
MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n,r,m LIMIT 30

        var cypherQuery = "";
 
         var config = {
         container_id: "viz",
         server_url: "bolt://localhost:11001",
         server_user: "neo4j",
         server_password: "Vr123",
         labels: {
        
            "Banking": {
                "caption": "name",
                "size": "pagerank",
                "community": "community"
               
                 }
              },
             relationships: {
              "cc": {
                "thickness": "weight",
                "caption": false
                }
           },
       RETURN cc",
 
            initial_cypher: cypherQuery ,        
            arrows: true,
            hierarchical_layout:true,
             hierarchical_sort_method:"directed",
       
            };                 
           this.viz = new NeoVis.default(config);  
 
           this.viz.render();
           console.log(this.viz);
            }

**Comment by alexwbaule** [comment]
OPTIONAL MATCH is returning 'null' if dont have match, and the lib dont treat it.

**Comment by thebestnom** [comment]
Should be fixed after the newer version will be released

**Comment by sai-velamuri** [comment]
Is this fixed yet? @thebestnom

**Comment by thebestnom** [comment]
Yes, it should have been fixed by the last update, try updating (if you are using npm/yarn) and see for yourself

**Comment by gegedenice** [comment]
Hello, I've been updating with npm to neovis.js@1.2.0 (using Neo4j 3.5 community edition) and I always have the same error with null properties from Cypher OPTIONAL query.
Thanks

**Comment by thebestnom** [comment]
I will test that later today

**Comment by pborah88** [comment]
This is my query -

```
match (n:Report)
with n
optional match (m)-[r]->(n)
optional match (n)-[r1]->(o)
return *
```

And this is the error I'm getting on the console - 

```
web.dom-collections.for-each.js (13,1)

[object Error]: {description: "Unable to get property 'constructor' of undefined or null reference", message: "Unable to get property 'constructor' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'constructor' of undefined or null reference at Anonymous function (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:32:102848) at d (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:30:309371) at Anonymous function (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:30:309159) at e[t] (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:30:309787) at h (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:32:98691) at s (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:32:98903) at Anonymous function (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:32:98962) at N (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:30:303200) at Anonymous function (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:32:98837) at Anonymous function (https://cdn.neo4jlabs.com/neovis.js/master/neovis.js:32:104968)"}
```

**Comment by thebestnom** [comment]
Ill test it later today, shouldn't happned on the latest version of neovis

**Comment by thebestnom** [comment]
It looks like cdn/master is not the last (cant fully confirm cause im not part of neo4j try to use 
https://cdn.neo4jlabs.com/neovis.js/v1.2.1/neovis.js
Instead

**Comment by pborah88** [comment]
> It looks like cdn/master is not the last (cant fully confirm cause im not part of neo4j) try to use
> https://cdn.neo4jlabs.com/neovis.js/v1.2.1/neovis.js
> Instead

Thank you very much! This works!
