### ISSUE TITLE
Same color for same Relationship nodes/same Origination nodes

### ISSUE THREAD

**Issue by suchetaswabhav** [neo4j-contrib/neovis.js#46]
Hi,

We have a concern. As showed in the example diagram , all the same originated nodes or probably same relationship nodes here have same color

![api_mining_samecolor](https://user-images.githubusercontent.com/37062796/49148790-5aaafa80-f32e-11e8-8c83-a0a794324a83.png)

but in my neovis.js we get a different output of colors of the nodes belonging to the same relationship/  origination from the same node-

![api_mining_neovis_different_color](https://user-images.githubusercontent.com/37062796/49148964-d2792500-f32e-11e8-940a-52187ef197a7.png)

Can this issue of different colors be resolved  and that the color of the node be made the same as its relationship parameter.

**Comment by NareshShetty** [comment]
@suchetaswabhav Any solution for specifying the colors to nodes?

**Comment by thebestnom** [comment]
Should be trivial in 2.x

**Comment by PatK19** [comment]
@thebestnom I am also trying to color code some labels, but the trivial solution as shown in the image does not work. 
currently i am using version 2.0.2
![2022-12-11 17_36_47-● GraphVisualization jsx - seba-lab-ws22-23 - Visual Studio Code](https://user-images.githubusercontent.com/50517642/206916470-54d365fb-f2ba-4d37-b663-26d4735bd18c.png)

**Comment by PatK19** [comment]
Thank you for you quick reply. I figured that i am using it wrong, but couldn't find the proper way to implement it. 
Am i reading in the right docs, or did i get the starting point wrong (https://neo4j-contrib.github.io/neovis.js/interfaces/NeoVisAdvanceConfig.html#static)?
`labels: {
          FieldOfStudy: {
            label: "displayName",
            title: "displayName",
            [NeoVis.NEOVIS_ADVANCED_CONFIG]: {
              static: {
                color: "#123456",
              },
            },
          },
}`
Defining the color under static in advanced config isn't working either.

I am sorry for my lack of knowledge, but i just started using Neovis.

**Comment by thebestnom** [comment]
Can you give some more info, like how are you inporting NeoVis?

**Comment by PatK19** [comment]
`import NeoVis from "neovis.js/dist/neovis.js";`
Im using it inside of a .jsx file 
The draw function with the `const config` are inside of reacts useEffect.
I am able to get the graph visualized, yet i am not able to change the color or shape of nodes with a specific label (like FieldOfStudy). 
Unfortunately i am not able to use group because of the structure of the database i was given.

**Comment by PatK19** [comment]
This was actually my problem, thank you very much 👍
