### ISSUE TITLE
How to make a uniform color for a set of nodes in neovis.js / vis.js

### ISSUE THREAD

**Issue by suchetaswabhav** [neo4j-contrib/neovis.js#49]
I am working with Neo4j application. And it creates nodal graph. To display the nodal graph on UI , we have Neovis.js. Neovis.js name taken from vis.js. The output that i get is -

![organisationdashboard](https://user-images.githubusercontent.com/37062796/50482167-51837b00-0a0b-11e9-8bf8-8be87cbfcb2e.png)

Here in the picture, all the nodes have a different color. We have relationships like Department, Function, System, Parameter,etc. I want a uniform color for all the nodes with relationship - Parameter and all the nodes with relationship - Department, etc. As in this pic -

![uniform-dash](https://user-images.githubusercontent.com/37062796/50482175-5cd6a680-0a0b-11e9-9069-60468307e010.png)

Please suggest changes in the following codes. It will be very useful.

code -

**visjs in Neovis.js** 

   

    visjs: {
            interaction: {
                hover: true,
                hoverConnectedEdges: true,
                selectConnectedEdges: false,
      
                multiselect: 'alwaysOn',
                zoomView: false,
                experimental: { }
            },
            physics: {
                barnesHut: {
                    damping: 0.1
                }
            },
            nodes: {
                mass: 4,
                shape: 'neo',
                labelHighlightBold: false,
                widthConstraint: {
                    maximum: 40
                },
                heightConstraint: {
                    maximum: 40
                }
            },
            edges: {
                hoverWidth: 0,
                selectionWidth: 0,
                smooth: {
                    type: 'continuous',
                    roundness: 0.15
                },
                font: {
                    size: 9,
                    strokeWidth: 0,
                    align: 'top'
                },
                color: {
                    inherit: false
                },
                arrows: {
                    to: {
                        enabled: true,
                        type: 'arrow',
                        scaleFactor: 0.5
                    }
                }
            }
    
        }

**front-end Neovis.js to display nodes**

          var config = {
             container_id: "viz",
             server_url: "bolt://localhost:7474/",
             server_user: "neo4j",
             server_password: "ib1",
            labels: {
                 //"Character": "name",
                 "Banking": {
                     "caption": "name",
                     "size": "pagerank",
                     community: "community",
                  
                     "sizeCypher": "MATCH (n) WHERE id(n) = {id} MATCH (n)-[r]-() RETURN sum(r.weight) AS c"
                 },
                 "Parameter": {
                    "thickness": "weight",
                    "caption": true,
                    community: "community",
                    "sizeCypher": "MATCH (n) WHERE id(n) = {id} MATCH (n)-[r]-() RETURN sum(r.weight) AS c"
                },
                "Method": {
                   "thickness": "weight",
                   "caption": true,
                   community: "community",
                   "sizeCypher": "MATCH (n) WHERE id(n) = {id} MATCH (n)-[r]-() RETURN sum(r.weight) AS c"
               },
               "Request": {
                   "thickness": "weight",
                   "caption": true,
                   community: "community",
               },
               "Response": {
                   "thickness": "weight",
                   "caption": true,
                   "community": "Pink"
               },
               "Paths": {
                   "thickness": "weight",
                   "caption": true,
                   "community": "Purple"
               },
               "API": {
                   "thickness": "weight",
                   "caption": true,
                   "community": "Black"
               },
               "Department": {
                   "thickness": "weight",
                   "caption": true,
                   community: "community",
                   "sizeCypher": "MATCH (n) WHERE id(n) = {id} MATCH (n)-[r]-() RETURN sum(r.weight) AS c"
               },
               "System": {
                   "thickness": "weight",
                   "caption": true,
                   "community": "Red"
               },
                 
             },
             relationships: {
                 "Parameter": {
                     thickness: "weight",
                     caption: true,
                     community: "community",
                     color:'red'
                 },
                 "Method": {
                    "thickness": "weight",
                    "caption": true,
                    "community": "Blue",
                    'color':'red'
                },
                "Request": {
                    "thickness": "weight",
                    "caption": true,
                    "community": "Red",
                    'color':'green'
                },
                "Response": {
                    "thickness": "weight",
                    "caption": true,
                    "community": "Red",
                    'color':'black'
                },
                "Paths": {
                    "thickness": "weight",
                    "caption": true,
                    "community": "Red",
                    'color':'pink'
                },
                "API": {
                    "thickness": "weight",
                    "caption": true,
                    "community": "Red",
                    'color':'pink'
                },
                "Department": {
                    "thickness": "weight",
                    "caption": true,
                    "community": "Red",
                    'color':'pink'
                },
                "System": {
                    "thickness": "weight",
                    "caption": true,
                    "community": "Red",
                    'color':'pink'
                },
             },
           
             initial_cypher:cypherQuery ,        
            arrows: true,
            hierarchical_layout:true,
            hierarchical_sort_method:"directed",
            
         };

**Comment by DurkoMatko** [comment]
I'm having the same issue. It's a shame this hasn't been addressed/answered anywhere. Well structured question, posted on StackOverflow as well as here...and ignored on both platforms. Very disappointing

**Comment by vincentkollebolle** [comment]
up up :)

**Comment by Nathiy** [comment]
I'm having the same problem as well and I've been looking for solutions all over

**Comment by DurkoMatko** [comment]
@Nathiy this project is dead, I've switched to using vis.js after realizing it. So far very happy about it, documentation is great and configuration options are endless.

**Comment by Nathiy** [comment]
Thank you, I'll check it out

**Comment by aguinaldoabbj** [comment]
> @Nathiy this project is dead, I've switched to using vis.js after realizing it. So far very happy about it, documentation is great and graph customisation options are wide. The downside (obviously) is that you have to manually fetch and preprocess the data rather than write the cypher query.

Can you share your work on this?

**Comment by jfcantu** [comment]
> Can you share your work on this?

@aguinaldoabbj Not sure if you're still looking for this, but I switched to `vis.js` based on this thread and it's worked well for me. Feel free to e-mail me at john.cantu@dreambox.com if you're interested so we don't hijack this thread.

**Comment by LukasRasmussen** [comment]
@thebestnom Are there any plans to address this issue?

**Comment by thebestnom** [comment]
Im pretty sure you can easily do this in 2.0.x, Im just got ditracted and havnt had the time to publish it

**Comment by LukasRasmussen** [comment]
I haven't tried 2.0.x. I read the issue where you talked about it with someone but I didn't fully understand the difference between current version and 2.0.x. My goal was to color nodes dynamically depending on some node attributes or labels depending on what kind of node (node label) it is. I thought to maybe use visjs instead since there's better possibilities for more configuration. What are your thoughts on this?

**Comment by thebestnom** [comment]
You can easily do it in 2.0.x that was the point of it, what it does is to allow you to map any node/rel thing to any vis.js config

**Comment by LukasRasmussen** [comment]
Do you have any examples to change colors? I just looked through the repo without finding any proper example (only one where you set node shape). I also noticed there's quite a few issues regarding styling so it might save you some time answering those questions. Would be lovely to be able to set colors through a function so you can style it with advanced logic.

**Comment by thebestnom** [comment]
@LukasRasmussen have you managed 😅 should be trivial in 2.x

**Comment by LeviWadd** [comment]
@LukasRasmussen How did you solve the colour issue? I'm trying to use the `community` property of the labels but no luck so far.

**Comment by thebestnom** [comment]
@LeviWadd use group property, that a bug on my part, by default I need to add group=label by default and I forgot on 2.0 😅

**Comment by LeviWadd** [comment]
@thebestnom thanks for quick response, I figured it out last night after a bit more playing around. Couple of related questions:
1. Is it possible to colour the nodes directly based on node type? At the moment I have to add some property P to each node type and then do group: "P", what I'd like to do is skip that step and have some way to query the node type directly so that, for example, nodes of type Person can be one colour, nodes of type Movie can be another etc.
2. Is it possible to change the default colours of the nodes used by group? I'm not a big fan of the yellow xD

**Comment by thebestnom** [comment]
You can set group color in the override vis config, and someone just use static config that the group will just be the label name, or you can use function config to get the label that way (the function gets the raw node/relationship)

**Comment by hutao95814** [comment]
Excuse me, do you have a solution to this problem?

**Comment by hutao95814** [comment]
I want to change the color of the nodes according to the node type, because my graph has many different types of nodes, but I tried many methods and it doesn't work

**Comment by thebestnom** [comment]
@hutao95814 by default on the latest version it's different color per label, you can use advance config to map specific color per label, if you need more specific help please open a different discussion
