### ISSUE TITLE
Using a Non-GoT (different schema) database

### ISSUE THREAD

**Issue by kaveUW** [neo4j-contrib/neovis.js#5]
Howdy,

What do I need to change in order to use a different database with different schema? It seems I can only get the visualization with the Game of Thrones data.

I've tried editing var viz: function draw labels and initial_cypher based on my database. And of course I've change the server_password, but there must be other items I need to address.

Can you please help?

Many Thanks,

Keith

**Comment by johnymontana** [comment]
Hi @kaveUW - you'll want to specify configuration in the `config` object passed to the `NeoVis` constructor with details specific to your database. 

In addition to the connection info you'll want to specify the node labels and relationship types you want to visualize (including the properties to be used for captions) as well as the initial Cypher query to populate the visualization.

~~~
var config = {
                container_id: "viz",
                server_url: "bolt://localhost:7687",
                server_user: "neo4j",
                server_password: "sorts-swims-burglaries",
                labels: {
                    "Character": {
                        "caption": "name",
                        "size": "pagerank",
                        "community": "community"
                    }
                },
                relationships: {
                    "INTERACTS": {
                        "thickness": "weight",
                        "caption": false
                    }
                },
                initial_cypher: "MATCH (n)-[r:INTERACTS]->(m) RETURN *"
            };

            viz = new NeoVis.default(config);
            viz.render();
~~~

It sounds like you may have tried that already though. Can you share your code?

**Comment by kaveUW** [comment]
thanks so much for your help!

I have many node/label types: Brewery, Person, BeerType, BarrelAged, BreweryRating, Beer, BreweryLocation, Animal. 

Relationships: IS_BARREL_AGED, IS_LOCATED, IS_A, RATES_BEER, RATES_BREWERY, BREWS

Do I have to have all of the labels/nodes & relationships represented in the var config? 
I'm starting off just representing a couple nodes/labels with one relationship. 

   var config = {
                container_id: "viz",
                server_url: "bolt://localhost:7687",
                server_user: "neo4j",
                server_password: "neo4j",
                labels: {
                    "Beer": {"caption": "name" },
		   "Brewery": {"caption":"name"}
                },
                relationships: {
                    "BREWS": {"caption": false}
                },
		initial_cypher: "MATCH (n)-[r:BREWS]->(m) RETURN n,r,m Limit 30"
            }; 
            viz = new NeoVis.default(config);
            viz.render();

**Comment by kaveUW** [comment]
Also, how do I go about connecting to my Graphenedb instance of neo4j?

I've tried the following to connect to the instance, but it's not connecting, what else do I need to do?

server_url: "bolt://hobby-ihjbochbhigjgbkecidndkal.dbs.graphenedb.com:24786",
server_user: "user",
server_password: "1234",

**Comment by johnymontana** [comment]
Yes, you'll need to specify each label and the configuration for that label in the config. Any labels not specified won't be added to the visualization.

Regarding the connection issue - can you check the developer console for any error messages?

**Comment by kaveUW** [comment]
Thanks your comments helped consider this closed
