### ISSUE TITLE
A graph showing different root nodes,as this

### ISSUE THREAD

**Issue by liufan1993** [neo4j-contrib/neovis.js#57]
A graph showing different root nodes,as this
![image](https://user-images.githubusercontent.com/24200096/54905071-1534bd80-4f1b-11e9-995a-047cb367bdad.png)

There is now a requirement, a graph has multiple root nodes, but an error is reported with neo4jd3.js
![image](https://user-images.githubusercontent.com/24200096/54905078-1b2a9e80-4f1b-11e9-89fd-8d00ead00c22.png)

**Comment by thebestnom** [comment]
Nothing to do with neovis 😅
