### ISSUE TITLE
Can I expose an interactive neo4j visualization (safely) to users over the internet?

### ISSUE THREAD

**Issue by rtruxal** [neo4j-contrib/neovis.js#60]
Hi - I'm making a [web app](https://github.com/rtruxal/webmap-webapp) to display some of the cool things you can do with graph back-ends, and this repo has been terrific for testing locally. (Kudos & thanks!!!)

[See my open question on StackOverflow.](https://stackoverflow.com/questions/55929740/how-can-i-expose-an-interactive-neo4j-visualization-safely-to-users-over-the-i)

My application (finally) works, and I'm in the process of trying to stand it up on one of my cloud VMs. However, the examples here all embed credentials directly into client-side code, and also seem to assume I can make a _direct_ connection to Neo4j.

Aside from my unease at exposing my back-end directly to clients over the internet, I can't afford the neo4j enterprise edition & so I don't think I can set up RBAC. This means I can't swap out the embedded admin credentials for read-only credentials.

Is there a way I can still use this library without handing out plaintext admin credentials to clients?

**Comment by rtruxal** [comment]
There is another branch of this repo called `more-data-options` which allows one to specify an object full of nodes an edges, as opposed to connecting directly to Neo4j with a driver. 

That allowed me to make my read-request from the server-side, and then expose the data to my webapp via CORS. No more credentials embedded in the browser!

**Comment by jeffg2k** [comment]
@jexp Any reason this was never merged into the master branch?  Seems like it would be a necessary feature.  I see there is an option for `Version without neo4j-driver dependency` - does that allow you to put the creds server side?  Our biggest issue with `neovis.js` is putting the creds in the client side code.

**Comment by thebestnom** [comment]
What im trying to do is to make every configuration of neovis to be superset of existing configuration instead, after that I think that sending existing neo4j driver would be that benefitial, and if it is still make sense after I break api, I could add that more easily instead of making more patch work in the current situation
