### ISSUE TITLE
Neovis-ts sizing needed on canvas instead of div

### ISSUE THREAD

**Issue by sirhallt** [neo4j-contrib/neovis.js#65]
When Integrating with Angular app using neovis-ts from npm I have found that if I set the height of the div that the convas is drawn in the convas does not auto-resize to fit and thereby the tooltip on the left side is hidden,  Can there be an option to resize the canvas and not just the parent div?

**Comment by thebestnom** [comment]
Im pretty sure thats a vis thing, 
https://github.com/almende/vis/issues/917
It looks like after resizing you should call network.fit()
Im pretty sure you can get the network by `youneovisinstance._network`

**Comment by sirhallt** [comment]
Thank you.  It appears that the vis._network object is private in NeoVis-ts so I can’t access it.

**Comment by thebestnom** [comment]
Yes, it is private, for now you can use `as any`, but maybe someone will have time to add a public getter for it or somthing and open a pr for it

**Comment by thebestnom** [comment]
Did it work? If so I would like if you close this issue and if you still need open an issue with the feature request you need (probebly the d.ts and getter for the network)

**Comment by sirhallt** [comment]
Can you explain how to use as Any to get it as public?

Thank you

**Comment by thebestnom** [comment]
`(neovisinstance as any)._network` it doesnt exactly makes it public, more makes ts interpret it as plain js object... (Bad hack, dont use it if not needed)

**Comment by sirhallt** [comment]
Ok thank you it worked
