### ISSUE TITLE
Neovis not working in Angular

### ISSUE THREAD

**Issue by viveksacademia4git** [neo4j-contrib/neovis.js#67]
## Neovis.js not working in Angular
  
Angular Version 8  
  
While trying to integrate the Neovis.js in the Angular project, getting the following error and due to this even the single page from the application does not load:  
  
![image](https://user-images.githubusercontent.com/45398326/65159675-c03eb380-da34-11e9-9261-fd9eb6131dfc.png)
  
Code in the component  
```
import NeoVis from 'neovis.js/dist/neovis.js';
..
export class DirectedGraphComponent implements OnInit {
..
ngOnInit() {
    var config = {
      container_id: "viz",
      server_url: "bolt://localhost:7687",
      server_user: "neo4j",
      server_password: "neo4j",
      labels: {
          //"Character": "name",
          "Character": {
              "caption": "name",
              "size": "pagerank",
              "community": "community"
              //"sizeCypher": "MATCH (n) WHERE id(n) = {id} MATCH (n)-[r]-() RETURN sum(r.weight) AS c"
          }
      },
      relationships: {
          "INTERACTS": {
              "thickness": "weight",
              "caption": false
          }
      },
      initial_cypher: "MATCH (n)-[r:INTERACTS]->(m) RETURN n,r,m"
    };

    var viz = new NeoVis.default(config);
    viz.render();
  }
}
```

**Comment by thebestnom** [comment]
I would highly suggest to try import by `import NeoVis from "neovis.js"` instead, can you test that?

**Comment by thebestnom** [comment]
Have you tested it?

**Comment by viveksacademia4git** [comment]
I have tested it. Its not working.  
I created another project to test the functionalities specifically for the Neovis.js.  
Please check this (Issue)[https://github.com/viveksacademia4git/neovis-test/issues/1] created in the another repository

**Comment by thebestnom** [comment]
Ok, I looked for a bit and it looks like I used poltfill the wrong way, will fix somtimes this week, and hope that it will get merged

**Comment by viveksacademia4git** [comment]
Okay, thank you @thebestnom.  
I will keep a watch and test the functionality in my workspace.  
If possible, add a comment after check-in.

**Comment by viveksacademia4git** [comment]
Hello @thebestnom do you have any update on this or a timeline?

**Comment by thebestnom** [comment]
No, sorry didn't have time this week, ill probably try tomorrow

**Comment by viveksacademia4git** [comment]
@thebestnom Okay, thank you.

**Comment by thebestnom** [comment]
well, I tested it and it should be fixed after the PR will be merged and a new version will be published...
@johnymontana to your knowledge
