### ISSUE TITLE
Installing Neovis.js on Typescript project

### ISSUE THREAD

**Issue by alexandrupetrescu94** [neo4j-contrib/neovis.js#7]
I tried to install neovis.js on a Ionic2/Typescript project so I tried the following:

**Solution:** Adding the library in the CDN version and declaring it into the project:
`declare let NeoVis: any;` will work. 
**Is there any way to fetch the database from backend and just add the results to NeoVis?** I am asking this because the bolt conector seems to be deprecated while using cloud databases and I am unable to connect (and the HTTPS:// is not recognized):

> WebSocket connection failure. Due to security constraints

**Other failures trying to add the library into Typescript app:**
**1.** First to add a lib folder with neovis already added and to just import neovis.js from src. Although, this way to use the library is not working due to the vendor libraries which are not installed and by typing npm install on the library will not install also those submodules.

**2.** I also tried to install it with npm:
`npm install https://github.com/johnymontana/neovis.js.git --save`

But I am getting: 

> Failed to clone 'vendor/neo4j-javascript-driver'. Retry scheduled

Is there any way to use NeoVis with Typescript?

**3:** Even if I try to clone the project I am unable to fetch the vendor files by using: 
`git clone REPO --recursive`

**4:** I installed in the main project both vendor libraries, and changed the references to them and also changed from .js to .ts the src files.
I am getting now 
> hammer.assign is not a function error
This seems to be an error found also on VIS library.

**Comment by mhoangvslev** [comment]
A TypeScript conversion would be awesome!
An attempt can be found on my fork of this repo.

**Comment by thebestnom** [comment]
I did not find who is managing neovis-ts last time I checked, I would add an index.d.ts later tonight and open a pr, it should be fairly easy

**Comment by thebestnom** [comment]
Added pr, waiting for merge
