### ISSUE TITLE
Control over the color of the nodes displayed

### ISSUE THREAD

**Issue by vvvasilev** [neo4j-contrib/neovis.js#71]
I noticed that there are multiple requests for this, but without answers. Is there a way to control the color of the nodes and relations? I would like to be able to assign specific colors either to the communities or to specific node labels. Can this be done?

**Comment by thebestnom** [comment]
I checked and its looked like for now you can't, but, it looks like it shouldn't be too hard to do color by type... By community should take a little bit more time (because communities are dynamic and im not 100% how to implement it)

**Comment by NareshShetty** [comment]
@vvvasilev  You found any solution for this?

**Comment by thebestnom** [comment]
Trivial in 2.x
