### ISSUE TITLE
neovis.js not work in react

### ISSUE THREAD

**Issue by club326** [neo4j-contrib/neovis.js#73]
`import React from 'react';
import ReactDOM from 'react-dom';
import NeoVis from 'neovis.js'
import './index.css';

class NeoView extends React.Component {
  componentDidMount() {
    var config = {
      server_url: "xxx",
      server_user: "xxx",
      server_password: "xxx",
      initial_cypher: "MATCH p=()-[r:test ]->() RETURN p AS someName"
    };
    this.viz = new NeoVis.default(config);
    this.viz.render();
  }
  render() {return <div id="viz"></div>;}
}

ReactDOM.render( < NeoView / > , document.getElementById('root'));`

**Comment by thebestnom** [comment]
What is the error that it shows?

**Comment by club326** [comment]
![image](https://user-images.githubusercontent.com/10458166/66985827-35fb7500-f0f0-11e9-8371-8edce73de336.png)

**Comment by club326** [comment]
thanks,it's ok now!
