### ISSUE TITLE
Neovis > Failing License Check due to > Emitter Component  

### ISSUE THREAD

**Issue by viveksacademia4git** [neo4j-contrib/neovis.js#76]
Neovis is Failing License Check due to it's dependency upon **Emitter Component** library.  

Please refer to the [Issue-87](https://github.com/component/emitter/issues/87) created within the [emitter-component](https://github.com/component/emitter) GitHub Repository.

**Comment by viveksacademia4git** [comment]
Neovis is dependent on Vis which is further dependent on Emitter Component.

In order to check this, scan the ‘package lock’ file (for npm) or ‘yarn lock’ file (for yarn).

**Comment by viveksacademia4git** [comment]
Hello @tj or @vendethiel,  
If you guys are busy, then maybe I contribute to this.

**Comment by vendethiel** [comment]
I don't own it and can't change the license.

**Comment by viveksacademia4git** [comment]
@vendethiel Sorry, I meant for [component/emitter](https://github.com/component/emitter) not [neovis.js](https://github.com/neo4j-contrib/neovis.js)

**Comment by vendethiel** [comment]
I know.
