### ISSUE TITLE
Canvas 'height' attribute is causing styling problem for style's > height

### ISSUE THREAD

**Issue by viveksacademia4git** [neo4j-contrib/neovis.js#77]
Canvas `height` attribute is causing the `style="height:100%"` to not assign the height to canvas properly. Attached is the screenshot:  

![image](https://user-images.githubusercontent.com/45398326/68074436-4459ba00-fd9b-11e9-9ff1-db5c34109e6c.png)

![image](https://user-images.githubusercontent.com/45398326/68074507-fe512600-fd9b-11e9-977e-f86de768d67d.png)

**Comment by thebestnom** [comment]
It's uses vis.js, it looks like something in it, check if someone asked a similar thing there, https://github.com/almende/vis/issues/1832

**Comment by viveksacademia4git** [comment]
Okay, I will check.

**Comment by thebestnom** [comment]
Trivial in 2.x
