### ISSUE TITLE
Mismatched graph between neo4j browser and neo4jvis

### ISSUE THREAD

**Issue by muon3** [neo4j-contrib/neovis.js#78]
I adapted the example for my own graph database but I got different results in the neo4j desktop and neovis. 

Here's the query in my desktop:
match (m1)<-[r:is_keyword]->(m2) RETURN * limit 10
![image](https://user-images.githubusercontent.com/43165808/68650180-50920400-055f-11ea-956e-211229acbcd5.png)

The initial_cypher in index.html:
"MATCH (m1)<-[r:is_keyword]->(m2) RETURN * LIMIT 10"

![image](https://user-images.githubusercontent.com/43165808/68650280-90f18200-055f-11ea-836e-6fde0ebd8c4a.png)

Specifically the number of relationships for "approaches" is 5 in the desktop but only 4 in neo4jvis. Can anyone explain what could be causing this mismatch?

Thanks!
muon3

**Comment by dukesun99** [comment]
I feel the neo4j browser is auto-populating the graph with some relationships not returned by the query. I think neovis is displaying the "correct" result.

**Comment by thebestnom** [comment]
Ill @dukesun99 continue what said. you can get the correct result in Neo4j browser by disabling auto connect in options
