### ISSUE TITLE
Applying adaptive edge thickness to all relations and not one

### ISSUE THREAD

**Issue by navidre** [neo4j-contrib/neovis.js#83]
Is there a way to set relationship edge thickness without specifying the edge label? Say the thickness to be variable based on the width value of the relationship. This applies to all relationships, regardless of type.

Currently, it seems that we have to specify the relationship type in order to do this:
```
relationships: {
   "INTERACTS": {
      "thickness": "weight"
   }
},
```

If this feature does not exist, consider this as a feature request. Did not have access to label it so.

**Comment by pborah88** [comment]
This feature does not exist. Would be really helpful to have this. Most real world use cases will not have nodes connected by just one type of relationship and forcing this by adding an extra relationship to show different types of nodes interacting with each other via a single relationship type just makes the overall graph extremely messy.

**Comment by thebestnom** [comment]
Implemented default configs by custom symbol `NeoVis.NEOVIS_DEFAULT_CONFIG`, I wish it could be merged quickly.... also implemented it on labels while I was at it
