### ISSUE TITLE
Error when turning on Encryption

### ISSUE THREAD

**Issue by promentol** [neo4j-contrib/neovis.js#89]
When turning on the encryption, by setting "ENCRYPTION_ON", It is not connecting to the server, instead it is showing the following error in chrome console.

    TypeError: Cannot read property 'close' of undefined
    at captureStacktrace (result.js:199)
    at new Result (result.js:65)
    at Session._run (session.js:152)
    at Session.run (session.js:130)

I made sure ssl is configured correctly, and neo4j browser is being served by ssl correctly. 

Is there some workaround on this??

**Comment by thebestnom** [comment]
Can you give a minimum code for replicating the error, it just never happened to me

**Comment by promentol** [comment]
@thebestnom Thank you for fast response. While making an example I realized, that `encryption: true` is working only in webpages, served by https, it is because of neo4j driver. Sorry for disturbing.
