### ISSUE TITLE
Caption missing from the graph 

### ISSUE THREAD

**Issue by Ard1tSelfo** [neo4j-contrib/neovis.js#91]
I have been using this library for the past months everyday and suddenly it seems that the captions are missing from the nodes. 
Some hours ago it worked fine actually.
<img width="714" alt="Screenshot 2020-02-15 at 22 48 23" src="https://user-images.githubusercontent.com/32358543/74595730-6bd04c00-5045-11ea-9b4b-6d3e4b76591f.png">

**Comment by mrgianlu** [comment]
I'm experiencing the same issue from the latest updates (10 days or so)
@johnymontana 
I saw you are taking care of the latest updates, do you have any hint for us?

**Comment by thebestnom** [comment]
Can you give minimum reimplement so I can test thos later?

**Comment by matethurzo** [comment]
It's the 1.3.0 release that messed up, if you are not relying on that version you can easily just reference the 1.2.1 version: <script src="https://cdn.neo4jlabs.com/neovis.js/v1.2.1/neovis.js"></script>
I had the same problem, but the 1.2.1 version works fine.

**Comment by mrgianlu** [comment]
@matethurzo 

correct, going back to v1.2.1 solved the problem.

Thanks, I'll be following closely the next development and looking forward for a bugfix.

**Comment by thebestnom** [comment]
fixed and opened a pr

**Comment by mrgianlu** [comment]
Thanks @thebestnom @matethurzo

**Comment by johnymontana** [comment]
The fix for this has been released in version 1.4.0. Please give that version a try

**Comment by matethurzo** [comment]
@johnymontana it's working now, thanks!
