### ISSUE TITLE
GPU accleration for rendering visualization

### ISSUE THREAD

**Issue by Roman-kazi** [neo4j-contrib/neovis.js#92]
Hi,
I am trying to load some medium size graphs on a mid spec system, but the visualization is taking very long to render and I also checked my dedicated NVIDIA GPU was sitting idle and the the ram usage went as high as 3 GB for a graph with 700 nodes.
Is there any way to force neovis.js rendering using dedicated GPU.
Thank you.

**Comment by KhemnarMayuresh** [comment]
Yes I have the same problem. It would be great if we can use GPU for rendering.

**Comment by shubhisharma30** [comment]
Yes,i also have a same problem.

**Comment by thebestnom** [comment]
Neovis.js uses vis.js (hence it's name 😅) which doesn't support gpu, maybe adding more output options is possible, but it does change most of the code so I don't think it will ever be implemented
