### ISSUE TITLE
Node label not displayed

### ISSUE THREAD

**Issue by raghav85** [neo4j-contrib/neovis.js#93]
Hi,

Have been fiddling around with below basic setup. Unable to get the label name on the nodes and only the relationship label is shown. Could you please tell me if there is any issue with the code below:
Thank you.

`function draw() {
			var config = {
				container_id: "viz",
				server_url: "bolt://localhost:7687",
				server_user: "admin",
				server_password: "admin",
				arrows: true,
				hierarchical: false,
				labels: {
					"Person": {
						"caption": "name",
						// "size": 50.0,
						"community": "name"
						//\"sizeCypher": "MATCH (n) WHERE id(n) = {id} MATCH (n)-[r]-() RETURN sum(r.weight) AS c"
					},
					"Movie": {
						"caption": "title",
						// "size": 50.0,
					
						//\"sizeCypher": "MATCH (n) WHERE id(n) = {id} MATCH (n)-[r]-() RETURN sum(r.weight) AS c"
					},

				},
				relationships: {
					"DIRECTED": {
						"thickness": "weight",
						"caption": true
					}
				},
				initial_cypher: "MATCH (p)-[r:DIRECTED]->(m) RETURN p,r,m"
			};

			viz = new NeoVis.default(config);
			viz.render();
			console.log(viz);

		}`

![Neovis_issue](https://user-images.githubusercontent.com/46476189/75036585-378edc80-54d8-11ea-945d-e7a8d7fb2089.png)

**Comment by raghav85** [comment]
Better code view for readability, appreciate your help:
![neovis_codeview](https://user-images.githubusercontent.com/46476189/75038571-a110ea00-54dc-11ea-86fe-2938a860efc6.png)

**Comment by matethurzo** [comment]
duplicate of: https://github.com/neo4j-contrib/neovis.js/issues/91 a PR has been opened for this as well

**Comment by raghav85** [comment]
Thank you. Closing the issue as it is tracked in #91
