### ISSUE TITLE
Is there a way add clickable nodes ?

### ISSUE THREAD

**Issue by aysuays** [neo4j-contrib/neovis.js#97]
Hello,
In div element we see the graphs,  when I right clicked to nodes is it possible to see tiny popup and in this popup there must be options like see dismiss and expand all child relations options like in neo4j. Is neovis.js capable of doing this?If yes, can you lead me a way please ? Thank you so much.

**Comment by thebestnom** [comment]
See https://github.com/neo4j-contrib/neovis.js/issues/16

**Comment by thebestnom** [comment]
Trivial in 2.x
