### ISSUE TITLE
Customizing vis.js settings

### ISSUE THREAD

**Issue by rcanzanese** [neo4j-contrib/neovis.js#99]
I tried customizing the physics by editing the vis.js settings in [defaults.js](https://github.com/neo4j-contrib/neovis.js/blob/master/src/defaults.js) and then building the package.  However, none of these settings went into effect. Where is the appropriate location to change the vis.js settings?

**Comment by a515978292** [comment]
I have also tried but it has no effect

**Comment by lucaslemos94** [comment]
Same here

**Comment by thebestnom** [comment]
Currently there is no way to programly change the values, only by changing the code in neovis.js file, but PR is welcomed

**Comment by thebestnom** [comment]
In 2.0.0 it is now fully supported 😄
